### ISSUE TITLE
[Bug] Unfocused tabs glitch out on dark reader global toggle

### ISSUE THREAD

**Issue by starcraft66** [darkreader/darkreader#10004]
# Bug Report

When I toggle dark reader globally (either manually or via automation), all of my unfocused tabs glitch out and I have to reload them to make them display correctly.

## Website Address
Affects every website

## Steps To Reproduce
1. Have a few tabs open
2. Toggle dark mode (via dark reader's gui) on one tab
3. Go to an unfocused tab

## Expected Behavior
Websites look normal in unfocused tabs.

## Actual Behavior
Websites look broken in unfocused tabs.

## Screenshots
Here's an example of a page that was unfocused when I toggled dark reader:
![image](https://user-images.githubusercontent.com/1858154/193956167-8bcbb747-aed8-4b44-a6f3-c2473bf2e8aa.png)

## System Information
- OS: macOS, Linux
- Browser: Firefox 105
- Dark Reader Version: 4.9.58

## Additional Context
This has happened to me for ever on multiple mac and linux computers. I just turned off all automations and never toggled the extension because it is maddening.

**Comment by PowerUser64** [comment]
This is happening to me as well. When I go to an inactive tab, DR does a strange 'half-dark theme', where elements that shouldn't be dark are set to be dark aren't. I'm especially noticing this with colored elements, which seem to get set to the page's background color.

A workaround is to toggle the page's dark theme off and back on (<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>a</kbd>, <kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>a</kbd>), but this is annoying because it flashes my eyes with light theme :P

**Comment by Gusted** [comment]
> I just turned off all automations and never toggled the extension because it is maddening.

Just to make sure, this issue is only observed when toggling the extension (either manually or via automation)?

**Comment by PowerUser64** [comment]
We're both using a similar workaround to get pages to look normal again. @starcraft66 is disabling the extension outright and I am toggling it off and on each time a site is broken to get it to do a proper dark theme conversion. I'm still trying to pin down exactly what causes this. It seems to be related to unfocusing tabs, but that doesn't always cause it. Some sites don't like to have other instances of the site have dark theme, so only one has dark theme, and when I switch to the other instances and refresh, the initial tab loses dark theme. Some sites don't do this though.

I actually downgraded to version 4.9.55 and the issue doesn't exist on that version. What's weird is I also encountered the issue when I downgraded to 4.9.57. I started encountering this issue around the 9/22/2022 update to 4.9.58, so I'm pretty sure it's related to that update. I have since tried upgrading back to 4.9.58, and the extension is working properly again ¯\_(ツ)_/¯

I don't know what exactly I did to fix it, but it seems to have to do with the downgrade/upgrade process. If I re-encounter the issue, I will definitely investigate it some more to see if I can find out more about what causes it.

It's also worth noting that I have the same setup as @starcraft66, running Linux, DR 4.9.58, and Firefox 105.0. I experienced this issue on both my desktop and my laptop which run Linux. I have not tried fixing it on my desktop using this method yet, but I will send another comment here if I try and it doesn't work.

**Comment by starcraft66** [comment]
> Just to make sure, this issue is only observed when toggling the extension (either manually or via automation)?

Yup.

**Comment by Luke-L** [comment]
> This is happening to me as well. When I go to an inactive tab, DR does a strange 'half-dark theme', where elements that shouldn't be dark are set to be dark aren't. I'm especially noticing this with colored elements, which seem to get set to the page's background color.
> 
> A workaround is to toggle the page's dark theme off and back on (alt+shift+a, alt+shift+a), but this is annoying because it flashes my eyes with light theme :P

ive had this problem for months now. its so fucking annoying on chrome. ive emailed the devs about this and included screenshots but gotten zero response

**Comment by wan7teen-ping** [comment]
Hi I will help you with everything you need but you have to subscribe to
the youtube channel and I will fulfill all your requests

https://youtu.be/aIaqr4eq18g


Pada Sab, 8 Okt 2022, 8:00 AM Luke-L ***@***.***> menulis:

**Comment by i-aka5h** [comment]
Same issue on edge

**Comment by Gusted** [comment]
> I actually downgraded to version 4.9.55 and the issue doesn't exist on that version. What's weird is I also encountered the issue when I downgraded to 4.9.57. I started encountering this issue around the 9/22/2022 update to 4.9.58, so I'm pretty sure it's related to that update. I have since tried upgrading back to 4.9.58, and the extension is working properly again ¯\_(ツ)_/¯

Oh that's quite weird, it could be a fluke... that sometimes unfortunately happens.

@starcraft66 Could you also try this? Re-installing Dark Reader.

----



> ive had this problem for months now. its so fucking annoying on chrome. ive emailed the devs about this and included screenshots but gotten zero response

I'm sorry to hear that, which email address have you tried mailing? I didn't receive any mail if you have tried mailing me.

----

Unfortunate there seems to be not a lot of actionable information here, other that it might happen. @bershanskiy Just to make sure, could you see if you are able to reproduce this issue? You somehow always have more "luck" than me.

**Comment by Gusted** [comment]
> I actually downgraded to version 4.9.55 and the issue doesn't exist on that version. What's weird is I also encountered the issue when I downgraded to 4.9.57. I started encountering this issue around the 9/22/2022 update to 4.9.58, so I'm pretty sure it's related to that update. I have since tried upgrading back to 4.9.58, and the extension is working properly again ¯\_(ツ)_/¯

Oh that's quite weird, it could be a fluke... that sometimes unfortunately happens.

@starcraft66 Could you also try this? Re-installing Dark Reader.

----

> ive had this problem for months now. its so fucking annoying on chrome. ive emailed the devs about this and included screenshots but gotten zero response

@Luke-L I'm sorry to hear that, which email address have you tried mailing? I didn't receive any mail if you have tried mailing me.

----

Unfortunate there seems to be not a lot of actionable information here, other that it might happen. @bershanskiy Just to make sure, could you see if you are able to reproduce this issue? You somehow always have more "luck" than me.

**Comment by PowerUser64** [comment]
Update: I tried doing the fix on my desktop and it didn't work.

The way I reproduce this is by middle-clicking a link (this one should do: https://www.opus-codec.org/) and then switching to the tab after the page has loaded. If the links on the left are a light grey color, the bug happened. Toggling the extension off and back on or refreshing the page will change the colors to the blue they should normally be.

**Comment by Gusted** [comment]
@PowerUser64 Do you have any other extension on your desktop? One could be interfering with Dark Reader, to detect when the tab is being visible to the user again.

**Comment by bershanskiy** [comment]
Based on the symptoms (tabs going to the fallback script) I had a guess that this could happen if the tab script or background script was unloaded and somehow they lost connections to each other. I tried to reproduce this but never managed to. Perhaps, I'm missing some crucial variable here:
 - how easy is it to reproduce?
 - for how long do you need to keep the unfocused tabs open?
 - how high is your system load during the times the bug appears? (E.g., what do you do after you open a tab, leave it in the background and before you reopen it again and see it being broken? Do you put your device to sleep?)
 - do you have any other extensions installed?

**Comment by PowerUser64** [comment]
I just tried this with a blank firefox profile and I didn't see the problem.

Here's how I tested:

```bash
mkdir deleteme
firefox --profile deleteme
# install darkreader and perform a test
rm -rf deleteme
```

After this, I went to my extensions page in my usual firefox profile and disabled half of my extensions, tested it, and repeated until it was fixed.

It turns out the extension causing the problem was a privacy extension that keeps websites from knowing when the site is focused (called [No Focus Spying](https://addons.mozilla.org/en-US/firefox/addon/no-focus-spying/)), and it seems as though darkreader uses this functionality to know when to convert a page to dark theme if it is a link opened in the background. I have this extension disabled now, and the problem has gone away. Maybe the other people here have a similar extension?

**Comment by Gusted** [comment]
> It turns out the extension causing the problem was a privacy extension that keeps websites from knowing when the site is focused (called [No Focus Spying](https://addons.mozilla.org/en-US/firefox/addon/no-focus-spying/)), and it seems as though darkreader uses this functionality to know when to convert a page to dark theme if it is a link opened in the background. I have this extension disabled now, and the problem has gone away. Maybe the other people here have a similar extension?

Alright that was something I was expecting, so then Dark Reader is working accordingly, Dark Reader doesn't know when you opened your tab, but this check can be disabled:
- Click Dark Reader icon.
- Click Dev tools (in the bottom-right corner).
- Click Preview new design.
- Go back to popup.
- Click See all options.
- Click Fonts & More.
- Enable Immediate modify.

That will fix the issue.

**Comment by bershanskiy** [comment]
@PowerUser64 This is incredibly useful information, thank you! I can reproduce this bug with No Focus Spying installed.

> It turns out the extension causing the problem was a privacy extension that keeps websites from knowing when the site is focused (called [No Focus Spying](https://addons.mozilla.org/en-US/firefox/addon/no-focus-spying/)),

Yes, Dark Reader uses visibility change events for optimizations. (In a nut shell, Dark Reader does not update styles on tabs which are currently not visible). We should be able to detect this kind of extensions and simply disable this optimization (like you do manually via "immediate modify" or use [`tabs.onActiveChanged`](https://developer.chrome.com/docs/extensions/reference/tabs/#event-onActiveChanged) or [`tabs.onActivated`](https://developer.chrome.com/docs/extensions/reference/tabs/#event-onActivated) instead. I'll look into it and we should have a fix in the next release.

No Focus Spying appears to have very few users. Perhaps, there are some other extensions which does the same thing but supports exclusions for other WebExtensions?

**Comment by PowerUser64** [comment]
Yeah, I use No Focus Spying for a few very specific purposes. I don't know if there are any other extensions that do it, but I can just make sure to disable it when I don't need it.

Thanks for the tip, @Gusted and @bershanskiy!

If you do add detection for extensions like this, I might recommend that you have some way of notifying the user this optimization is being disabled so they can adjust their setup if they want to have the optimization.

**Comment by bershanskiy** [comment]
Also, the entire No Focus Spying extension extension is just this:
```js
document.hidden = false;
document.visibilityState = 'visible';
for (events of ["visibilitychange", "webkitvisibilitychange", "blur"]) {
    window.addEventListener(events, function(event) {
          event.stopImmediatePropagation();
      }, true);
  }
```

We can detect existence of this script by creating a listener, then dispatching one of these events, and observing that this event was not delivered (so we conclude that it was intercepted by No Focus Spying).

**Comment by bershanskiy** [comment]
I confirmed that No Focus Spying causes Dark Reader to break on both Chrome and Firefox, and that [the fix in comment by @Gusted](https://github.com/darkreader/darkreader/issues/10004#issuecomment-1272512756) fixes it. I have a few workarounds in mind, I'll need to consider which one is best:
 - test for existence of No Focus Spying within the page context (bad, since page might have its own listeners and we don't really want to upset those)
 - inject a custom blank `<iframe>` into the page and test for No Focus Spying within it (bad, since would either require manifest modification to web_accessible_resources or would break on sites with good CSP)

> Yeah, I use No Focus Spying for a few very specific purposes. 

Could you please elaborate? I'm aware of one such use case: prevent a site (e.g., Reddit) from pausing/muting a video when tab is hidden. Perhaps, you could enumerate sites where you use No Focus Spying, explicitly add them to list of permitted sites (possible on Chrome without extension modification, on Firefox might require extension modification).

Frankly, the easiest way to handle this might be to document this limitation of No Focus Spying & Dark Reader interoperability and to create a custom fork of No Focus Spying which would intercept these events, cancel their propagation, but then deliver them to Dark Reader with a different name. Or use WebExtension APIs I listed earlier. I'll think of a way to do it.

**Comment by PowerUser64** [comment]
To the other people experiencing this here, if you want a quick fix, try isolating the extension that might be causing the problem.
I did this with these steps:

1. disable half of all enabled browser extensions (except darkreader, also keep track of which ones got disabled)
3. test if the bug exists (middle click a link)
5. repeat steps 1 and 2 until the problem doesn't happen
6. enable all the extensions except the ones that were disabled last
8. enable the remaining disabled extensions one-by-one until middle-clicking a link results in a broken page
9. disable the extension you just enabled and enable the rest
10. Profit

Once you find the extension that was causing the problem, consider sharing it here so we can see if our problem is being caused by the same thing, or if we're even experiencing the same problem.

**Comment by PowerUser64** [comment]
I use No Focus Spying (let's call it NFS) to change sites that check if they are focused in order to create features that end up just being annoying. I couldn't really say which sites I use it the most on because its effects are usually unnoticable. An example of one of these "features" I use NFS to combat is Intercom (advertising company) which has a thing that changes the site title to say "You have one message" and flashes it between two messages when you change tabs away from it (they're trying to get you to interact with the annoying chatbot in the corner). I don't have any specific examples of these sites, but I come across them every so often. I saw NFS in the firefox add-ons store and thought, "hey, I bet that would stop that annoying thing from happening" and so I got it.

**Comment by bershanskiy** [comment]
> I don't have any specific examples of these sites, but I come across them every so often. I saw NFS in the firefox add-ons store and thought, "hey, I bet that would stop that annoying thing from happening" and so I got it.

I suspect some other extensions and sites might be broken in different ways by NFS. We can create a version of NFS which runs only on specific sites (user-configurable) and then you could use that (once you see a specific problematic site, you add it to custom NFS within a few seconds). Eventually, you'll have the efficiency benefits of DR getting visibility change events with distraction-free browsing.

**Comment by starcraft66** [comment]
Thanks for the investigative work, I went to check my extension list and saw:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/1858154/194759039-af0a243f-0ec1-4544-a295-ceb39c35ef74.png">

I have the page visibility API disabled to prevent spying and annoyances like mentioned in this thread, also to let youtube keep playing in my mobile browser when I close it.

Just enabled the proposed fix by @Gusted and it works like a charm! Thanks so much.

**Comment by Luke-L** [comment]
> @Luke-L I'm sorry to hear that, which email address have you tried mailing? I didn't receive any mail if you have tried mailing me.

the gmail one that i think was listed on the contact page of the site. What email should i forward it to?

**Comment by bershanskiy** [comment]
Summary of the thread:

1. These issues are caused by extensions blocking parts of Page Lifecycle API
2. If you are experiencing this issue on Dark Reader 4.9.58, please [enable a temporary workaround by following these steps](https://github.com/darkreader/darkreader/issues/10004#issuecomment-1272512756)
3. Dark Reader 4.9.59 will most likely ship with a workaround which will work by default and will not have any performance implications when those other extensions are disabled #10047 
4. In the unlikely case that you see any performance regressions from the manual workaround, please limit extensions blocking parts of Page Lifecycle API:
   - on Chrome (Chromium-based browsers) go to `chrome://extensions/`, open that extension's "Details", find "Site access" section and change to "On Specific sites" and add the sites where you need to block Page Lifecycle API.
   - on Firefox, try installing a different extension which explicitly supports site lists

**Comment by Gusted** [comment]
> the gmail one that i think was listed on the contact page of the site. What email should i forward it to?

Do you mean darkreaderapp@gmail.com? I don't have access to that mail account. Please check the other comments in this issue, as it might likely list the reason of this issue.

**Comment by bershanskiy** [comment]
I just merged the fix, it will be included in the next Dark Reader release. Thanks to everyone who participated in this discussion!
