### ISSUE TITLE
[Feature Request] Treat "127.0.0.1" the same as "localhost"

### ISSUE THREAD

**Issue by nsde** [darkreader/darkreader#10077]
# Feature Request

## Is this feature request related to a problem?

When working locally on a server, I often noticed that my settings are not applied for localhost:1234 if I changed them in 127.0.0.1:1234 etc.

## Screenshots

Dark Reader closes when I'm trying to make a screenshot :(

## Additional Context
\-

**Comment by bershanskiy** [comment]
It is already possible to specify that fixes should apply to both forms of `localhost` by listing them explicitly:
```
===================

127.0.0.1
localhost

<your fixes>

===================
```

On the one hand, I do not object to treating `localhost` identical to `127.0.0.1`, since lots of programs do this already. On the other hand, browsers are a bit weird in the way they specify IPv6 addresses so IPv6 localhost `::1` becomes `[::1]`. I'm not sure we want to support only one alternative format (`localhost` being the same as `127.0.0.1`) while not supporting the other (`::1` or `[::1]`). However, implicitly equating all three could be confusing by itself. I'll wait for feedback from @Gusted or @alexanderby on this.

**Comment by nsde** [comment]
ok!
