### ISSUE TITLE
[Bug] "Flashing" issue on intial page load in version 4.9.59 and .60

### ISSUE THREAD

**Issue by fragande** [darkreader/darkreader#10221]
# Bug Report

## Website Address

Any with a light background.

## Bug Description

Since version 4.9.59 there is a clear delay before the Dark Reader settings takes effect when loading new tabs. This means that backgrounds can be, for example, temporarily white causing very eye-straining "flashing". Latest version in which this doesn't occur is 4.9.58.

## Steps To Reproduce

Open any light background site in a new background tab with version >=4.9.59 installed. Focus tab and observe "flashing" before Dark Reader settings apply.

## Expected Behavior

For settings to apply like in version 4.9.58 and earlier where there is no "flashing" issue.

## Actual Behavior

Delay that causes "flashing".

## System Information

- OS: Windows 10 21H1
- Browser: Firefox 106.0.3
- Dark Reader Version: 4.9.60

**Comment by azat11** [comment]
I started having this issure recently too, idk if it started happening after an update. I'm on Waterfox G3.2.3. DR 4.9.60

**Comment by fragande** [comment]
> I started having this issure recently too, idk if it started happening after an update. I'm on Waterfox G3.2.3. DR 4.9.60
> 
> When opening new tab in the background, and later switching to it, a white flash occurs. Probably from the background color of the site itself.
> 
> Rolled back to 4.9.58 and this stopped happening.

This is my observation as well. I have gone back and forth between versions and it's clear that this issue started with version 4.9.59.

**Comment by azat11** [comment]
> This is my observation as well. I have gone back and forth between versions and it's clear that this issue started with version 4.9.59.

This issue here helped me find out the cause, so thanks.

**Comment by MahdiNazemi** [comment]
I have started experiencing the same issue in the past few days.

- OS: macOS 13.0
- Browser: Firefox 106.0.4
- Dark Reader Version: 4.9.60

**Comment by bershanskiy** [comment]
@fragande @azat11 @MahdiNazemi I can reproduce this bug on Firefox 106.0.4 and Dark Reader 4.9.60. Here is a temporary workaround:
 - enable new design: open popup and click on "Dev tools" in the bottom right corner -> popup will open -> click on "Preview new design"
 - open popup again, and click on "See all options" -> click on "Font & more" -> set "Immediate modify" to "Yes"

Explanation: for efficiency reasons, by default, Dark Reader activates itself only when the page becomes visible. Unfortunately, this may result in a slight delay. This options makes Dark Reader disregard page visibility information and eagerly turn it dark. I will try to fix this issue properly in the mean time, but I can provide no ETA since I'm working full-time for another company right now.

**Comment by bershanskiy** [comment]
This appears to be Firefox-specific issue.

**Comment by bershanskiy** [comment]
The fix for this regression will be included in Dark Reader 4.9.61. In the mean time, please use [the workaround above](https://github.com/darkreader/darkreader/issues/10221#issuecomment-1304561713).

**Comment by MahdiNazemi** [comment]
@bershanskiy, thank you for quickly fixing this bug.
Do you suggest keeping the "Immediately modify" option turned on even after the new version is released, or may it break some websites?

**Comment by bershanskiy** [comment]
> Do you suggest keeping the "Immediately modify" option turned on even after the new version is released, or may it break some websites?

There are two things to consider:
 - from my testing of DR after the patch, I did not find any flashes of white content, so I see no reason to keep "immediate modify" option ON.
 - however, "immediate modify" is just one efficiency optimization among many others (it just avoids work when the page is not visible and delays it until page becomes visible). These efficiency issues are rather tricky to trigger, since we have other optimizations in place and browsers throttle JS in some cases as well. If you do not experience any efficiency issues, there is no specific reason to keep "immediate modify" OFF either.

So my advice:
- If you do see white flashes or dislike that some pages in some situations momentarily have dark fallback style applied to them before getting the real style, then make sure to set "immediate modify" to ON.
- In the unlikely case you do see some efficiency issues from "immediate modify" option, then obviously you should disable it. Also, I would be glad for a report about such performance issues so I might he able to fix them.

**Comment by Littleweisheit** [comment]
Now the problem is back, unless I open the link with the middle button
