### ISSUE TITLE
[Broken Website] Dark Reader darkness varying in different browsers.

### ISSUE THREAD

**Issue by roydhritiman** [darkreader/darkreader#10291]
# Broken Website Report

## Website Address

https://twitter.com/home

## Steps To Reproduce

- Go to https://twitter.com/home on **Google Chrome** & **Microsoft Edge.**
- Enable light mode in the native Twitter settings.
- Turn Dark Reader on with the darkness settings shown in the screenshots below.

## Problematic Observation

I want Twitter to have the **same intensity of darkness (via Dark Reader) across browsers.** The exact way I want it is how it looks in Edge. Is there a way to fix this inconsistency, despite the settings being identical in both browsers?

## Screenshots

![dCx9tUk](https://user-images.githubusercontent.com/38285763/201474131-d0cfb51f-3cf6-4d66-9069-edda9911c37c.png)
![WW9jj0P](https://user-images.githubusercontent.com/38285763/201474140-e762982b-3cbe-4a02-835c-2c61cb11ed29.png)
Chrome:![qdvcrpB](https://user-images.githubusercontent.com/38285763/201474147-5779a8e4-07b0-4681-8c4d-e0210846e93d.png)
Edge: ![1BUq9Fi](https://user-images.githubusercontent.com/38285763/201474168-a01b4553-eb5a-4ffb-844c-a54aa9f13608.png)

## System Information

- OS:  Windows
- Browser:  **Chrome 107.0.5304.107 (Official Build) (64-bit)** & **Edge Version 107.0.1418.42 (Official build) (64-bit)**
- Dark Reader Version:  4.9.60

**Comment by bershanskiy** [comment]
> Is there a way to fix this inconsistency, despite the settings being identical in both browsers?

It appears that you have slightly different settings on two installs. To fix this, I recommend exporting settings from Edge and importing them into Chrome. To do this: on Edge open popup -> Click "Settings" -> Click "Manage settings" -> Click "Export Settings". This will produce a file (in JSON format), just do the same thing on Chrome but click "Import settings" instead of export, then select the previously exported file.

Does this fix the issue?

**Comment by roydhritiman** [comment]
Omg yes, this fixed it. Thanks a lot!
