### ISSUE TITLE
[Bug] Text disappear after changing settings

### ISSUE THREAD

**Issue by Pdzoc** [darkreader/darkreader#10367]
# Bug Report

## Website Address
Articles from https://in.indeed.com like
https://in.indeed.com/career-advice/resumes-cover-letters/basic-computer-skills
https://in.indeed.com/career-advice/resumes-cover-letters/best-resume-skills

## Bug Description
After changing values for contrast or sepia text "disappear" - looks like black div on almost whole page. Toggle light/dark mode doesn't cause any problem.

## Steps To Reproduce
- Change value for contrast/sepia etc.

## Expected Behavior
Text in sepia or higher contrast.

## Actual Behavior
Black rectangle cover the page.

## Screenshots
![indeed1](https://user-images.githubusercontent.com/71113600/203730521-618bec3a-37c6-4306-95a3-dd35baa0e80a.png)

After changing values:

![indeed2](https://user-images.githubusercontent.com/71113600/203730594-33fe1273-2e40-4b6f-8d4c-85b8dec32a2e.png)

## System Information

- OS: Windows 10
- Browser: Firefox 107
- Dark Reader Version: 4.9.60

**Comment by Gusted** [comment]
Well, this took unfortunately bit more time to dig into. But apparently Dark Reader was "crashing", as we were telling the browser to parse invalid CSS code... as it was valid CSS code for SVGs. Well that still could happen(as to fix that, the code needs a refactor to take that into account rather than a ugly hack now). So for now I've excluded another related case that prevents this specific invalid CSS rule from being touched by dark reader.
