### ISSUE TITLE
[Feature Request] Gmail loading icon change

### ISSUE THREAD

**Issue by CharaViolet** [darkreader/darkreader#10374]
# Feature Request
The Gmail logo in the quick little loading screen when Dark Reader is on is one of the ugliest things I've ever seen. I would like it to not be one of the ugliest things I've ever seen. So my request is to change the colors back to what they normally are, or just change them to something that isn't incredibly ugly.

## Is this feature request related to a problem?

It is related to the problem of it being very very ugly. The solution would be to make it not be ugly.

## Screenshots

Here's what the logo looks like with Dark Reader:
![image](https://user-images.githubusercontent.com/28274295/203922139-268b2eac-6c10-46b8-9ffa-4f2c7680d618.png)
Here's what it looks like normally:
![image](https://user-images.githubusercontent.com/28274295/203922221-b4517a6a-c01f-4c58-9d07-a3824d3d14de.png)

## Additional Context

It's so ugly I just cannot understate how ugly it is to me :(

**Comment by Gusted** [comment]
Hi @CharaViolet,

Please use the bug issue template next time, as well you only have to mention it once that it's "ugly" -- it doesn't add any value to the report.

This is expected behavior, as the colors have to blend in with the dark mode. If that wasn't the case, it would look like:
![image](https://user-images.githubusercontent.com/25481501/204131486-3f828bce-3a8c-47f4-ad4c-83d37492f55b.png)

Which is objectively uglier to me.
