### ISSUE TITLE
proxyDocumentStyleSheets doesn't check if ownerNode != null before accessing ownerNode.classList

### ISSUE THREAD

**Issue by TomasRiker** [darkreader/darkreader#10427]
### Bug Description

The function `proxyDocumentStyleSheets` tries to access every stylesheet's `ownerNode.classList` without checking if `ownerNode != null`.

I've been observing JavaScript errors caused by this missing check from Dark Reader users visiting my websites:

`Uncaught TypeError: Cannot read properties of null (reading 'classList')`

This is the line of code where the check is missing:

https://github.com/darkreader/darkreader/blob/2e57b83370c22a22a90b76d97e596bcda6070403/src/inject/dynamic-theme/stylesheet-proxy.ts#L102

At all other places, the code already performs the required check.

Here is a pull request to fix it:
#10426

**Comment by bershanskiy** [comment]
This `null` reference is a valid issue, which was supposed to be caught by #10399 but was not because we narrow type and exclude `null` accidentally. If we remove type conversion we get an error:

![image](https://user-images.githubusercontent.com/45960703/205457895-e00680e1-d69c-4c7e-9c06-0200fe66f414.png)
