### ISSUE TITLE
[Broken Website] Liquipedia

### ISSUE THREAD

**Issue by robbai** [darkreader/darkreader#10444]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Internal changes at Liquipedia have affected how Darkreader interpets the colours. One example of this happening is on a teams "Recent Matches" page at Liquipedia Rocket League.

Example: <https://liquipedia.net/rocketleague/Karmine_Corp/Played_Matches>

This is the relevant change at Liquipedia: <https://liquipedia.net/commons/index.php?title=MediaWiki:Common.css/Miscellaneous.css&curid=2760&diff=464738&oldid=461127>

### Website Address

https://liquipedia.net/rocketleague/Version1/Played_Matches

### Steps To Reproduce

1. Go to any teams recent match page on Liquipedia Rocket League
2. More examples:

- <https://liquipedia.net/rocketleague/Gen.G_Mobil1_Racing/Played_Matches>
- <https://liquipedia.net/rocketleague/FaZe_Clan/Played_Matches>
- <https://liquipedia.net/rocketleague/Team_Liquid/Played_Matches>

### Screenshots

![Screenshot](https://cdn.discordapp.com/attachments/372075546231832576/1049766484475379752/image.png)

### Operating System

Windows 10

### Web Browser name and version

Microsoft Edge - 107.0.1418.62

### Dark Reader version

4.9.60

### Additional Context

This is how the issue was explained to me when I reported it at Liquipedia:

> it seems that darkreader has some kind of bug where it does not override the colors set for the rows. The second <style> is defined by darkreader (as is the first one) however it does not seem to be modifying the style correctly. So, this is definitely a darkreader bug.
![Report](https://cdn.discordapp.com/attachments/960883616769007676/1049813375502266398/image.png)

**Comment by Gusted** [comment]
We could fix this at Dark Reader(which is trivial), but if it's possible I prefer to "fix" this at liquipedia.net.

The reason Dark Reader does not change correctly is that the browser does not tell Dark Reader that there is a variable in the value(it simply returns empty) at `background` because the browser does not know the type of variable.

It looks like you didn't link the bug report, but if they change the `background` property to `background-color`, the browser would tell Dark Reader that there is a variable in the value and Dark Reader can then modify it correctly.

**Comment by robbai** [comment]
Thank you! Closing now
