### ISSUE TITLE
Some garbled images in Dynamic theme

### ISSUE THREAD

**Issue by thany** [darkreader/darkreader#1063]
This is happening at https://tweakers.net/, a popular technology site in The Netherlands and Belgium.
In the header the account kind of icons become garbled. In the news overview, some items get a weird background behind the text. There are possibly other issues, but I suspect they share the same root cause. These issues appear to do with icons only, not pictures within article content.

Example before:
![before](https://user-images.githubusercontent.com/152227/51981308-fa057e80-2492-11e9-8cb7-65d628f37c76.PNG)
After:
![after](https://user-images.githubusercontent.com/152227/51981310-fc67d880-2492-11e9-8b1e-7df7c0f67c28.PNG)

Current workaround is to use the Filter+ theme.

I'm using Firefox 65 & the latest Dark Reader addon from the Mozilla repo.

**Comment by memeplex** [comment]
Here is another example, for google docs equation toolbar:

![image](https://user-images.githubusercontent.com/2845433/57585253-e61edf00-74bb-11e9-9731-bdc6cf16ccba.png)

With Filter or Filter+ modes this doesn't happen.

**Comment by Yoshi2889** [comment]
On Tweakers, this seems to be the case because Dark Reader applies the wrong image set.

![image](https://user-images.githubusercontent.com/1280380/75809621-fa043c00-5d80-11ea-8631-5810fcf925fd.png)

Disabling the top one, so the responsive one, fixes the issue for me. The logo is even worse, as it picks a totally unrelated image:

![image](https://user-images.githubusercontent.com/1280380/75809726-228c3600-5d81-11ea-914d-8ec2dbf8e73e.png)

**Comment by Gusted** [comment]
Hi Medetweakers ;)

It has been fixed in the latest version of darkreader!

Regards,
Gusted
