### ISSUE TITLE
Nothing but background color shows with darkreader open

### ISSUE THREAD

**Issue by jasonxia23** [darkreader/darkreader#1103]
```html
<style class="darkreader darkreader--fallback" media="screen">
  html, body, body * {
      background-color: #eae7e1 !important;
      border-color: #36383d !important;
      color: #000000 !important;
  }
</style>
```
After comment `background-color: #eae7e1 !important;` element shows.

**Comment by alexanderby** [comment]
This fallback style prevents white flashes and should be removed when page finishes loading. Does it happen on some specific website?

**Comment by gladiator001** [comment]
The issue is reproducible in many websites (including https://github.com). In my case, the fallback DIV is not always removed.
As a side effect, the color of links and texts are overwritten to `color: #000000 !important`.

The issue seems to be caused by a raise condition around the `loadingStyleId`, `loadingStylesCounter` variables.

In my case, I could work around the issue entirely by commenting out all the following `loadingStyles.size === 0 ` statements, so that the `cleanFallbackStyle()` function is always called.

https://github.com/darkreader/darkreader/blob/f9afdc08136388b2fa45dc0ebc994168899d3acb/src/inject/dynamic-theme/index.ts#L242-L250

I am using a MacBook Pro (macOS Catalina) and Google Chrome.

**Comment by Gusted** [comment]
Resolved.
