### ISSUE TITLE
syntax colors in jupyter notebook

### ISSUE THREAD

**Issue by sanyam5** [darkreader/darkreader#1106]
syntax colors in jupyter notebook disappear on refreshing page:
![screenshot from 2019-02-14 14-57-03](https://user-images.githubusercontent.com/2987069/52813976-02e87980-3069-11e9-91b5-5ac5506d24ba.png)

To bring back the colors, I:
1. Turn off the extension
2. refresh the page with the extension off.
3. then turn on the extension. (but don't refresh the page again)
(all three steps are needed, skipping step 2 doesn't do the trick).

![screenshot from 2019-02-14 14-56-30](https://user-images.githubusercontent.com/2987069/52814076-3d521680-3069-11e9-90f3-97a4eff1671f.png)

But this is temporary since the colors disappear again after refreshing.

**Comment by ali-abz** [comment]
I have problem with jupyter too. Normally, jupyter looks like this:
![light](https://user-images.githubusercontent.com/23415604/54743666-0926c400-4bda-11e9-81dd-0ce0f778a3d6.png)
but with darkreader, there is absolutely nothing too see:
![dark](https://user-images.githubusercontent.com/23415604/54743702-1fcd1b00-4bda-11e9-9e79-9b408c43d987.png)
there is no problem with other local pages.
Firefox 65, Ipython3.6, Notebook 5.4.1, Xubuntu 18.10

**Comment by ali-abz** [comment]
By the way, this problem only occurs when im using a '.ipynb' files.
![dark2](https://user-images.githubusercontent.com/23415604/54744303-e1d0f680-4bdb-11e9-86f2-ef03460db0e0.png)

**Comment by devanshuDesai** [comment]
Any updates/fixes on this?

**Comment by Japkeerat** [comment]
This issue also comes up with websites using Jupyter notebook. Like Kaggle and Udacity.

**Comment by yoflippo** [comment]
Another Jupyter bug, when the plugin is operating the cell shrinks:
![image](https://user-images.githubusercontent.com/13065538/64333414-bcdc0e80-cfd6-11e9-8b1f-a1a9635e4fed.png)
Turned off it looks like this:
![2019-09-05 12_16_18-intro-python - Jupyter Notebook](https://user-images.githubusercontent.com/13065538/64333537-075d8b00-cfd7-11e9-9f16-7185a8913abb.png)

**Comment by rvillalba-novetta** [comment]
For local notebooks it seems to temporarily fix itself if you
disable dark reader, refresh the page, enable dark reader

**Comment by PyroGenesis** [comment]
This issue has been happening to me for a quite a while as well so I narrowed down the CSS section that causes it.

### When darkreader is enabled AFTER reload (syntax highlighting works correctly)
![image](https://user-images.githubusercontent.com/17806916/104233898-7e930280-5407-11eb-9cf5-c2d0640ff77c.png)

### When darkreader is enabled BEFORE reload (syntax highlighting doesn't work)
![image](https://user-images.githubusercontent.com/17806916/104233596-fdd40680-5406-11eb-901f-3198f3c00ef2.png)

The style element which causes it is this one:
```
<style class="darkreader darkreader--fallback" media="screen"></style>
```
When the syntax highlighting works correctly, the above style tag is empty.
When the syntax highlighting doesn't work, the style tag contains the CSS you see in the 2nd image.

Is this something like a race condition between Juyter syntax highlighting vs darkreader styles?
Also, is there any way to prevent darkreader from applying this style to the relevant classes (maybe using Dev Tools)?

**Comment by Gusted** [comment]
Fallback should be removed, this indicates for an error.
As it's a fallback and just for specific purposes you can't edit it with the Dev Tools.

Race conditions? No not all.

**Comment by atzemis13** [comment]
Has anyone come up with a better fix for this?

**Comment by jpuris** [comment]
There is a workaround to this

1. Open DR settings (when activating it via extension button)
2. In `Filter tab`, at the bottom make sure `Only for ...` is turned on
3. In `More tab`, make sure `Filter` or `Filter+` is chosen. Whichever look you prefer

Additional settings (my preference, makes it easier on the eyes)
- More -> Filter
- Filter -> Brightness off
- Filter -> Contrast -15 (to lower the contrast as 0 value is way too strong)
- Filter -> Sepia +10 (to remove some strong blue tones)

Drawbacks:
- This is per `<domain>:<port>` as instructions may suggest

_Tested on Brave browser Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (x86_64)_

**Comment by devanshuDesai** [comment]
I think the extension just doesn't play well with syntax highlighting in general. I always have issues viewing `python` and `conda` docs with the extension enabled.

**Comment by mathsmathsmaths** [comment]
With fallback element CSS deleted:
![Screen Shot 2021-03-25 at 10 29 14](https://user-images.githubusercontent.com/40340216/112499201-3f612600-8d55-11eb-850a-5f79a1290117.png)
After reloading (or adding the CSS back)
![Screen Shot 2021-03-25 at 10 30 12](https://user-images.githubusercontent.com/40340216/112499328-5bfd5e00-8d55-11eb-8751-1ffa1a52a8e8.png)

(Look for the triple hashtags in both images)

So yes, it looks like DR is adding CSS to the fallback element (only under `<head>` in the Jupyter notebook though...)

It looks like [this file](https://github.com/darkreader/darkreader/blob/master/src/inject/fallback.ts) is the culprit. The CSS in the file directly matches the CSS in the fallback element.

**Comment by mathsmathsmaths** [comment]
Actually, it might not be `getModifiedFallbackStyle`. My "fix" totally destroyed the white flash fix and I would like to preserve intended purpose so hear's what I've found.

From [this file](https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/index.ts): 
```
function cleanFallbackStyle() {
    const fallback = document.querySelector('.darkreader--fallback');
    if (fallback) {
        fallback.textContent = '';
    }
}
```
For me, the jupyter notebook is loaded through an iframe using src. So, it would make sense that the above would not capture the fallback style in the iframe's `<head>`. It seems like it only erases the CSS in the 'upper' `<head>`.

Inside the upper head:
![Screen Shot 2021-03-26 at 10 37 40](https://user-images.githubusercontent.com/40340216/112656412-62580c80-8e1f-11eb-9da8-a18fa9f25b26.png)

The iframe's head:
![Screen Shot 2021-03-26 at 10 37 10](https://user-images.githubusercontent.com/40340216/112656494-7734a000-8e1f-11eb-89ea-68beac0899d8.png)

`cleanFallbackStyle()` is completely ignoring the `darkreader.darkreader--fallback` style element in the `<head>` under the iframe.

**Comment by Gusted** [comment]
Hi @mathsmathsmaths 

So just before thinking what's going on. Let me explain the purpose of the fallback element.

Simply said, it's to reduce overhead from the white-flash within chromium's browsers(with edge-cases in firefox) and provide an minimal dark UI while we the site is loading and Dark Reader is analyzing the styles. When all styles are analyzed we remove the fallback element. Their are cases(which I think this is 1 of them) whereby 1 or more styles aren't getting loading for some reason. #4886 fixes this. Another shot to give is #3921 that also uses a new system to use the fallback styles(trough constructed Stylesheets). Thereby the Iframe and top window have separated content scripts and don't know that each other exist and purely do their own thing.

Regards,
Gusted

**Comment by mathsmathsmaths** [comment]
@Gusted so you're saying that the iframe's styles never finished analyzing, preventing fallback from being cleaned? (Even though that should be fixed in #4886?)

**Comment by Gusted** [comment]
> so you're saying that the iframe's styles never finished analyzing, preventing fallback from being cleaned?

It's an likely scenario. Whereby if this scenario is present #4886 is definitely an solution.

**Comment by mathsmathsmaths** [comment]
Made the changes in #4886 and builded. Works perfectly

**Comment by sjoerdloenen** [comment]
Hi guys, I have the same issue. Glad to see that it works for you! 
Disclaimer: I am quite new to all this. 
I see #4886 refers to the file: src/inject/dynamic-theme/style-manager.ts. I was wondering how I can access that file on my own computer. I have downloaded the Dark Reader extension from the Chrome extension web store over a year ago or so. Help is appreciated:). Thanks in advance

**Comment by Gusted** [comment]
I don't recommend at all to access that file as Chrome/Firefox works with data integrity and if you change such file, the extension won't work anymore. If you want to have that change you should build the branch on your own. Which for someone that doesn't know GIT/not comfortable around the command line is pretty hard.

**Comment by AndrewDaGuy** [comment]
As Gusted said its pretty hard to if the command line gives you the heebie jeebies, so I'm here to give you very noob friendly instructions (if you want to build by yourself) and the extension files :D

<details>
<summary>Building by yourself guide</summary>

_This very noob friendly guide is assuming you're using Windows 10 and Chrome_

1. Get Nodejs LTS here -> https://nodejs.org/en/
2. Go though the installation process
![image](https://user-images.githubusercontent.com/66189242/120066820-c9847e00-c067-11eb-8405-7e6e794c8b08.png)
2a. Next, click `Node.js command prompt`, then once its finished you can close the window.
![image](https://user-images.githubusercontent.com/66189242/120066935-77902800-c068-11eb-9391-3fab05eb4ca1.png)

3. Open https://github.com/darkreader/darkreader/tree/timeoutLoading-Patch in your browser
4. Click this green button
![image](https://user-images.githubusercontent.com/66189242/120066244-419d7480-c065-11eb-8cf8-337b41a047e1.png)
5. Download the `.zip` into your __Downloads folder__ (it'll make it easier to follow the tutorial :o)
![image](https://user-images.githubusercontent.com/66189242/120066254-50842700-c065-11eb-90b4-38735838c445.png)
6. Unzip/extract the file (You should get a folder)
![image](https://user-images.githubusercontent.com/66189242/120066510-54fd0f80-c066-11eb-92d7-5952e436f5b6.png)
7. Now open the command prompt _(Ignore the username :c)_
![image](https://user-images.githubusercontent.com/66189242/120066567-b0c79880-c066-11eb-983c-d7754d427b93.png)
![image](https://user-images.githubusercontent.com/66189242/120066605-c89f1c80-c066-11eb-9ad8-a83ed4299bd5.png) 
8. Type `cd Downloads`, this will change your directory to `C:\Users\{username}\Downloads`
![image](https://user-images.githubusercontent.com/66189242/120066726-4c590900-c067-11eb-9eb9-6d3573d3de96.png)
9. Now do `cd darkreader-timeoutLoading-Patch/darkreader-timeoutLoading-Patch` (Now this time you're in the folder you extracted in step 6)
![image](https://user-images.githubusercontent.com/66189242/120066753-78748a00-c067-11eb-9e92-7a8eb29231cd.png)
10. Now run `npm install`, this will take awhile (From here on out I'll be not be using screenshots from windows 10 because VMs are slow af)
![image](https://user-images.githubusercontent.com/66189242/120067586-08b4ce00-c06c-11eb-93f4-a5a59ddc69eb.png)
11. Run `npm run build`, this will build the extensions to use with chrome or firefox :D
![image](https://user-images.githubusercontent.com/66189242/120067657-46195b80-c06c-11eb-808e-c7e88ceeb982.png)
12. Now install the extension to chrome (Stolen from https://howchoo.com/internet/how-to-install-a-chrome-extension-manually)

12b. Go to `chrome://extensions/` and click "Load unpacked" and select the build folder (blue is a folder ;) )
![image](https://user-images.githubusercontent.com/66189242/120068107-8f6aaa80-c06e-11eb-8569-628beba9904e.png)

</details>


[build-firefox.xpi.zip](https://github.com/darkreader/darkreader/files/6564567/build-firefox.xpi.zip)
[build.zip](https://github.com/darkreader/darkreader/files/6564570/build.zip)

Chrome:  Go to `chrome://extensions/` and click "Load unpacked" and select the unziped `build.zip` folder

Firefox: Go to `about:addons` and click this
![image](https://user-images.githubusercontent.com/66189242/120068356-cd1c0300-c06f-11eb-82f4-625c162c871b.png)
then select the unziped `build-firefox.xpi.zip` file

**Comment by Gusted** [comment]
> As Gusted said its pretty hard to if the command line gives you the heebie jeebies, so I'm here to give you very noob friendly instructions (if you want to build by yourself) and the extension files :D

Maybe time to update the Contributions.MD with these instructions or adding them to a separate /wiki page.

**Comment by AndrewDaGuy** [comment]
> Maybe time to update the Contributions.MD with these instructions or adding them to a separate /wiki page.

Maybe a `BUILDING.md`?

**Comment by Gusted** [comment]
> Maybe a `BUILDING.md`?

:D do the honors and draft up a PR.

**Comment by AndrewDaGuy** [comment]
> :D do the honors and draft up a PR.

#5905

**Comment by Osherz5** [comment]
This issue has been going on for a while, why was #4886 closed if it solves it?

**Comment by PyroGenesis** [comment]
Personally I ended up switching to Jupyter Lab which already has a built-in dark mode.

**Comment by alexanderby** [comment]
Works fine for me https://jupyter.org/try-jupyter/notebooks/?path=notebooks/Intro.ipynb

**Comment by alexanderby** [comment]
Could you please share a link?

**Comment by oilskin-dataset** [comment]
Answer located successfully https://lnkr.fun/e7c70f9
