### ISSUE TITLE
Web site meta data to disable dark by default

### ISSUE THREAD

**Issue by sandrock** [darkreader/darkreader#1114]
I am working on a website that uses a lot of background pictures and visuals. The dark mode does not work well and there is no way such website can be displayed in dark. 

This creates a issue: the user sees a wrongly displayed website (half-dark half-not). 

I would like a way to announce to dark reader (and to all similar extensions) that it should not use dark mode by default. 

Maybe using a meta element?

    <meta name="X-DarkMode-Default" value="false" />

Note: it seems better to play with a default value rather than to play on a "disable always" way. This would allow the user to try dark mode, and see that it does not work. 

PS: I don't like the idea of dark-list of websites because you cannot list all the problematic websites of the world. It seems better for webmasters to declare it on their side.

**Comment by oxguy3** [comment]
I definitely would not want to give web developers the power to turn off dark mode, as it would almost likely be abused. If I think a website is unusable with dark mode turned on, then I may make the decision to disable dark mode, but I don't want web developers to make that decision for me. Perhaps your website doesn't look good in dark mode, but depending on how bad it is and how much I'm going to use your website, I am pretty likely to decide to keep the janky dark mode on instead of viewing a light website.

Frankly, this extension causes a few issues on _most_ websites. Anyone using this extensions will likely be used to dealing with it and not think anything of it if your site looks a bit broken.

**Comment by sandrock** [comment]
I understand the spirit of this extension and I like it very well.

You don't want to give web developers a way to forbid dark mode and it's perfectly understandable.

However, I expressed my suggestion  in a specific way, considering the spirit of the extension. I suggest web developers to be able to give a *default value* for dark mode. Not a *forbid dark mode* option.

The website I'm responsible for is "intermediate dark" with a lot of background pictures. Dark mode does not change many things. The few changes  alter text color and makes it unreadable.

Would you consider debating that a bit? Not many web developers know about this extension. I doubt one day most website will set the preference to counter dark mode. Even if this happens, you could make a list of website abusing the preference...

Your thoughts ?
________________________________
De : Hayden Schiff<mailto:notifications@github.com>
Envoyé : ‎01/‎03/‎2019 21:25
À : darkreader/darkreader<mailto:darkreader@noreply.github.com>
Cc : SandRock<mailto:antoine.sottiau@outlook.com>; Author<mailto:author@noreply.github.com>
Objet : Re: [darkreader/darkreader] Web site meta data to disable dark by default (#1114)


I definitely would not want to give web developers the power to turn off dark mode, as it would almost likely be abused. If I think a website is unusable with dark mode turned on, then I may make the decision to disable dark mode, but I don't want web developers to make that decision for me. Perhaps your website doesn't look good in dark mode, but depending on how bad it is and how much I'm going to use your website, I am pretty likely to decide to keep the janky dark mode on instead of viewing a light website.

Frankly, this extension causes a few issues on most websites. Anyone using this extensions will likely be used to dealing with it and not think anything of it if your site looks a bit broken.

**Comment by spikespaz** [comment]
How about a list of exclusions that this repository maintains in lieu of a meta tag? Using this method, any website whose author wishes it to remain unchanged by default can *request* such, instead of setting a tag.

Dark Reader and the maintainers (and then ultimately the end-user) would make the final decision.

This feature, turning off Dark Reader for specific sites *by default*, **is almost necessary**, because as @sandrock stated that for some sites, including his own and mine:

> Dark mode does not change many things. The few changes  alter text color and makes it unreadable.

Dark Reader--the majority of the time--does a *very** good job at what it does. However, it's impossible to make it airtight, and the only way to ensure near-complete compatibility is to cooperate with the websites (and authors) themselves. On the other hand, if the author (or large company, as is more likely) attempts to circumvent DR functionality, I would say go ahead and combat it. If the user wants to change the styles of a website, I say that's their right.

Issue #1179 is a duplicate, which I saw and commented first.

**Comment by spikespaz** [comment]
Additionally, I've had another idea. 

Each website entry in the exclusion list would have an optional corresponding JS snippet to toggle dark mode. That would be dynamically loaded and run by DR for each site in the exclusion list.

Some sites have the dark theme disabled by default, even though they are very good. For example, [this arbitrary MS Dev Center page](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/).

A simple script that could be evaluated by DR just needs to virtually click a toggle instead of processing the whole page's styles.

```js
document.querySelector("button.theme-control > span.theme-dark").click();
```

One line. That's all it takes to enable dark theme for that site. I'm sure simple solutions can be found for *a ton* of other sites as well.

MS Dev Center should be one of the first on the exclusion list because the Dynamic filter looks like crap with it, and it's only extra overhead if the site is already available dark.

**Comment by rlefevre** [comment]
Maybe it could be abused, but breaking web sites is not that great either: https://github.com/darkreader/darkreader/issues/623

One of mines also breaks in dynamic mode: https://elm-greenwood.com
I guess a lot of react sites have the same issue.

Maybe at least a `meta` tag to disable dynamic mode only would be an acceptable compromise?

**Comment by Jayshua** [comment]
I don't know if this would be possible, but maybe the meta tag could trigger a prompt from darkreader. Something like "This websites reports that it doesn't work well with dark mode. Would you like to enable it anyway?"

**Comment by qguv** [comment]
Right now, each site already designed with a dark theme will have to be added to darkreader's exclude list with a commit to the darkreader repo. Each user will have to wait for an extension update to get these changes.

@sandrock and @rlefevre support allowing website developers themselves to declare if their site is already dark mode using a meta tag. I strongly agree; darkreader doesn't need to do anything to a site that already handles its own dark mode. For example, automatic dark mode makes an absolute mess of the link color of [one of my own projects](https://lsdj.cloud) even though it already shows bright text on a dark background.

But as @oxguy3 points out, a meta tag could potentially be abused by a user-hostile site which wants to prevent darkreader from applying a dark theme. @spikespaz suggests a possible mitigation, but this would require intervention from darkreader maintainers for every site with the special tag. @Jayshua suggests a user prompt, but bothering the user 

But I would argue that this abuse is likely to be rare, and there's still the chance to configure darkreader to ignore the site's already-dark declaration by putting it on a list in darkreader source, similar to how we put sites on a list today. Because I think it would be rare to explicitly deceive darkreader, this would be a lot less work than expecting every site on the web with a dark theme to make a PR to the darkreader repo.

So I would suggest implementing the following:

  - site authors can include a meta tag declaring that the currently-displayed page has a dark theme
  - if users find a site that's abusing this privilege, they can put it on a list to disable recognition of the meta tag

As to the format of the magic tag… there is a [proposal](https://github.com/w3c/csswg-drafts/issues/3299) that has since been [documented in MDN (search in page for `color-scheme`)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) specifying something similar: a meta tag declaring a site's preference for light or dark browser UI elements. If darkreader is to look for a meta tag, I would suggest using this proposed tag instead, because developers who aren't aware of darkreader might still use a standardized meta tag for their site theme.

**Comment by MatthiasGrandl** [comment]
+1. I am developing a self-hosted app with a native dark mode. It being self-hosted, means it's deployed on a ton of different domains. I can't realistically add all of them to the blacklist, so having this meta tag supported would be amazing.

**Comment by Gusted** [comment]
Hi their!

First I didn't read all comments *yet* 😬 Forgive me.
So you suggest when Dark Reader detects `<meta name="A meta name">` It should not darken the site?
We also should think of a good Meta Name that don't potential mess up any other meta's I saw some suggestion of name's and even a w3c-draft in my eyesights. 
I'm happy to discuss with everyone involving further about this behaviour.

Regards,
Gusted

**Comment by Gusted** [comment]
#2855 
We added a meta tag for <meta name="darkreader" instance="UUID here"> and if it's found it wouldn't do anything.

**Comment by NeXTs** [comment]
> We added a meta tag for `<meta name="darkreader" instance="UUID here">` and if it's found it wouldn't do anything.

[There should be "content" instead of "instance", right?](https://github.com/darkreader/darkreader/blob/9287f368f1c3415253f6b9a4d1ace48accc5f172/src/inject/dynamic-theme/index.ts#L402)

`<meta name="darkreader" content="UUID here">`

**Comment by Gusted** [comment]
> [It should be "content" instead of "instance", right?](https://github.com/darkreader/darkreader/blob/9287f368f1c3415253f6b9a4d1ace48accc5f172/src/inject/dynamic-theme/index.ts#L402)
> 
> `<meta name="darkreader" content="UUID here">`

Correct

**Comment by TruncatedDinosour** [comment]
> #2855 We added a meta tag for `<meta name="darkreader" content="UUID here">` and if it's found it wouldn't do anything.

what is "UUID here" supposed to be replaced with? should it be like a random UUID or something? I am confused, sorry

**Comment by Gusted** [comment]
You can replace UUID with any kind of content.
