### ISSUE TITLE
Can you invert the white backgrounds of amazon images so that the website looks truly dark?

### ISSUE THREAD

**Issue by ars4l4n** [darkreader/darkreader#1122]
Right now an amazon page basically looks like this 
![image](https://user-images.githubusercontent.com/47932878/53294234-e5db4580-37e2-11e9-9c1b-cc68d3416179.png) so it's quite harsh for the eyes in the evening. Is there a way to invert those image backgrounds? Maybe by doing the thing you can do on paint with the bucket? I don't know how resource hungry that would be but if it was it would still be a nice feature for people who love darkmode and are willing to get better hardware for it.

Best Regards,

Arslan

**Comment by oxguy3** [comment]
Manually removing a white background from an image is really easy (like you said, just use the paint bucket tool in your favorite image editor), but doing it automatically to any arbitrary image is much more difficult. The software would have to guess where the background is and what parts of the image are/aren't background and how soft the edges should be and so on. Any white objects would likely get obliterated (e.g. [https://amzn.com/B006OEY8N6 this shirt] or [https://amzn.com/B00TTD9BRC this moisturizer]); parts of the white background would awkwardly remain (e.g. the reflection of [https://amzn.com/B00NNS5MNQ this hard drive]); it would probably get confused on images that don't have a background (e.g. [https://amzn.com/B016OLA1B6/ this Blu-ray]; etc etc etc. In the best cases, it would still likely look a little bit odd -- the script would have to be one-size-fits-all and use the same thresholds for every image, but the photos on Amazon have a wide variety of quality and whatnot.

And also as you mentioned, it would likely be pretty time-intensive to process if you want the images to look halfway decent. Ideally you'd want to have the script use the original resolution images instead of the compressed ones Amazon normally serves, but that would be slow both in terms of bandwidth and processing time.

Here's an existing tool that does background removal in the browser, to give you a sense of what's possible: https://www.eraseimage.com. It takes it maybe half a second to process a single image at the relatively low resolution of 640x640, the edges look kind of ugly, and it's only able to do any of that after you manually indicate which parts of the image are foreground/background.

This is definitely possible to do, but it'd be very difficult to do _well_, and is likely outside of the scope of this extension. If you want to make it look better, you could write some custom CSS that adds a border around the images; that way, they'd sorta be framed and might not look so out of place.

**Comment by ars4l4n** [comment]
Hey,

thank you for the detailed explanation. It's a nice thing that you are so aware of this issue.
I guess the only solution for now would be websites like amazon implementing darkmodes themselves in a way that is easier on your hardware. More and more websites are slowly making darkmodes. User hardware performance also increases each year so we will eventually see it. I just hope it happens quickly, I'm waiting for years now.

Regarding the costum borders, I'm an amateur and not the best learner in programming languages so I'll see what I might be able to do at some point but what about you putting the rounded borders as an optional feature into your extension for users that can handle it performance-wise?

Best Regards,

Arslan


________________________________
Von: Hayden Schiff <notifications@github.com>
Gesendet: Freitag, 1. März 2019 21:06
An: darkreader/darkreader
Cc: ars4l4n; Author
Betreff: Re: [darkreader/darkreader] Can you invert the white backgrounds of amazon images so that the website looks truly dark? (#1122)


Manually removing a white background from an image is really easy (like you said, just use the paint bucket tool in your favorite image editor), but doing it automatically to any arbitrary image is much more difficult. The software would have to guess where the background is and what parts of the image are/aren't background and how soft the edges should be and so on. Any white objects would likely get obliterated (e.g. [https://amzn.com/B006OEY8N6 this shirt] or [https://amzn.com/B00TTD9BRC this moisturizer]); parts of the white background would awkwardly remain (e.g. the reflection of [https://amzn.com/B00NNS5MNQ this hard drive]); it would probably get confused on images that don't have a background (e.g. [https://amzn.com/B016OLA1B6/ this Blu-ray]; etc etc etc. In the best cases, it would still likely look a little bit odd -- the script would have to be one-size-fits-all and use the same thresholds for every image, but the photos on Amazon have a wide variety of quality and whatnot.

And also as you mentioned, it would likely be pretty time-intensive to process if you want the images to look halfway decent. Ideally you'd want to have the script use the original resolution images instead of the compressed ones Amazon normally serves, but that would be slow both in terms of bandwidth and processing time.

Here's an existing tool that does background removal in the browser, to give you a sense of what's possible: https://www.eraseimage.com. It takes it maybe half a second to process a single image at the relatively low resolution of 640x640, the edges look kind of ugly, and it's only able to do any of that after you manually indicate which parts of the image are foreground/background.

This is definitely possible to do, but it'd be very difficult to do well, and is likely outside of the scope of this extension. If you want to make it look better, you could write some custom CSS that adds a border around the images; that way, they'd sorta be framed and might not look so out of place.

**Comment by Gusted** [comment]
`no` Was the answer and wont be possible unless you want to have minutes of site loading.
