### ISSUE TITLE
[Feature Request] Dashlane in extensions (chrome-extension://....)

### ISSUE THREAD

**Issue by tahayparker** [darkreader/darkreader#11242]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

Dashlane on the web app (Chrome extension) is "protected" and hence Dashlane does not appear in dark mode.

The URL: chrome-extension://fdjamakpfbbddfjaooikfcpapjohcfmg/index.html#/credentials

### Screenshots

![image](https://user-images.githubusercontent.com/98612931/236983642-a4b1994b-55bc-4885-b611-f5f2460f8ba8.png)

**Comment by bershanskiy** [comment]
This is an intentional browser limitation for security purposes. As a remedy, I can provide you with instructions how to save Dashlane page, then open it in Dark Reader, export Dark Reader's style changes, and then apply these changes to Dashlane and install the resulting extension. These steps would need to be performed each time Dashlane updates.

**Comment by bershanskiy** [comment]
Closing as impossible to implement.

**Comment by tahayparker** [comment]
> As a remedy, I can provide you with instructions how to save Dashlane page, then open it in Dark Reader, export Dark Reader's style changes, and then apply these changes to Dashlane and install the resulting extension

Could you provide the steps please?

**Comment by tahayparker** [comment]
@bershanskiy if you could please
