### ISSUE TITLE
Workaround for new tab

### ISSUE THREAD

**Issue by ghost** [darkreader/darkreader#1138]
Can this extension add a custom new tab page with dark theme?

**Comment by oxguy3** [comment]
Why not just install one of the numerous dark browser themes that are available? https://chrome.google.com/webstore/category/collection/dark_themes

**Comment by humphreygaming** [comment]
@zbot473 i dont think browsers support that kind of stuff (or this dev still does not add this feature)

**Comment by zbot473** [comment]
@humphreygaming
Extensions like Momentum exist

**Comment by zbot473** [comment]
@oxguy3 I only use dark theme in the night though

**Comment by nik312123** [comment]
Dark Reader's purpose is to make webpages basically dark themed. It cannot do this dark formatting on pages provided by the Chrome browser, including the new tab page.

If you set your new tab page to a website like google.com, Dark Reader can easily apply in that case.

If you are asking Dark Reader to make their own dark new tab page, it would be better to just install a dark new tab page as suggested above since adding such a feature would distract from the main intention behind Dark Reader.

Otherwise, I think you're out of luck.

**Comment by Flaburgan** [comment]
It works on Firefox though. The new tab page is dark when using Dark Reader.

**Comment by Gusted** [comment]
No intention to make a theme.
