### ISSUE TITLE
"Static" makes some videos unwatchable

### ISSUE THREAD

**Issue by neetch1** [darkreader/darkreader#1160]
Would love to use dynamic cause it looks great but its wayyy too slow so static must be the next option since it doesnt make everything black and white. But on sites like liveleak and tumblr the video disapears. Any fix for this?

Btw im using firefox

**Comment by okradonkey** [comment]
Same here, Firefox in Static mode also.  I can't seem to get most videos to display on top of the dark background (problem is only in Static; videos display properly in Filter and Dynamic mode).  I tried changing z-index of video elements and various divs in CSS, but can't seem to find the solution. I was able to move video text overlays and video controls to the top, but not the video itself.  Any suggestions?

**Comment by okradonkey** [comment]
I was able to make some progress, but if there's a better way to do this, I'm open to learn it.  As specified in the default filter, Dark Reader was adding `background-color: rgb(16, 20, 23)` to any non-text element that didn't already have a `background-color` defined (including video overlays).  I think the best and only realistic remedy is to add per-site CSS rules to the static filter, since many sites have their own variations of video players whose overlays are also commonly customized.

(There are, however, some common frameworks, like videojs, that might be candidates for inclusion in the default NEUTRAL BG section by expanding the existing selector to be something like `:not([style*="background-color:"]):not([class*="vjs"])`.  I honestly don't have the raw web experience to know if this is the best way to handle it, so instead I am adding per-site sections to my filter for now.)

First, in Dark Reader, with the Static filter enabled, click Dev Tools to bring up the Static Theme Editor.  Then, we add a new section and specify the site, then the line "TRANSPARENT BG", followed by CSS selectors for those elements that need to retain a transparent background.

For example, most of the videos on Tumblr appear correctly after adding the following lines to the static theme editor:

```
================================

tumblr.com

TRANSPARENT BG
div[class*="vjs"]
div[class*="video"]
div[class*="post_content"]
```


Washington Post was a little more complicated, but this seems to handle most of their video layouts:

```
================================

washingtonpost.com

TRANSPARENT BG
.powa-pane
.powa-custom-ctrls
.powa-overlay
div[class*="powa-ctrls"]
div[class*="ctrls-overlay"]
```

I hope this helps somebody!
