### ISSUE TITLE
google docs document is inverted

### ISSUE THREAD

**Issue by noyza2132** [darkreader/darkreader#1162]

**Comment by PsiPhiTheta** [comment]
Please provide more information on your issue. Which part of the document is inverted that you do not wish to be inverted?

**Comment by lukoma666** [comment]
I can't speak for the OP but I have to keep it disabled for Google Sheets as it defaults my text color to gray instead of black for example. I have to constantly reset the text color to fix this. If the page is reloaded, it goes back to defaulting to gray. The gray is very difficult to read on black or white background.

Different site, but I also had issues with outlook web (outlook.office.com/owa) adding black highlighting with gray text. This one was very strange as the first paragraph was fine but the second paragraph was very difficult for the recipients to read. Now I am paranoid and always disable it before sending mail so I can see what other people are actually going to see.

**Comment by AndroidDeveloperLB** [comment]
Duplicate:
https://github.com/darkreader/darkreader/issues/490
?

**Comment by Gusted** [comment]
Dup is closed.
