### ISSUE TITLE
Pushbullet.com Website Blank on Firefox

### ISSUE THREAD

**Issue by TheAlienDrew** [darkreader/darkreader#1170]
Using Dark Reader, on chrome PushBullet's website works just fine, however, viewing the same site on FireFox gives a blank screen.

**Comment by thakyZ** [comment]
I can confirm this. It only seems to happen when the page is loaded when the filter is enabled for pushbullet.com, but if it's enabled after pushbullet.com fully loads, it works fine. I wonder if this is because pushbullet dynamically loads the page, and possibly the extension is interrupting it.

**Comment by yasiupl** [comment]
I have the same problem without darkreader addon installed.

**Comment by thakyZ** [comment]
That doesn't seem to fix the issue.

**Comment by Gusted** [comment]
Fixed. tested with normal settings.

**Comment by bossanovaorca** [comment]
I am seeing this once more on pushbullet.com in Firefox 85

**Comment by Gusted** [comment]
reproduce-able again.

**Comment by Gusted** [comment]
Hi!

Pushbullets is using [document.stylesheets](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/styleSheets) API to fetch all stylesheets and add their own CSS, however due to order of the DOM the expected place of their stylesheets will be actually an dark reader stylesheet and not theirs and will cause an issue. I will look for an workaround.

Regards,
Gusted

**Comment by Gusted** [comment]
Continuing #5009
