### ISSUE TITLE
[Broken Website] Google maps and calendar icons

### ISSUE THREAD

**Issue by StefanoChiodino** [darkreader/darkreader#12068]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [ ] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Icons are black boxes, or a text is displayed instead. Weirdly, I can't reproduce this in a new chrome profile, but if I disable every other plugin I still get this issue on my profile :thinking:

### Website Address

https://www.google.com/maps

### Steps To Reproduce

Toggle darkreaded on/off. Refreshing hard, etc.

### Screenshots

<img width="383" alt="image" src="https://github.com/darkreader/darkreader/assets/1428893/39f4845c-19f2-4430-96dd-5873005a795c">
<img width="366" alt="image" src="https://github.com/darkreader/darkreader/assets/1428893/c1e061aa-7675-4040-b95b-7793dd665a14">

<img width="264" alt="image" src="https://github.com/darkreader/darkreader/assets/1428893/ccbac192-c595-435b-a333-fb033813e6a4">
<img width="304" alt="image" src="https://github.com/darkreader/darkreader/assets/1428893/ded36373-223b-4d73-9f9d-36e5680de1ba">

### Operating System

Macos 14.2 (23C64)

### Web Browser name and version

Chrome 120.0.6099.129

### Dark Reader version

4.9.73

**Comment by Myshor** [comment]
As you did not check "I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension." it seems that other plugin i causing problems with loading the icons and labels... As I saw similar "issue" on other site when I opened tab earlier discarded with Auto Tab Discard then I propose:
1. List all added plugins you have in Chrome to give bigger view to the problem.
2. Check by yourserf what exact plugin causes the problem repeating scenario with Dark Reader and only one other plugin enabled in Chrome.

Waiting for more info.

P.S. If I already guessed Auto Tab Discard then I don't think it will be possible to do anything with Dark Reader because it's not Dark Reader issue but Auto Tab Discard one.

**Comment by StefanoChiodino** [comment]
hey @Myshor , thanks for your reply. I figured it out!

Icons have been implemented using font families. I had Dark Reader replacing fonts to `Helvetica Neue`, which broke this implementation. I wouldn't say that it's a bug, but it may be worth adding `Google Symbols` to a list of fonts that won't be replaced!

**Comment by Myshor** [comment]
I will do some sitefixes for maps and calendar in dynamic mode where I force google-symbols and google-material-icons fonts.
This will not break icons on this sites when some font is set by user in Dark Reader. 😉
