### ISSUE TITLE
AirBnB Email user / customer comment texts not visible on Gmail

### ISSUE THREAD

**Issue by DSiouffi** [darkreader/darkreader#12274]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Greetings,

First of all, apologies if this is not in the right section. I wasn't sure if I should put it in Broken Website or another.

I work as an online hotel customer communication to which we use AirBnB to promote our rooms.
When I receive an email notification from AirBnB of a customer sending me questions, or a customer leaving a comment/review, I can see most of the texts of the email, but the customers message/comment/review texts are not visible when Dark Reader is active.
I use Gmail to receive and read these emails.

I tried different browsers as well but same result.

I'm wondering if you can fix this issue within the extension? I'd gladly provide a couple of emails for you to do the testing if need be.

### Website Address

https://www.gmail.com/

### Steps To Reproduce

1. Go to gmail.com
2. Receive a user/customer message/comment/review email notification from AirBnB
3. Open the email received
4. User/Customer text is not visible

### Screenshots

Without Dark Reader
![DR AirBnB Email White](https://github.com/darkreader/darkreader/assets/41664556/1ab29cf9-deb7-4c7d-95f0-3f2c6bed472e)

With Dark Reader
![DR AirBnB Email Black](https://github.com/darkreader/darkreader/assets/41664556/beaf351e-c93b-40b9-98e1-cfce681306f7)

As you can see above, the text of the message the AirBnB customer wrote is not visible with Dark Reader active. But the rest of the texts outside of that message box is visible, even the user/customer name.

I will gladly send a few sample emails for you to do tests on. Just tell me where I can send them.

### Operating System

Windows 10 Pro

### Web Browser name and version

Brave version 1.62.153

### Dark Reader version

4.9.77

**Comment by Myshor** [comment]
Can you FD this email to my github profile email? I think there is some new design of emails in Airbnb as I found some old ones and they didn't have this bubble with photo so... Only looking on new one I could try to help.

**Comment by DSiouffi** [comment]
> Can you FD this email to my github profile email? I think there is some new design of emails in Airbnb as I found some old ones and they didn't have this bubble with photo so... Only looking on new one I could try to help.

I've sent you 3 samples, each of them are a different type of notification. The Evaluation Notification sample also has few more texts that are not visible.

**Comment by Myshor** [comment]
Ok... looked through them.

The comment from the screen in main description of the issue can be fixed as the color is not forced in email html code, but the rest are forced by AirBnB html code (they include style in html with `!important` to set color) and that Dark Reader can't pass.

so the comment from screen from issue will look like this:
![obraz](https://github.com/darkreader/darkreader/assets/56877029/63bb3bda-aa6a-41d4-8d75-687fd6f0058e)

All links on buttons and text footer stays dark.

Should I push the fix for the comment or we will leave it for a while?

P.S.
CSS to add into mail.google.com to fix:
```
table {
    color: ${black} !important;
}
```

**Comment by DSiouffi** [comment]
Before I answer that. I tried the Filter+ feature in the extension, and that brought out every text in the emails (including the url buttons). The only downside to the Filter+ is that a lot of other things on the Gmail website (mailbox pages and general website contours) becomes darker and less visible (+ search bar typing become not visible at all).
What part of the Filter+ actually makes the invisible texts become visible again? Is there any way to integrate that to the dynamic setting for only Gmail?

**Comment by Myshor** [comment]
Ok... I'll push fix in some minutes.

For the difference how dynamic changes work compared to filter:
Dynamic goes through whole site code - html + css (style) and search for dark colors for text and light backgrounds => then it set some Dark Reader default colors for them. Problem starts if author of the html + css code forces some color with `!important` attribute. Normally we try to use this to force our setting but if something is forced in main code with that then it has bigger priority than Dark Reader's settings. That what happens in the emails you forwarded to me. Some parts of the texts have dark color set with that `!important` attribute.

The Filter don't set any colors it just uses filtering changes to change the background and text color and it uses INVERT. So applying filter works for everything fine but in some cases some things which was already nice in dark mode will change to light mode after INVERT. Wen we have some mixed data (some in dark and some in light mode) filter will just invert them. (That's shortest description.)

Ok... going to push the fix for mail.google.com.

**Comment by DSiouffi** [comment]
Hello Myshor,

Thank you for the explanation, I understand better the workings.

Have you pushed the fix yet? I've updated the Dark Reader extension but I'm not seeing any change.

Regards.

**Comment by Myshor** [comment]
It's pushed but...

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advaced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉

**Comment by DSiouffi** [comment]
Hi Myshor,

I didn't know about that feature. Thanks it worked! I can see the texts of AirBnB Customer messages!

Just one little question left : 
After clicking on Dev Tools, I noticed the Dark Reader main dashboard changed to this
![New DR display](https://github.com/darkreader/darkreader/assets/41664556/7c92c154-248e-4627-92fc-b9ba99e9b1ba)

I couldn't find the way to go back to the original dashboard. Tried finding an answer online but only found how to use the Dev Tools page.

How do I go back to the normal Dashboard?

**Comment by Myshor** [comment]
Need to go again to Dev Tools.

So click Settings. On new options tab in browser select Advanced from menu on the left.
There will be Developer Tools option which open Dark Reader's developer tools.
And in Developer Tools window it will be the same button which you pressed to preview new design. Now it will be named "Switch to old design".

**Comment by Myshor** [comment]
BTW can we close this issue as the main submitted thing is fixed?

**Comment by Myshor** [comment]
Thank you.
