### ISSUE TITLE
[Broken Website] White background in Generative AI on google.com

### ISSUE THREAD

**Issue by Tony20221** [darkreader/darkreader#12275]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Doing a search, the Generative AI section at the top had low contrast between the text and background and it's hard to read.

![image](https://github.com/darkreader/darkreader/assets/99626433/d8edf6ba-78d2-462e-b7f0-3a5db21495e2)

### Website Address

https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&projects=&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title

### Steps To Reproduce

Go to the url provided

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/99626433/59d8637d-036e-4b00-9b54-4b9cd3ab09f6)

### Operating System

Windows 10

### Web Browser name and version

Chrome

### Dark Reader version

latest

**Comment by Myshor** [comment]
First... correct the 'cause it is link to creating issue.

Second thing... go to chrome://extensions/ and click on more details for dark reader see the extension version in your browser.
Check if it is 4.9.77

There was fix for similar Issue #12007 and there was fixes already done for that and should be included in latest 4.9.77 version.

When you confirm you use the latest 4.9.77 version then we will need to check that fix if it needs to be updated.

I can not confirm anything as option to use new AI search is not yet available for me.

**Comment by Tony20221** [comment]
I don't know what your first line is about.

It's version 4.9.77. I am not using AI search specifically. It just appears for me sometimes when I do a Google search. 
Create a Bard account. Maybe then it will show up for you.

**Comment by Myshor** [comment]
> I don't know what your first line is about.

I meant this link - it's not the link to the site with problem.
> https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&projects=&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title

**Comment by Myshor** [comment]
Not sure how that bard should work. Maybe it's location related. I am moved to gemini.google.com when I try to go to bard.google.com and no possibility to enable it in google search. Maybe @suhan-paradkar will take a look as author of last fixes?

**Comment by Tony20221** [comment]
I am in the US. Maybe a VPN with a US ip address might make it show up. I can also attach the html and css source of the page.

**Comment by Myshor** [comment]
That html + css can be helpfull. 🙂

**Comment by Tony20221** [comment]
That  whole section doesn't show if the page is loaded from a file.

**Comment by Myshor** [comment]
and when you analyze that part what is shown in html code in developer tools? Is it some iframe or sth?

Can you try and share what can be found on that white part of page?

**Comment by Tony20221** [comment]
The page seems to have some personal information about me. I see my email address in there.
The colors are not a big issue for me. I can simply turn off the extension and the text is readable.
You can close this issue. Thanks.

**Comment by Myshor** [comment]
I will leave it open - maybe [suhan-paradkar](https://github.com/suhan-paradkar) will look here and comment something.

**Comment by lalo-mx** [comment]
Google Dark theme is not that bad
![image](https://github.com/darkreader/darkreader/assets/7459881/38c213be-b9b9-4b9b-a7db-d19b8ccf6c50)

**Comment by Myshor** [comment]
Same issue here #12288

**Comment by MalekNecibi** [comment]
I think I understand the issue. ([New PR](https://github.com/darkreader/darkreader/pull/12340))

The previously merged [pull request](https://github.com/darkreader/darkreader/pull/12148/files) included a bug that _"double invert's"_ the background of the Generative AI section.
Specifically ````X6JNf```` (the main class for Generative AI) has both ````INVERT```` and ````--darkreader-neutral-background````.

In an earlier commit, ````--darkreader-background```` was mistakenly used instead of ````--darkreader-neutral-background````, avoiding the "double invert" scenario.
But during [code review](https://github.com/darkreader/darkreader/pull/12148/files/94a8c51a1b30a95b42d1e803c64d907705eab8c5#r1455151776) the typo was caught and replaced directly through the GitHub Web UI ([see Verified commit](https://github.com/darkreader/darkreader/pull/12148/commits)).

Relying only on ````--darkreader-neutral-background```` and removing the additions from ````INVERT```` (which are various subclasses within GenAI) worked well when tested locally in Chrome and Brave on Windows 10.

Final mystery, I'm not quite sure what the ````NKrsie```` class is for. My local Google Search source has no reference to that class, and I suspect that it no longer exists as the GenAI feature is in beta. 

I hope this helps, please let me know if there's anything that I missed or if you need any additional info. Also my apologies for the long message or if this comes off as an attack in any way. I'm just getting started in open source and I would love your honest feedback.

Current State (Canceled out):
<img width="477" alt="current_canceled_out" src="https://github.com/darkreader/darkreader/assets/59520645/3c29b878-7e9c-4994-ac17-c4cefe8ec0d8">

Proposed Fix:
<img width="484" alt="proposed_fix" src="https://github.com/darkreader/darkreader/assets/59520645/04c3fb65-a174-41d2-bf4f-acaf15aaad86">

Initial Typo Commit (for reference):
<img width="486" alt="initial_typo" src="https://github.com/darkreader/darkreader/assets/59520645/acb16ff6-6314-4f7e-95e5-4d0497bd155c">

Google Official Dark Mode (for reference):
<img width="477" alt="google_official_dark_mode" src="https://github.com/darkreader/darkreader/assets/59520645/6952a527-a3b4-453b-9e1d-64c8651d760e">

**Comment by Myshor** [comment]
Thanks @MalekNecibi 
Merged your fixes.
