### ISSUE TITLE
Add API so local tools on Desktop can speak with this extension

### ISSUE THREAD

**Issue by daehruoydeef** [darkreader/darkreader#1246]
Hey it would be great if we could expose some kind of an API so local Tools like nightowl for macos or yin-yang for Linux could speak with it. This way it would be possible to not only trigger the theme used on your desktop but also trigger it inside the web. This would be a major step forward for universal Dark / Light mode for everything.

**Comment by KyleWJohnston** [comment]
#1522 allows you to set Dark Reader to activate whenever the system is in dark mode. This might not completely solve your issue for yin-yang, but it works for me.

**Comment by daehruoydeef** [comment]
@KyleWJohnston do you know by any chance if this also works for Linux? I am currently running OSX and while OSX can set system flags which theme is used I cannot verify if this is also true for Linux.

**Comment by KyleWJohnston** [comment]
@daehruoydeef I am using GNOME 3 in Fedora 30 with [Brave-Browser](https://github.com/brave/brave-browser). As soon as I change my Brave setting from light to dark or vice versa, Dark Reader immediately updates.

I was not able to achieve this in Google Chrome since there is no built-in dark mode yet. I tried changing the GNOME setting with `gsettings set org.gnome.desktop.interface 'gtk-theme' 'Adwaita'` or the Tweaks app, but there was no effect on Dark Reader.

**Comment by Gusted** [comment]
> I was not able to achieve this in Google Chrome since there is no built-in dark mode yet. I tried changing the GNOME setting with `gsettings set org.gnome.desktop.interface 'gtk-theme' 'Adwaita'` or the Tweaks app, but there was no effect on Dark Reader

https://bugs.chromium.org/p/chromium/issues/detail?id=998903 :)

It really depends on the browser itself
