### ISSUE TITLE
[Broken Website] bigrr.bukitvista.com Page Unresponsive

### ISSUE THREAD

**Issue by fanesz** [darkreader/darkreader#12547]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

It appears that the issue started on April 2nd yesterday; before that, the website was functioning properly without any problems. Currently, the website is not displaying its intended content at all and only shows an error message stating "Unresponsive Page."

### Website Address

https://bigrr.bukitvista.com/

### Steps To Reproduce

1. Enable dark reader extension
2. Open https://bigrr.bukitvista.com/

### Screenshots

![image](https://github.com/darkreader/darkreader/assets/91197642/6b8c17b6-5e73-4053-b9f0-c23af40207a8)

### Operating System

Windows 11

### Web Browser name and version

Chrome 123.0.6312.86 (Official Build) (64-bit), MS Edge 123.0.2420.65 (Official build) (64-bit)

### Dark Reader version

4.9.81

**Comment by Jamess-Lucass** [comment]
@fanesz I did a bit of testing on my site, it seems to break when using tailwindcss version < 2. My site is on `1.9.6` due to IE support.

Having dark reader enabled and updating my site to tailwindcss version `2.0.0` seemed to work.

Also note that the site does eventually load, it just takes a considerably amount of time when using the newest version of dark reader with tailwindcss v1. We're taking a site that loads in under 400ms, suddenly taking > 2mins. It just hangs for ages.

I am pretty sure this has only occured since the latest dark reader release (`v4.9.81`). Not sure if anything seems apparent in the commits that contributed to the release - https://github.com/darkreader/darkreader/compare/v4.9.81...main.

I shall see if I am able to narrow it down further.

**Comment by Jamess-Lucass** [comment]
@fanesz I did a bit of testing on my site, it seems to break when using tailwindcss version < 3. My site is on `1.9.6` due to IE support.

Having dark reader enabled and updating my site to tailwindcss version `3.0.0` seemed to work.

Also note that the site does eventually load, it just takes a considerably amount of time when using the newest version of dark reader with tailwindcss < v3. We're talking a site that loads in under 200ms, suddenly taking > 2mins. It just hangs for ages.

I am pretty sure this has only occurred since the latest dark reader release (`v4.9.81`). Not sure if anything seems apparent in the commits that contributed to the release - https://github.com/darkreader/darkreader/compare/v4.9.81...main.

I shall see if I am able to narrow it down further.

**Comment by fanesz** [comment]
well ya maybe that's the problem @Jamess-Lucass, because my web using tailwind version `2.2.16`

**Comment by Jamess-Lucass** [comment]
After performing a git bisect, I tracked the issue down to the commit https://github.com/darkreader/darkreader/commit/59a755f69857b294cfc78df27973885c8ab4e8c8

**Comment by Jamess-Lucass** [comment]
I've opened #12554 to track this performance increase issue
