### ISSUE TITLE
Dark mode for "Downloaded" section

### ISSUE THREAD

**Issue by Rakkah** [darkreader/darkreader#1260]
Hey,

Dark Reader works perfectly, I really like it. The only issue I've found so far is that it doesn't work when I open my tab with downloaded files. Then its casually white. Can I changed it somehow?

Cheers!

**Comment by pfarnham** [comment]
Extensions are disabled on chrome:// urls. They can be enabled at the user end via chrome://flags/#extensions-on-chrome-urls which warns: "You are using an unsupported command-line flag: -extensions-on-chrome-urls. Stability and security will suffer." The chrome://*/* permission would need to be added to Dark Reader's manifest. This would allow injection of scripts into chrome:// pages, however these pages make extensive use of Shadow DOM, rendering most elements inaccessible, and any potential changes by Dark Reader minimal to nonexistent. Essentially it is not possible. Chrome 73 officially rolled out dark mode support, so extension to chrome:// pages may come in the future.

**Comment by reseto** [comment]
Not sure if extensions are allowed to modify built-in pages in Chrome, like the Downloads? I think they're not.

However, Chrome since this week's version 74 (Official Build, on Windows) has a dark theme for its configuration pages (Settings, Extensions, Downloads ...) if you have Dark app colors enabled in Windows. Tutorial here: [how-to-enable-dark-mode-for-google-chrome](https://www.howtogeek.com/360650/how-to-enable-dark-mode-for-google-chrome/). On macOS it was already available in Chrome 73.
