### ISSUE TITLE
[Feature Request] Enable "Synchronize site fixes" by default

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#12910]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this feature request to avoid opening a duplicate.

### Is this feature request related to a problem?

No

### Feature Request Description

Enable "Synchronize site fixes" by default, so people don't have to wait for a Dark Reader update to have the latest fixes applied.

**Comment by Myshor** [comment]
There are some pros and cons (as always).

Pros:
- you have always newest fixes fetched.
- you know if the site you had a problem using x.x.x version of DarkReader is already fixed using sitefixes entry.
- you can feel a little bit like a beta tester.

Cons:
- newest fixes can fix one thing but breaks other one. (there is for example some bug related to wikimedia pages that I reopen everytime there is some info that something is or may be broken)
- some sitefixes can be related to some additional changes in the code (if @alexanderby is doing some change - fix - in the code then something can be removed from sitefixes but will not work fine with older Dark Reader version)
- you can have issues that doesn't exists on stable released sitefixes.

I was trying to include the same as pro and con to show you the both sides of the medal... For most of the people they prefer to have stable release and if something is not working fine then downgrade or just wait for next release.

Other people are like the ones that submit bugs, want to have fix ASAP then they can manually set that option to enabled.

I always mention when do some sitefix to the bug that you can enable Synchronize site fixes to have the fix earlier but I only mess in CSS sitefixes. Other devs can do the fix in different ways and even site fixes synchronization won't give solution earlier.

P.S. And there is one more reason it's disabled by default... When every user would download new version of the sitefixes files we do not know how the server brandwitch would work. 😉 (or in the worst scenario the whole access could be blocked because of the very big ammount of request for the files).
