### ISSUE TITLE
[Broken Website] Text on Revolut website not readable

### ISSUE THREAD

**Issue by vikingnope** [darkreader/darkreader#12957]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Most text is not readable since it turns white and background is white.

### Website Address

https://www.revolut.com/currency-converter/convert-usd-to-eur-exchange-rate/

### Steps To Reproduce

1. Go to the site

### Screenshots

With Dark Reader ON:

![image](https://github.com/user-attachments/assets/1e87f4d8-e7fd-4ba8-8683-ef14f2ffff2e)

With Dark Reader OFF:

![image](https://github.com/user-attachments/assets/f05c1bf6-964f-46a0-8fa8-19185e8aa311)

### Operating System

Windows 11

### Web Browser name and version

Floorp 11.14.1

### Dark Reader version

4.9.87

**Comment by Myshor** [comment]
The "problem" is because of the picture with white background.

As I don't want to touch pictures (I tried to make them darker using opacity: 0.5) but more than this picture changed).
In the end I add shadow to all Text-rui (texts on pictures). Which will help on white background and will be almost invisible on darker.

![obraz](https://github.com/user-attachments/assets/17d837e9-6e5d-4fdf-bdd1-9456079763b8)

![obraz](https://github.com/user-attachments/assets/24fb306a-9199-4d3b-a46a-34688014e43f)

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster go to Dark Reader Developer Tools. Click "Preview new design".
- Then with new design go to settings. In settings (new tab) go to advanced. There is option to check to **Synchronizee site fixes**.
- With that enabled newest sitefixes will be updated every browser start. 😉
