### ISSUE TITLE
[Broken Website] winehq.org

### ISSUE THREAD

**Issue by Tiagoquix** [darkreader/darkreader#13014]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

![image](https://github.com/user-attachments/assets/61a3155c-4bc9-4824-a01f-3fbf31f80d19)

Icons should not be inverted (screenshot is with Dark Reader ON).

![image](https://github.com/user-attachments/assets/267b35d4-7da2-4aac-94a8-478d39d6214a)

Wine disappears with Dark Reader (screenshot is with Dark Reader OFF).

### Website Address

https://www.winehq.org/

### Steps To Reproduce

Go to site and see the issues.

### Operating System

Linux

### Web Browser name and version

Firefox 128.0

### Dark Reader version

4.9.88

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee site fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by Myshor** [comment]
@Tiagoquix the glass will be fixed in a while.

The bottom bar is defined in some layers included in html and the color is switched by DR in the code I think. So it can not be fixed using sitefixes. 😞

But I think it's not that much trouble than the glass on articles so I will push only fix for the glass and it will close this issue (again 😋).

Thanks anywhay for catching that - I did not scroll the pages after doing previous fix and did not switch to wiki.winehq.org.

Now the glass should work on all subpages fine.

**Comment by Myshor** [comment]
One more fix for broken (cut) background on https://appdb.winehq.org/ will be in a sec. :)
