### ISSUE TITLE
[Bug] system-ui font is recognized but not applied

### ISSUE THREAD

**Issue by RaptaG** [darkreader/darkreader#13513]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this bug to avoid opening a duplicate.
- [X] I can reproduce this bug in a new, unmodified web browser profile with Dark Reader installed as the only extension.
- [X] I understand I need to use the [Broken Website Report template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=Broken+Website&template=broken-website-report.yml&title=%5BBroken+Website%5D+Replace+with+title) if this bug I am reporting occurs on a single website.

### Bug Description

Using Dark Reader from flatpak LibreWolf on Fedora Linux 41 I have following problem.

Applying Dark Reader's own custom fonts (monospace, serif etc.) works, but when trying to apply the system-ui font, while the font's name uses the font on the listing (see attachment), it not actually applied. I don't think this is a flatpak issue, since the rest of the browser uses my system font just fine and because the system-ui font seems to be recognized too.

### Website Address

Any website

### Steps To Reproduce

1. Install LiberWolf flatpak
2. Install Dark Reader
3. Change your system font
4. Try to select system-ui font on Dark Reader
5. Go to a random website that Dark Reader is enabled
6. The font is not applied

### Expected Behavior

The font to be applied

### Actual Behavior

The font remains the one each website uses

### Screenshots

![image](https://github.com/user-attachments/assets/13fcc3a6-6601-4383-ab84-efa4c7bc6e4d)
![image](https://github.com/user-attachments/assets/f5840f4e-8dae-461b-aa45-d10d84552bf6)

### Operating System

Fedora Linux 41

### Web Browser name and version

LibreWolf 132.0.1-1 (From Flathub)

### Dark Reader version

4.9.96

**Comment by Myshor** [comment]
As the flatpack version of Firefox/Librewolf is the "closed container" version then it's definitely not the Dark Reader problem that it can not find "system-ui" font to set. I never used Firefox (or any other browser) as flatpack. Iprefer to use it from the repo but I think it needs some flatpack configuration that would enable access to the correct system place that browser could use system font (and get the info what system font is used).

Summarizing... It's not to be fixed by Dark Reader team.
