### ISSUE TITLE
[Broken Website] Dropdown menus are still poorly styled

### ISSUE THREAD

**Issue by Pierrounator** [darkreader/darkreader#13551]
### Prerequisites

- [X] I [searched for any existing report](https://github.com/darkreader/darkreader/issues?q=is%3Aissue) about this website issue to avoid opening a duplicate.
- [X] I can reproduce this website issue in a new, unmodified web browser profile with Dark Reader installed as the only extension.

### Website Issue Description

Hi, I've checked #8351 but this fix doesn't fully work actually, I still encounter the same problem that the OP had. Dropdown menus texts are white on very light-grey background.
I can't post the website since it's an intranet, only used on my local network.

Any way to fix it?

### Website Address

intranet

### Steps To Reproduce

Open a dropdown menu and it's unreadable

### Operating System

W11

### Web Browser name and version

Firefox 132.0

### Dark Reader version

4.9.96

**Comment by Myshor** [comment]
Not sure why but linked fix for the mentioned bug is to something totally different.

I will add the fix mentioned in older bug so maybe it will fix your issue. 😉

**Comment by Myshor** [comment]
Wait... so is the problem related to goodreads.com or some intranet site?

Because I am not sure what we should check and fix.

**Comment by Pierrounator** [comment]
Oh no it's not related to goodreads.com, it's for an intranet yes.
But the dropdown menu is designed like the screenshot they posted on their issue: 
![156832710-bb5711d6-e316-4aed-b487-1e4e1cab7d2a](https://github.com/user-attachments/assets/acab3359-e2fd-4c1a-bb6b-ba920ee45851)

**Comment by Myshor** [comment]
Ok... I looked through other bugs like this and found some site that still has similar issue.

As it seems it's the dropdown selection issue on all sites I will add sitefix to `*` section for all websites - that should work on your intranet URLs too. 😉

**Comment by Myshor** [comment]
Sitefix added.

- If you want to have this fix faster you can set **Synchronizee sites fixes** option to check in Advanced section of Settings.
![obraz](https://github.com/user-attachments/assets/9dea8b66-b77a-46ab-8aa6-e50d995718c3)
- With that enabled newest sitefixes will be updated every browser start. 😉
- To open all settings you must click on:
(Old/classic design) More -> All Settings
![obraz](https://github.com/user-attachments/assets/8c17b1f1-e85e-4672-8a88-85930e178e02)
(New/Preview design) Settings in popup
![obraz](https://github.com/user-attachments/assets/e4f586f8-8ce4-47bc-90d7-7451eb030439)

**Comment by Myshor** [comment]
OK... I got simillar submission in #14358 and I will push fix for that in a minute. I will include this issue number in it too.

**Comment by Pierrounator** [comment]
Hi, sorry for the late reply I couldn't get back to work earlier 😦 
Unfortunately, your latest sitefix doesn't fix it. I can't share the website since it's an intranet but I can share the HTML of the page (with some parts removed due the confidentiality): https://pastecode.io/s/gbit9crq

On the line 172, you can see the `<select>` options that are with white text on light grey background.

**Comment by Myshor** [comment]
That doesn't give me anything... Without CSS styles and JS scripts the page can not be loaded and without that I can not even check how it would display on my local machine with newest hotfixes.

That's why only option is to share complete page - you can anonumize it with changing text into SAME LETTER (for example X) if you must - but I need the "skeleton" of the page in HTML, all CSS styles (as some of your intranet page style can force it's colors too) and JavaScripts as without them the page won't load (like the shared html only).

P.S. Did you checked if lates sites fixes are downloaded into your Dark Reader? I am asking this because when you apply your changes in Dark Reader's Developer Tools the newest sites fixes can not be updated until "Reset changes" button is pressed.
P.P.S. Did you check the latest sitefixes after whole page was refreshed (and best refreshed with clear cache using `ctrl`+`shift`+`r`)?

**Comment by Pierrounator** [comment]
Yeah I knew it wouldn't help that much. :(
Is there an easy way to export HTML/CSS/JS like with inspector since I don't own the intranet and it only can be accessed localy?

I also checked in Developer Tools, I did the “Reset Changes” option and unfortunately it doesn't fix it.

**Comment by Myshor** [comment]
At least in firefox you can use the right click menu and choose "save site as" (sorry I am translating to english from polish), then in the second dropdown (save type as) use the "complete" option)

**Comment by Pierrounator** [comment]
Hi there!
I'm sorry if I didn't answer before, but I couldn't even save the website as you requested. When I save it, there is no CSS in it, only the HTML (even if I choose “Complete”) (and even the HTML is not complete because they use `<iframe>`)

Today, the dropdown menus are hard to use again and I think I might find the problem:

<img width="1574" height="854" alt="Image" src="https://github.com/user-attachments/assets/67f2bcba-0700-4e42-98a2-5f6efee8ea87" />
<img width="1575" height="854" alt="Image" src="https://github.com/user-attachments/assets/cc520b7f-fcaa-4cf7-bc21-9d4a64cbff07" />

As you can see on the first screenshot, the dropdown menus are grey on grey BG, but if I deactivated the `html {color-scheme: dark !important;}` they now are fine (at least for the `<options>` because now the `<select>` are unreadable)

**Comment by Myshor** [comment]
Your problem came back because there was other bug which needed to remove whole select * section https://github.com/darkreader/darkreader/issues/14853 and if I again put fix for `*` I will break other pages again.

I will reopen issue and call for @alexanderby as he is the main developer of Dark Reader. Maybe he will think some other solution or ask some other questions which would help to find solution for your problem.
