### ISSUE TITLE
Contradicting privacy policy

### ISSUE THREAD

**Issue by gerroon** [darkreader/darkreader#1386]
You say (in addon's privacy policy)

>Dark Reader had never collected and will never collect any personal data, browsing history etc.

Then you state 
>In future Dark Reader may collect browser version, platform name, display settings and user's filter settings (except website list or any other data which can help identify user). This information is needed for decision on implementing new features, removing unused features or suggesting default settings for new users.

How is this will never collect? Browser version, platform name, display settings, filter settings are clearly personally identifyable data.  How am I supposed to know when you start collecting this data?  I do not even know if you started collecting it or not, given that the privacy policy was written on Oct 18 2018

I think this add-on is heading for a head on crash with major privacy issues.

**Comment by alexanderby** [comment]
I disagree that your browser version, platform name, display settings and filter settings are clearly personally identifiable data. There are millions or even billions users of Chrome or Firefox, Windows or macOS. Could you please give an example, how someone can identify you having info like:
```
browser: Chrome 75
platform: macOS 10.14.4
screen: 1280x800
DPI: 2
filter: brightness 1 contrast 0.9
```

What could be a purpose of such investigation?

Currently there is a need of calculating users having different Chrome versions. Last year there was a case, when Dark Reader was totally rewritten and usage of modern features broke the extension for thousands users of older browsers. They couldn't update the browser because they had old macOS or Windows XP, or custom Chromium builds. If I had this data, I could prevent this sudden strike, preparing people for the update.

Firefox provides this [stats](https://addons.mozilla.org/en-US/firefox/addon/darkreader/statistics/usage/applications/?last=30), so I can assume if using some specific feature will break something.

The idea with screen and filter settings was to see what settings do most users prefer and find any correlation. Currently it seems not necessary, especially that browser provides just screen size and pixel depth, but Firefox and Edge had some experiments with providing info from ambient light sensors, who knows what useful browser features will be available in future. That's why the Privacy Policy states "in future".

It would be also important to see, how many people use Filter or Static mode, maybe the majority is using them and I should improve them instead of fixing bugs for Dynamic mode. Does anybody uses custom fonts, text stroke or Firefox custom browser theme, maybe it's better to wipe them out to simplify the development?

Currently I have no time for creating such a web app for collecting technical data, if this would ever happen I will give a clear option to enable/disable sending such info. Still, since I'm working on a large user interface update, it would be great to understand how people use Dark Reader. So maybe I will make some poll.

**Comment by gerroon** [comment]
Hi

Thanks for the reply.

I do not want to get into a real argument here, but individual components themselves are  not personally identifiable however when you put bunch of identification points together then you can get a pretty good picture of who that person might be. In any case as long as this is well communicated with the user and if such data collection is given as a choice to the user that would be the best. As a user that is choice based data collection is what I would like to see happening, however you are the dev it is up to you to how to implement it.


thanks

**Comment by Zblay** [comment]
Hi guys, 

I agree with gerron and would like to keep dark reader form getting this info. 

Cheers & thanks a lot for all of your work.

**Comment by andre-paulo98** [comment]
Considering that Edge is now using Chromium, and that the Edge version is now out, it would be nice to see it on the Edge store.

**Comment by alexanderby** [comment]
I've updated the privacy policy, permission will be required for collecting technical info. It may never happen, there is absolutely no time for this. 

Dark Reader was published for Edge too (disable DR from CWS before install) https://microsoftedge.microsoft.com/addons/detail/ifoakfbpdcdoeenechcleahebpibofpc

**Comment by Gusted** [comment]
Privacy Policy was changed.
