### ISSUE TITLE
Sub domain control

### ISSUE THREAD

**Issue by sxp** [darkreader/darkreader#147]
If I use to invert the only mode, I add xxx.com to the site list, then I visit sub.xxx.com, I don't want to invert this domain. I can't exclude it. When I use the shortcut key to toggle the domain, extension just adds or remove the sub.xxx.com from site list, but the page has no effect.

I suggest a feature:
If current need add domain is a subdomain of a domain that already exists in the list. Then we do the opposite of the parent domain(add the subdomain to a exclude list?), or we remove the parent domain from the list(When user go back to the parent domain, he can re-add it to the list).

If current need add domain is a parent domain of a exists domain. Then we add it to the list, and don't change the exists domain. (When the parent remove from list, the old subdomain will be saved in the list, so the function of the subdomain has no effect)

In general, I want to add some features to avoid frequent visits to a website, toggle dark reader, but no effect problem.
(Sorry for my poor English)

**Comment by RalphLesch** [comment]
If I understand you correctly, you want to include a domain, but exclude a subdomain or vise versa.
This is already possible, in both "Invert listed only" (include) and "Not invert listed" (exclude) mode:

<table>
<tr><th>Mode</th><th>Include</th><th>Exclude</th><th>List entry</th></tr>
<tr><th rowspan=2>include</th><td>xxx.com</td><td>sub.xxx.com</td><td>`^xxx.com`</td></tr>
<tr>  <td>sub.xxx.com</td><td>xxx.com</td><td>`^sub.xxx.com`</td></tr>
<tr><th rowspan=2>exclude</h><td>xxx.com</td><td>sub.xxx.com</td><td>`^sub.xxx.com`</td></tr>
<tr>  <td>sub.xxx.com</td><td>xxx.com</td><td>`^xxx.com`</td></tr>
</table>

Problematic is the case of including/excluding all subdomains except for one or more, like include "\*.xxx.com", but exclude "www.xxx.com".
Currently, the only way I can think of, would be to add an invert fix (developer tools) for "\*.xxx.com", and exclude "www.xxx.com" (in exclude mode).

For DarkReader, I would suggest to either use both include and exclude lists together or to change to pattern syntax, for e.g. full regex support (see [my comment about the syntax](/alexanderby/darkreader/issues/86#issuecomment-355656408)).

**Comment by alexanderby** [comment]
`^` meaning the beginning of the string works. What about both exclude and include lists, I plan to make unlimited count of groups with different settings.

**Comment by RalphLesch** [comment]
Sub groups for domains should be enough to solve most URL match problems.
I would suggest an extended hierarchy:
- common/shared group, with inversion fixes that are always used (unless deactivated by an option in the other rules maybe?).
- site / domain groups for URL pattern, will be used unless subdomain matches are found.
  - subdomain groups: overwrite (super)domain rules.

Then a layout like this is possible:
```json
{
    "common": { "invert etc (fixes)": "", 
    },
    "sites": {
        "*": {
            "fixes": "",
            "subsites": {
                "domain1-pattern": {
                    "fixes": "",
                    "subsites": {
                      "subdomain1-pattern": {},
                      "subdomain2-pattern": {}
                    }
                },
                "domain2-pattern": {}
            }
        }
    }
}
```
Side note: collapsible sub groups in the editor and/or a complete separation for the sites (show only site config) would help a lot in the new UI.

**Comment by alexanderby** [comment]
Here is what I'm going to do with the list, similar to glob file patterns https://github.com/alexanderby/darkreader/issues/373

**Comment by Gusted** [comment]
As of #2327  you can simply exlude an subdomain by !subdomain.example.com

**Comment by aogier** [comment]
Hi, I'm having probably the same problem here: I'd want to exclude github.com (which has his own dark theme now), but include docs.github.com, and this does not seem possible with the button.

**Comment by nyuszika7h** [comment]
@aogier The solution was explained a few comments above. You can manually change the exclude list to have `^github.com` instead of `github.com`.

**Comment by psarno** [comment]
I am unable to get this to work.

I have a "Not Invert List" with "twitter.com", because I am using their dark theme.

I want "blogs.twitter.com" to let Dark Reader handle it as their theme doesn't apply there.

I tried entering "^blogs.twitter.com" and "!blogs.twitter.com" in the list and they don't have any effect, it seems the presence of "twitter.com" already in the list prevents Dark Reader from working on the subdomain.

**Comment by Gusted** [comment]
Add `^twitter.com` that will disable it just for twitter and not for any subdomains like `blogs.twitter.com`

**Comment by ackvf** [comment]
@RalphLesch 
> For DarkReader, I would suggest to either use both include and exclude lists together or to change to pattern syntax, for e.g. full regex support (see [my comment about the syntax](/alexanderby/darkreader/issues/86#issuecomment-355656408)).

This is the first time I am seeing a mention about using both _include_ and _exclude_ lists together. How can I do that?

**Comment by megamorphg** [comment]
> As of #2327 you can simply exlude an subdomain by !subdomain.example.com

If we can get "!" to work, this would be a great band-aid for now.
Currently "!" doesn't work to whitelist a subdomain (while the overall domain is blacklisted). Maybe ! URLs needs to be allowed precedence no matter where it is in the list?

**Comment by mattwelke** [comment]
Was talking in #7503 about my issue with the GCP console.

Here's a detailed explanation of my use case.

Just realized I didn't describe my issue properly.

For google.com, I don't want to use Dark Reader because they support a proper dark theme. So I disable Dark Reader on google.com by clicking that rectangle button in the top left corner:

![image](https://user-images.githubusercontent.com/7719209/155219997-15ab2c42-a13a-4abf-a202-34fa70720eb0.png)

For cloud.google.com, I also don't want to use Dark Reader because even though their documentation doesn't have a dark theme, that site doesn't yet behave nicely with Dark Reader. I'm okay sticking to the site's default CSS.

So, on cloud.google.com, I could click the top left rectangle button to override how I disabled it for google.com:

![image](https://user-images.githubusercontent.com/7719209/155220189-a29112a7-11c3-4a4d-a8cb-4e508b084a54.png)

But instead, I don't. I leave it alone:

![image](https://user-images.githubusercontent.com/7719209/155220231-88e8c8af-2a88-44f7-aebe-3b99c25bbf0a.png)

For console.cloud.google.com, I *do* want Dark Reader enabled because it doesn't have a dark theme and Dark Reader just a good job creating one for it. I try to override the disable I did for google.com by clicking the top left rectangle button:

![dark_reader_gcp_console](https://user-images.githubusercontent.com/7719209/155220681-5a57b4b2-ca26-4e7f-b5f9-0cf7a4cfd2fb.gif)

When I click the button, nothing happens. I believe that's the issue with subdomains I'm running into here. If I do the override of my settings for google.com at the cloud.google.com level (making it dark), then the console becomes dark and I can do another override at the console.google.com level to make it light. But that's the opposite of what I want. I want cloud.google.com to be light and console.cloud.google.com to be dark:

![dark_reader_gcp_console_2](https://user-images.githubusercontent.com/7719209/155221155-e482d3a4-7159-47c2-85db-1a4fc77ca9ad.gif)

**Comment by Revadike** [comment]
same thing for https://console.firebase.google.com

**Comment by alexanderby** [comment]
Fixed by https://github.com/darkreader/darkreader/commit/5546bd52e82f00dd1c436867f340170faaea868f
