### ISSUE TITLE
Please update the Safari version

### ISSUE THREAD

**Issue by Jax0rz** [darkreader/darkreader#1563]
As a paid user of safari version,I found you don't keep update the safari version frequently .

**Comment by villiansv** [comment]
That's a big understatement. Last Safari version was 5 months ago, as a comparison there have been about 7 Firefox releases since then. "Users fixes for websites" show up in the changelog for each release on the Mozilla addon version history - even if new features can't be implemented in the Safari extension model, at the very least these fixes should be included in an update waaaaay more often than what we're seeing.

**Comment by alexanderby** [comment]
The last update was in November. Currently I'm working on implementing a new app design, so you should expect an update by the end of this month.

Apple has fixed many issues with its IDE, previously I had to restart it several times after making a minor code change, which made the work disappointing. But now it works fine. So, I will try making more frequent updates.

**Comment by dannyboy90** [comment]
Please do

**Comment by Gusted** [comment]
#2927 :D

**Comment by cariacou** [comment]
any news on this?

**Comment by Gusted** [comment]
> any news on this?

Their was news he wanted to bring a new update, however I didn't see one...
@alexanderby any comment?

**Comment by alexanderby** [comment]
As you might heard Safari 14 will support web extensions. But according to the statistics quite few people are using the latest browser version. Also macOS High Sierra users will not be able to use it. So more time for research is needed.

Then I tried to update the legacy extension with the newest dynamic mode improvements, but failed. But will continue in the meantime.

**Comment by alexanderby** [comment]
By the way submitted an update for the review.

**Comment by danemacmillan** [comment]
Just got it this morning. Thanks!

**Comment by jpuris** [comment]
Please close the issue, it is resolved.
