### ISSUE TITLE
Please don't override the image/graphs/figures of Wikipedia.

### ISSUE THREAD

**Issue by PranavBhattarai** [darkreader/darkreader#1639]
I was reading an article about "[Economic Globalization](https://en.wikipedia.org/wiki/Economic_globalization)", using the "Dynamic" theme option (because it is a very good theme option on almost every website).

But the problem is:
![Screenshot from 2019-10-16 09-56-58](https://user-images.githubusercontent.com/32763112/66887661-64e3ef00-effb-11e9-8225-40e6f8ca9f6a.png)

But it should actuall look like this:
![Screenshot from 2019-10-16 09-58-06](https://user-images.githubusercontent.com/32763112/66887704-90ff7000-effb-11e9-99be-14e5b758cd6d.png)

What everyone wants is "Darkreader" not touching the image at all. Because its not required. Its pointless. Darkreader works well on Facebook, why not in Wikipedia? This is a sad thing for students, journalist, or anyone who can read.

**Comment by justsh** [comment]
Dark Reader is not touching the image; that's an SVG with a transparent background.

**Comment by PranavBhattarai** [comment]
> SVG with a transparent background

Can you elaborate on it more? Whose fault it is then? Browser fault! 
Either way, deactivating/uninstalling the extension solves the problem but I don't want to.

**Comment by Jnss98b** [comment]
What part of that did you not understand? Basically it's a vector image with a transparent background (a.k.a. the background is seethrough). Whoever created the SVG is the one to be blamed here. But then again, it's not their fault because it's not like they had to account for an inverted background.

**Comment by PranavBhattarai** [comment]
@Jnss98b @justsh 

Is there no technique that can be implemented in DarkReader where DarkReader recognizes this **SVG** with a transparent background & not convert it? That would be a smart move instead of blaming( I am talking about myself). Should I have to make a separate feature request for this? I think it would be a really cool concept.

**Comment by Jnss98b** [comment]
Again, this extension doesn't touch the SVG at all. It seems like you're having a hard time understanding what transparent background actually means. The dark background in your screenshot IS the background of the Wikipedia page itself. Being transparent means that it shows everything behind it, which in this case means the page's background

**Comment by PranavBhattarai** [comment]
But now I am not asking who's the fault is this or how is this happening.

I am asking in there a certain logic that we can implement in DarkReader where DarkReader understands these kinds of situations. Situations like transparent graphs on this condition. _You make it sounds like its impossible._ There must be a way around to handle this.

(sorry, noob)

**Comment by foresterr** [comment]
I don't see why Dark Reader should not set the background color of any png or svg image (any other formats that support transparency?) to white for Wikipedia. Either the image has transparency, in which case it was almost certainly designed for Wikipedia's default white background, or it does not, in which case setting the background color won't change a thing (because it's all behind the image).

I didn't even think of it myself, it's already implemented this way for certain thumbnails. I don't see why it shouldn't be done for all images on Wikipedia that can have transparency.

**Comment by JohnTasto** [comment]
I would prefer the brightness/value of all the colors in such SVGs to be inverted so my eyes aren't blown out by random splotches of white. They'd be legible again, and since SVGs aren't photographs, they wouldn't look weird. Same with PNGs, which _usually_ aren't photographs.

**Comment by Gusted** [comment]
#2321 Would resolve this issue
#1963 the Issue that also would be resolved

**Comment by Myshor** [comment]
It's not easy to make fixes to all SVGs on wikipedia article cause it will damage all icons which are used as SVG in the page.

There will be a fix for checkboard background in preview when screen is clicked.

I added the same fix for transparent SVG files for hover.
Now it will add background when you hover your cursor over it. ;)
