### ISSUE TITLE
Feature request: Allow app usage (API) to invert embedded IFrames

### ISSUE THREAD

**Issue by rfox12** [darkreader/darkreader#1840]
I'm using darkreader as an npm package dependency in my project--works great!  Simple to use.  enable/disable work just fine.  But I noticed an embedded IFrame was not effected on my Web page (I have control over both sources--and they run from the same origin).  My question is: how can I inject darkreader into my IFrame so that I can invert it?  Is there some way I can call enable on the IFrame dom element?  Thanks--great little program.  

Side question: is there a way to ignore (i.e. not invert) elements of my dom with CSS selectors?

**Comment by changkun** [comment]
Same problem here, did you find any workground?

**Comment by Gusted** [comment]
Hi their!

Hmm emmbed iframe you mean. Could you give the exact tag you use just redact the src=. With normal iframes it works fine.

For now there isn't a way to ignore it..

**Comment by changkun** [comment]
@Gusted Hi Gusted, thanks for your response. Here is my situation:

I have an iframe that its src is dynamically changed by javascript. However, the dark mode works for the whole website but doesn't work for the iframe that is loaded later.

The project I am using darkreader is https://github.com/changkun/ssaplayground. In the public folder, you can find the iframe in the [index.html](https://github.com/changkun/ssaplayground/blob/master/public/index.html), since the dark mode isn't working, so if you would like to try it then you might need to activate the commented switch and scripts in the bottom of the index.html.

**Comment by Gusted** [comment]
Could you provide the code so I can reproduce the IFrame.

**Comment by changkun** [comment]
@Gusted Hi, sorry for not providing minimum reproducible code before.

In the attachment, you have two HTML files. The `index.html` is the example that uses the darkreader, and `ssa.html` is the iframe that `index.html` tries to load. To prevent the CORS issue, you need to serve them as a web service, e.g. `python -m SimpleHTTPServer 8080`

On the top left corner, you find a toggle for the dark mode, once you toggled the dark mode, you can see the iframe is not inverted properly. This does not happen when I use the dardreader browser plugin.

[code.zip](https://github.com/darkreader/darkreader/files/4439751/code.zip)

**Comment by Gusted** [comment]
Seems like Darkreader Mutationobservers don't look inside a IFrame...

**Comment by changkun** [comment]
> Mutationobservers

Is there any workaround for this? Why the plugin works but the library doesn't?

**Comment by Gusted** [comment]
Nope It just need to have another function to look inside Iframes and Look for changes But a Iframe are Bassicly Shadow-Doms those 2 are very hard to code and make changes to them they are their own DOM/Style etc etc. Shadow-doms are now good/perfect handeled by Darkreader But IFrames are a bit stranges. I'm gonna try to debug it and see where the fault is in darkreader. And no not a current workaround well yeah. In ssa.html making the enable function and execute it from the Iframe perspective. That could maybe help for now not sure

**Comment by Gusted** [comment]
The Min.js is running 4.9.2 I know their was recently a shadow-dom improvements Not sure If this version already had it... I cannot see any darkreader.js running on 4.9.4

**Comment by changkun** [comment]
> The Min.js is running 4.9.2 I know their was recently a shadow-dom improvements Not sure If this version already had it... I cannot see any darkreader.js running on 4.9.4

I tried the latest build (4.9.4), it doesn't work either.

**Comment by Gusted** [comment]
Okay HMM I think I'm seeing the problem. Darkreader Doesn't handle any Iframe to explore. It's only check if it's a Iframe, because Content scripts. Extension can load Content scripts that act like if it was executed from the site self pretty handy if you want to make it dark etc. But Content scripts are automatticly injected into Iframes and on their way make that dark.. But because it's loaded from just the main site and not into the Iframe... It's not gonna dark anything in the Iframe and for their It's bugged.

**Comment by Gusted** [comment]
I'm trying to get a workaround Wouldn't be hard If i'm seeing the results

**Comment by Gusted** [comment]
[nice.zip](https://github.com/darkreader/darkreader/files/4440473/nice.zip)
This is a working workaround Only It doens't check real time only after Refresh But that Is someting Darkreader Can't fix Just up to the Developer to check if every 500ms or something Or some hooking into the Iframe src :/

**Comment by changkun** [comment]
I tried several ways of injecting that script into the frame, but in the end, it cannot be controlled by the toggle. Sad...

**Comment by Gusted** [comment]
Yeah it's kind of sucks but the only workaround for now I can try to get it working with just the toggle

**Comment by Gusted** [comment]
[nice.zip](https://github.com/darkreader/darkreader/files/4440902/nice.zip)
This POC works

**Comment by changkun** [comment]
@Gusted Thanks for the help. The later one looks good but your changes are in the ssa.html which is not really possible to control from `index.html`, is there a way to inject your changes in `ssa.html` from `index.html` using JS?

**Comment by Gusted** [comment]
[nice (2).zip](https://github.com/darkreader/darkreader/files/4443567/nice.2.zip)
You mean something like this? Don't ask why the toggle button is now inverted with toggling.

**Comment by changkun** [comment]
> [nice (2).zip](https://github.com/darkreader/darkreader/files/4443567/nice.2.zip)
> You mean something like this? Don't ask why the toggle button is now inverted with toggling.

No. I mean, can your workaround only changes the `index.html` rather than `ssa.html`? Your workaround copied the JS from `index.html` to `ssa.html`, in a real case, we cannot do that.

**Comment by changkun** [comment]
No. I mean, can your workaround only changes the index.html rather than ssa.html? Your workaround changes them both. In a real case, we cannot do that.

**Comment by Gusted** [comment]
That's the only solution because darkreader only dark the site itself and skips I frames and because it was actually used as content script it will automatically inject into all I frames but because your now loading into a api you need to do it manually darken the Iframe it not that different than the extension just you need to trigger to enable it.

**Comment by Gusted** [comment]
I think we are misunderstanding each other

**Comment by Gusted** [comment]
Not possible.
