### ISSUE TITLE
Doesn't make dark google.com yandex.com

### ISSUE THREAD

**Issue by Mi3antrop** [darkreader/darkreader#1893]
Doesn't make dark:
google.com
google.com/*
yandex.com
yandex.com/*

**Comment by LeoRiether** [comment]
Hey there, I had the same problem in Opera a few days ago. If your issue is the same, just go to `chrome://extensions`, scroll to the darkreader extension and check "Allow access to search page results". If you're not using Opera, however, please say which browser you're in so we can solve the issue more efficiently.

**Comment by Gusted** [comment]
@Mi3antrop 
Could you give some more info about which browser you are using and if you are running the latest version of Dark Reader?

**Comment by planigan** [comment]
I have the same problem with google search pages on Google Chrome Version 83.0.4103.106 (Official Build) (64-bit) with Dark Reader 4.9.11 on Ubuntu 20.04.

**Comment by Gusted** [comment]
#2969
