### ISSUE TITLE
Invalid font on dark mode 

### ISSUE THREAD

**Issue by DarkShadowFT** [darkreader/darkreader#1926]
![image](https://user-images.githubusercontent.com/41124884/72874762-8fd59180-3d14-11ea-8ab1-2925dbcb1953.png)
This is with dark reader on but set to light mode.

![image](https://user-images.githubusercontent.com/41124884/72874823-b5629b00-3d14-11ea-9798-d4b149c946b7.png)
This is with same but dark reader set to dark mode. 

This is the font that I use with dark reader.
![image](https://user-images.githubusercontent.com/41124884/72874861-ca3f2e80-3d14-11ea-8e0f-24d36aab4136.png)
I'm using vivaldi. This is not a browser issue and chromium with dark reader also has the same issue. I'm using Arch linux with KDE plasma ATM.

**Comment by WebMechanic** [comment]
Where did you see this?

Looks to me like the formula is a graphic file using a black font with alpha transpareny and a white-ish matte colour/background. It's either a GIF or PNG not the "wrong font".

Try this MathML test page from Mozilla. 
The right column should render corrently in DarkMode as it uses **real fonts**
https://mdn.mozillademos.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test$samples/MathML_Torture_Test

**Comment by DarkShadowFT** [comment]
![image](https://user-images.githubusercontent.com/41124884/73185221-7af76480-413f-11ea-9478-8cb388ecd28b.png)
You're right.

**Comment by WebMechanic** [comment]
Formulas look messed up. Using Chrome/Opera/Edgium/Vivaldi? Bad luck then. 
**Google removed support for MathML in Blink**. Fortunately change is on the way.
https://mathml.igalia.com/news/2019/10/31/mathml-in-chromium-upstream-process-started/

That's Firefox' rendering of that page (right column MathML):
![MathML](https://user-images.githubusercontent.com/638340/73186279-bc781780-411f-11ea-9da2-9b48dec8a1b3.png)

**Comment by DarkShadowFT** [comment]
Firefox can't display it properly in dark mode either. 
This is the website https://www.mathsisfun.com/algebra/partial-sums.html
I'm using Arch Linux with KDE Plasma if that matters.

**Comment by WebMechanic** [comment]
@DarkShadowFT mathisfun.com uses some images with solid white backgrounds for the formulae, and some are GIFs with transparent - i.e. examples with the halo. Coloured Diagrams are ok, 'cos these are PNGs

With transparent GIF's there will **always** be a halo around the letters, that's the problem with GIF format: 256 colors max, and transparency is on/of or none. PNGs do a better job blending in with alpha transparency, but black pixels remain black pixels anywhere. Any you can't just blindly invert images.

The MathML test I linked to page looks perfect in FF - there's no fancy CSS to make the font look nice though. This test was only to check **if MathML** is rendered at all; which is not the case in browser that run on Blink: Chrome, Opera, Vivaldi, Edgium, on any platform.

Because MathML (like HTML or SVG) uses real fonts, it's the only **save** way to properly handle the display of mathematical formuals in the same manner and according to the same "darkmode" rules as allthe other regular text on a page.
A transparent GIF will alwas always look like shit and depict a halo whre transparency ought to begin. This is why the PNG format was invented: to have true alpha transpareency (among other goodies). 
Nothing the extension can do about a bad GIF.
