### ISSUE TITLE
Android: Firefox Preview (Fenix) support

### ISSUE THREAD

**Issue by gitoss** [darkreader/darkreader#1946]
This is an obvious issue, but the one extension I'm really missing with Firefox Preview (Fenix) is 'Dark Reader' - and that's why I back using Fennec (the F-Droid Nighly). Please add asap when the Fenix api is ready - thanks!

https://blog.mozilla.org/addons/2019/10/23/fx-preview-geckoview-add-ons-support/
https://support.mozilla.org/en-US/kb/add-compatibility-firefox-preview

**Comment by alexanderby** [comment]
The Firefox team requested me to add the support. Many work should be done.

Just returned from FOSDEM Open Source Speed Dating, we will see if Mozilla will contribute to the project.

**Comment by bryansteiner** [comment]
Would love to see this supported! It's the last feature I'm waiting for before making the full-tine switch to Firefox Preview.

**Comment by serovar** [comment]
It is now in Firefox Nightly and Firefox Preview Nightly :)

![EVkakHHWoAAvXHc](https://user-images.githubusercontent.com/6732420/79317416-fb8b5d00-7f05-11ea-95c1-a4cf920cf1f5.jpg)

Links (since the Play Store is not being updated timely due to longer review times for the Coronavirus situation):

[Firefox Nightly](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly/latest)

[Firefox Preview Nightly](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.nightly/latest)

**Comment by babygau** [comment]
i just tried it out, apparently no sepia filter for light theme atm 😭

**Comment by Gusted** [comment]
New UI you can if you have 4.9.6 open devtools and click on Old design.

> i just tried it out, apparently no sepia filter for light theme atm 😭

**Comment by Gusted** [comment]
It's in Fenix.
