### ISSUE TITLE
Toggle button doesn't work on IPv6 addresses

### ISSUE THREAD

**Issue by thetric** [darkreader/darkreader#197]
Pressing the "Toggle" button on [::1]:3000 (ipv6 version of localhost:3000) has no effect. The only way to disable the extension is to press the "off" button which globally disables Dark Reader :(

Could you please make the toggling work with IPv6 loopback addresses?

**Comment by Pysis868** [comment]
Same problem with localhost:8000.  No `id="dark-reader-style"` elements in `head` or anywhere.  Tried bypassing the hotkey and working in the Chrome Extension dialog, but all I could do was toggle the extension, change the toggle site hotkey, and add it to the ignore list, but not toggle the site itself.  I even know it works because I switched that to a whitelist invert mode and it made the `localhost` site I already had open invert well, even without refreshing!  So there's just some block here maybe hardcoded about localhost??

As a bonus I found a workaround like I have already made some hostnames to point to various local services, so I made one for viewing these documents and it started in my default dark mode all working this way! O_o

**Comment by servadestroya** [comment]
A year later and this is still an issue. 

![2019-07-19_15-26-06](https://user-images.githubusercontent.com/24995257/61558601-e9939100-aa3d-11e9-8ba1-5f6901d3f3b5.gif)

**Comment by TheV360** [comment]
Still broken 6 months later.

![a](https://user-images.githubusercontent.com/25177071/73128084-485f3780-3f98-11ea-80f8-5930093289c3.gif)

**Comment by Fefke** [comment]
Well is someone (still) working on that Bug?

**Comment by narfanar** [comment]
This happens with `arxiv.org` now... :/

**Comment by Gusted** [comment]
> This happens with `arxiv.org` now... :/

Not Ipv6 and non existing domain

**Comment by Gusted** [comment]
https://i.imgur.com/8ZRu2gR.gifv 
I just need to tweak the decompress function a bit to get the full IPV6 but than it's done :)

**Comment by narfanar** [comment]
@Gusted , It's not IPv6-specific, maybe, I have no idea.

But it's the same symptoms.

And arxiv.org definitely exists? I'm confused by the statement.

https://arxiv.org
