### ISSUE TITLE
Blocked Add-On

### ISSUE THREAD

**Issue by Wolf68k** [darkreader/darkreader#2056]
Having done nothing today but start up the Firefox 73.0.1 suddenly the add-on is blocked.

**Comment by obadz** [comment]
It's not darkreader that was blocked but some altered copy.

It seems like there was malicious intent, but Mozilla is leaving us users with very little information.

@alexanderby, I know this has nothing to do with you, but any chance you could help us understand what we've been exposed to?

Some threads:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1618814
* https://discourse.mozilla.org/t/addon-is-declared-malware-and-thats-it/54922
* https://www.reddit.com/r/firefox/comments/fbfu45/question_regarding_a_firefox_addon_being_blocked/
* https://www.reddit.com/r/firefox/comments/fb0ib5/dark_reader_addon_disabled_by_firefox_for/

**Comment by alexanderby** [comment]
Thanks for the details. How did you get the installation link?

**Comment by alexanderby** [comment]
Could you please open [Firefox user's profile](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data#w_how-do-i-find-my-profile), open `extensions` folder and [send me](mailto:darkreaderapp@gmail.com?subject=Blocked%20Firefox%20XPI) an XPI file of the blocked extension?

**Comment by Wolf68k** [comment]
I wish I could but I've removed it once I realized that I had the wrong extension. I did get it from Mozilla's web site. The best I can do is give you the URL but the page doesn't exist any more.
https://addons.mozilla.org/en-US/firefox/addon/dark-mode-webextension/?src=search
I think it was that page that also brought me to here. The Support link that is.

Luckily I don't login to that many websites or other have to enter login credentials, so there was only a few I had to change my password on, most have 2 factor as well.

**Comment by alexanderby** [comment]
@Wolf68k I think the link you provided points to a legit extension, not open source though.

**Comment by suika-ibuki** [comment]
An archive of the extension was shared [here](https://www.dropbox.com/s/7u0lxjc3310wl4c/Dark%20Mode%20-%202019-12-18%20%28v2.0.2%29.xpi?dl=0), from the [discourse.mozilla](https://discourse.mozilla.org/t/addon-is-declared-malware-and-thats-it/54922) thread. [This](https://webcache.googleusercontent.com/search?q=cache:0VeCrrSnFXEJ:https://addons.mozilla.org/en-US/firefox/addon/dark-mode-zen/+&cd=1&hl=en&ct=clnk&gl=us) is a cached version of the page on AMO that was offering the addon.

**Comment by obadz** [comment]
I had a different one: https://gofile.io/?c=gEiX0j (sha256: 6fd50246e20b52ba429f5e45361cb6673cd302ed02858644baabde4eab97cce9).

The one in the above link had sha256: 830cd2da9ae5cf65a6303a768a71b25140e51684c91e54a0773501325c707440

**Comment by alexanderby** [comment]
So, I tried to investigate, what's going on.

There was much unused code added to an older Dark Reader version. Then I've noticed a strange icon loading. It turned out, that a `charlie.png` icon contained a strange text structure. Decoding it using the extension's code resulted to a [code](https://www.dropbox.com/s/kgmvolze4p8dfre/output-malware.js?dl=0), that after 5 days loads another code from a [remote source](https://www.liveupdt.com/ext/qm.php?f=svr) encoded in several ways. I've [decoded it](https://www.dropbox.com/s/w91smeukjehzm9l/remote-eval.js?dl=0), it's hard to tell what this code and a whole thing is trying to do, it shows some popups and captchas and sends some data to [the same domain](https://www.liveupdt.com/ext/qm.php?f=ga) or [a fallback](https://www.dealctr.com/ext/qm.php?f=ga). It also includes some Chinese comments.

I've found that somebody have already investigated a similar case https://github.com/rainyrainyday/HomebrewOverlay

So, maybe @rainyrainyday can explain what happened to you.

**Comment by obadz** [comment]
Thanks a lot @alexanderby, that is *really* helpful! A few questions for you:

1. You mention the code loads something after 5 days from a remote source. Does it save some state somewhere to keep track of time etc?
2. Assuming Firefox security systems are Ok (is that a reasonable assumption here?), can the malicious code leave something behind that's still there after the add-on was disabled?
3. Beyond reading password, could the code have read authentication 'cookies' and sent those back to mothership?
4. Can it run something outside of Firefox? (I assume not but best to check)

Again, thank you for the support you've been providing!

**Comment by alexanderby** [comment]
@obadz The extension declared an access to web requests, it seems it is removing [x-frame-options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) header for some purposes. I'm not sure the API allows to read cookies, maybe uBlock author knows more.

Also, if you are logged into sites like Facebook and GMail, the extension can read everything even without the need of your visit to the website (at least it can on Chrome, Firefox seems like fixed this, it should have been reported by a security researched, who have audited Dark Reader more than a year ago). In your case it's hard to tell, because the image, that should contain a script, that is loading remote code, is missing, but I see another code that performs a similar thing.

But, when you uninstall or disable the extension (through a browser's menu), it cannot do anything (if it's not an extension with the permission to manage other extensions and didn't install any other extension before). It stores its data using the `chrome.storage.local` API as a text, that cannot be executed in any way.

Weird situation, you'd better use Recommended Extensions for Firefox, they manually audit all the code. What about Chrome, it's hard to tell what they are doing, seems like just put a timeout for 2 weeks for every submission. I've reported another Dark Mode extension, that steals user's browsing history 2 days ago, but it's still there.

**Comment by mohe2015** [comment]
I'm not an expert but if it can manipulate headers it **could theoretically** change websites so they load some malicious script. So you should definitely delete all browser data (cache, history, etc).

**Comment by CyBiS** [comment]
@alexanderby Thanks for your [blog post](https://darkreader.org/blog/attention/) to make all dark reader user aware of this issue. However, I do not get how the users are actually supposed to check whether they have the correct addon or not.

Could you please confirm if this is the correct dark reader addon v4.9.4 (last update on 30.03.2020) for Firefox: https://addons.mozilla.org/de/firefox/addon/darkreader/? Here is the zipped XPI file from that firefox page (which by the way is the very same binary I have in my Firefox extension folder): [dark_reader-4.9.4-an+fx.xpi.zip](https://github.com/darkreader/darkreader/files/4482663/dark_reader-4.9.4-an%2Bfx.xpi.zip).

**Comment by Gusted** [comment]
> Could you please confirm if this is the correct dark reader addon v4.9.4 (last update on 30.03.2020) for Firefox: [addons.mozilla.org/de/firefox/addon/darkreader](https://addons.mozilla.org/de/firefox/addon/darkreader/)? Here is the zipped XPI file from that firefox page (which by the way is the very same binary I have in my Firefox extension folder): [dark_reader-4.9.4-an+fx.xpi.zip](https://github.com/darkreader/darkreader/files/4482663/dark_reader-4.9.4-an%2Bfx.xpi.zip).

That's the correct one

**Comment by Gusted** [comment]
> @alexanderby Thanks for your [blog post](https://darkreader.org/blog/attention/) to make all dark reader users aware of this issue. However, I do not get how the users are actually supposed to check whether they have the correct addon or not.

Most of not all are now being blocked by giving a warning. It will be enough for the most part implementing a signature check will be too complicated with Hash matching.

**Comment by alexanderby** [comment]
@CyBiS I've added some steps, please refresh the article.

**Comment by Gusted** [comment]
As of this now leaded to https://github.com/darkreader/darkreader/issues/2293 and https://darkreader.org/blog/attention/ If you feel otherwise feel free to comment.
