### ISSUE TITLE
Dynamic causing issues with Wikipedia

### ISSUE THREAD

**Issue by Thepenguin9** [darkreader/darkreader#2101]
Whilst using Vector skin on Wikipedia, the site almost universally functions as expected, though when notifications are received the container for the notification is white-on-white until it will fade to dark after a short time.
I will try and grab a screenshot/gif of this in action.

**Comment by Thepenguin9** [comment]
![GIF of bug](https://light-theme-hurts.my-ey.es/5haZrc3.gif)

**Comment by ElhemEnohpi** [comment]
It's related to an animation of the background colour between unseen and unread/read messages. Search the dev tools window for "wikipedia", and try adding this under CSS:

```
.mw-echo-ui-notificationItemWidget-initiallyUnseen.mw-echo-ui-notificationItemWidget-unread {
    background-color: rgb(24, 26, 27) !important;
}
```
There's maybe a more elegant way to do it, but this makes it readable at least.

**Comment by Thepenguin9** [comment]
I can now make out the message without having to wait. Thanks for the ad-hoc fix, is it worth adding this to master? The behaviour is much better than without, and the messages still blink when they've been seen.

**Comment by Gusted** [comment]
It's always nice to have this little things into the master. Only problem is I don't understand

> .mw-echo-ui-notificationItemWidget-initiallyUnseen.mw-echo-ui-notificationItemWidget-unread {
>     background-color: rgb(24, 26, 27) !important;
> }
If this fix the problem So yes? Could you give a gif so I can make a PR for this

**Comment by Thepenguin9** [comment]
> If this fix the problem So yes? Could you give a gif so I can make a PR for this

A gif isn't necessary. It makes the unseen colour (the white) a shade of grey. Function is normal other than that. Matches everything else

**Comment by ElhemEnohpi** [comment]
There's a CSS animation like this:
```
.mw-echo-ui-notificationItemWidget-initiallyUnseen {
    -webkit-animation-name: unseen-fadeout-to-read;
    animation-name: unseen-fadeout-to-read;
    -webkit-animation-duration: 0.5s;
    animation-duration: 0.5s;
    -webkit-animation-delay: 2s;
    animation-delay: 2s;
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
    -webkit-animation-fill-mode: both;
    animation-fill-mode: both;
}

Keyframes unseen-fadeout-to-unread
0% {
    background-color: #dce8ff;
}

100% {
    background-color: #ffffff;
}
```

So maybe it's better to invert those two background colours. But I wasn't sure how to do that, so I just set the background the same as what Dark Reader made the other messages. It works well enough for me. I guess it might not match anymore if you change dynamic settings for brightness/contrast etc. to something other than the default.

I think really it's something to be fixed in the Dark Reader code, so that it correctly darkens an animated background according to its settings. I don't know if that's possible though.  It's hard to test because you only see it when someone sends you a new message.
