### ISSUE TITLE
not compliant with progressive web app ?

### ISSUE THREAD

**Issue by promeneur** [darkreader/darkreader#2178]
openSuse leap 15.1
Chrome 80.0.3987.149
Darkreader 4.9.2

With Chrome i set up duo.google.com as a progressive web app.

When launching this app with the desktop shortcut created by Chrome
then
dark theme is not applied.

If i use F5 key to refresh the page then dark theme is applied.

**Comment by Gusted** [comment]
Apps are protected pages by Chrome therefore Darkreader will not dark it

**Comment by promeneur** [comment]
How do you explain that dark reader works well after launching web app if use F5 to refresh ?

How do you explain it works well with other progressive web apps built with
keep.google.com
messages.google.com
web.skype.com
twitter.com
web.whatsapp.com
groups.google.com
etc. ?

**Comment by Gusted** [comment]
Could you provide a screenshot?

**Comment by promeneur** [comment]
![darkreader_dmstwg](https://user-images.githubusercontent.com/240424/77670021-e87c1180-6f85-11ea-875d-f0a42954902d.png)

for "messages" and "skype" it is not a proof because they get their own dark theme but for the others it's a proof the page is not blocked.

**Comment by Gusted** [comment]
Ah I get it now I will look into it.. A little misunderstanding

**Comment by Gusted** [comment]
I think this could be a browser bug as you said

> When launching this app with the desktop shortcut created by Chrome
> then
> dark theme is not applied.

When I open up dou as web app I'm just getting dark theme

**Comment by Gusted** [comment]
> If i use F5 key to refresh the page then dark theme is applied.

Seems like a browser bug to me

**Comment by matfantinel** [comment]
Seems like I'm getting a similar issue here...
I created Chromium apps for Google Keep and WhatsApp (two examples), and Dark Mode applies to them if selected manually, but the automatic change according to system theme doesn't work as it does on regular FF/Chromium pages here.

Could this be related or does it deserve its own issue?

**Comment by Gusted** [comment]
> Seems like I'm getting a similar issue here...
> I created Chromium apps for Google Keep and WhatsApp (two examples), and Dark Mode applies to them if selected manually, but the automatic change according to system theme doesn't work as it does on regular FF/Chromium pages here.
> 
> Could this be related or does it deserve its own issue?

 Hmm seems like something else create a seperate issue with more info.

**Comment by matfantinel** [comment]
@Gusted after a bit more testing, seems like that isn't working for Chromium overall, not just its apps.

Considering sites with native dark mode are not changing too, seems like a browser problem, because Firefox (main browser) works just fine.

**Comment by Gusted** [comment]
> @Gusted after a bit more testing, seems like that isn't working for Chromium overall, not just its apps.
> 
> Considering sites with native dark mode are not changing too, seems like a browser problem, because Firefox (main browser) works just fine.


Could you give some example of sites

**Comment by matfantinel** [comment]
@Gusted websites like blog.elementary.io and fantinel.dev automatically change to a dark background when the system is in dark mode, even with Dark Reader off.

I just meant that it seems that the browser is currently unable to read my system's theme, so it makes sense that Dark Reader can't automatically change either. Seems like a browser bug

**Comment by Gusted** [comment]
> @Gusted websites like blog.elementary.io and fantinel.dev automatically change to a dark background when the system is in dark mode, even with Dark Reader off.
> 
> I just meant that it seems that the browser is currently unable to read my system's theme, so it makes sense that Dark Reader can't automatically change either. Seems like a browser bug

Whats your OS

**Comment by matfantinel** [comment]
@Gusted Pop_OS 20.04, which is based on Ubuntu 20.04.

**Comment by Gusted** [comment]
> @Gusted Pop_OS 20.04, which is based on Ubuntu 20.04.

It could be an underlying bug in the OS with chromium as Firefox works.. I suggest opening an bug report

**Comment by promeneur** [comment]
Another info.

Since Google Groups progressive web is now first launched when opening a session, it encounters the same problem.

It seems that this problem occurs only with first app launched.

**Comment by Gusted** [comment]
> Another info.
> 
> Since Google Groups progressive web is now first launched when opening a session, it encounters the same problem.
> 
> It seems that this problem occurs only with first app launched.

That suggest a bug in their system...

**Comment by Yash-Singh1** [comment]
@Gusted This is not any bug inside the system. This is simply a feature inside the browser. If the application is type `fullscreen`, such as https://yash-singh1.github.io/Game/index.html, a little game that I made, the extension will not be displayed. This is because that display type is made for showing almost nothing to the user that identifies it as Chrome. Here is a little table from MDN:

Display Mode | Description | Fallback Display Mode
-- | -- | --
fullscreen | All of the available display area is used and no user agent chrome is shown. | standalone
standalone | The application will look and feel like a standalone application. This can include the application having a different window, its own icon in the application launcher, etc. In this mode, the user agent will exclude UI elements for controlling navigation, but can include other UI elements such as a status bar. | minimal-ui
minimal-ui | The application will look and feel like a standalone application, but will have a minimal set of UI elements for controlling navigation. The elements will vary by browser. | browser
browser | The application opens in a conventional browser tab or new window, depending on the browser and platform. This is the default. | (None)

On the other hand, the standalone display mode will display the Dark Reader Extension, this includes, sketchpad.io:
![Screenshot from 2020-09-27 14-09-39](https://user-images.githubusercontent.com/53054099/94375798-1c69f800-00cb-11eb-852a-f87ac8d99e9e.png)
As you can see on the top left, it says Google Chrome. On the other hand, the game:
![Screenshot from 2020-09-27 14-10-14](https://user-images.githubusercontent.com/53054099/94375823-39063000-00cb-11eb-90b6-2e9025605060.png)
It shows the name of the game in the top left. In `minimal-ui`:
![superPWA](https://superpwa.com/wp-content/uploads/2018/12/display-mode-minimal-ui.png)
Not all browser UI is used, but some is. That some includes extensions. The last mode is browser mode, where it launches in the browser. It is the default.

**Comment by Gusted** [comment]
The extension are included trough the 3 dots 
![](https://i.imgur.com/HqLZDDj.png)
