### ISSUE TITLE
Reasoning behind granting "Access [to my] data for all websites" 

### ISSUE THREAD

**Issue by JStrebeyko** [darkreader/darkreader#2217]
I love the plugin, it's elegant and cool - honestly, my number one plugin for FF and Chrome, so thank you all for the hard work you've put into this :pray:

Was trying to advertise it to some of my friends and it was pointed to me that it asks for permissions not at all related to its functioning, very abuse-prone. I read the [Privacy Policy](https://darkreader.org/privacy/) and know about the concerns about it being [contradictory](https://github.com/darkreader/darkreader/issues/1386#issue-457753496).

Is a potential functionality of client details reporting a reason enough to have all the sore-eyed people granting the highest level of clearance to a CSS altering plugin? It makes it very difficult to peer-suggest, and the plugin is the best! :beers: 

Best,
Kuba

**Comment by Gusted** [comment]
Hello Their!

I'm happy to explain this.
Well First of all You got a very good guess

> Is a potential functionality of client details reporting a reason enough to have all the sore-eyed people granting the highest level of clearance to a CSS altering plugin? It makes it very difficult to peer-suggest, and the plugin is the best! 🍻

So let's me explain it on higher level
we use in the manifest.json the permission `<all_urls>` It's replaced the `activeTab` permission but with a twist, because it's give you the [permissions of activeTab](https://developer.chrome.com/extensions/activeTab) and because of changes how activeTab should work many developers use now <all_urs> so it won't cause any errors with navigation tabs and that kind of issues and because it's would only trigger when you do a browseraction. If you navigate to another site it won't darken until you 

The following user gestures enable activeTab:

- Executing a browser action
- Executing a page action
- Executing a context menu item
- Executing a keyboard shortcut from the commands API
- Accepting a suggestion from the omnibox API


But for which function are we using this permission? and why it popups that warning. First of all after taking a good look that message is misleading for the functions it gives.

- Call tabs.executeScript or tabs.insertCSS on that tab.
- Get the URL, title, and favicon for that tab via an API that returns a tabs.Tab object (essentially, activeTab grants the tabs permission temporarily).
- Intercept network requests in the tab to the tab's main frame origin using the webRequest API. The extension temporarily gets host permissions for the tab's main frame origin.

And we use the `tabs.executeScript` to inject Styles without giving it on our backend the less issues and bugs that potentially could happen. 
`https://github.com/darkreader/darkreader/blob/master/src/background/tab-manager.ts#L82`

We use the URL to identify if it's in the Global Dark list or has CSS fixes in one of the generators config

I'm not sure if we use the last point, because before the DOMS load(Rendering how it's should look like) It's makes the background black, trying to prevent white flashes. But I'm not sure if we use that part for this or if you don't need it

If you need more info, I'm glad to explain.

Best,
Gusted
