### ISSUE TITLE
Improvement for input box of the Google Translate website.

### ISSUE THREAD

**Issue by HubKing** [darkreader/darkreader#2260]
It seems that the soft, shadowy edge of the translation input box is not inverted. So the outline of the input box is almost invisible. 
![image](https://user-images.githubusercontent.com/10900489/78977258-cd4afd80-7b52-11ea-8ad9-d725ce5c0f7e.png)

That is when the contrast settings is "off". Since I like completely black background, instead of grey, I use +50 contrast. That makes the outline invisible.
![image](https://user-images.githubusercontent.com/10900489/78977490-2d41a400-7b53-11ea-8aba-076dc0002385.png) (The bottom line is not from the input box, but from the word box which appears when a word is selected. When no word is selected, there is no visible border.)

This is not a showstopper, as I remember the position of the input box, but it would be nice if there is a border (invert the soft, shadowy edge), or the input box is slightly grey (different from the background colour).

**Comment by Gusted** [comment]
That's right that is contrast like you mentioned.

```
.source-wrap {
    background-color: rgb(0, 0, 0);
}
```
That is the CSS of the input box with contrast +50. The background goes fully black and the left and right borders are the same as the background color because their was never assigned to another color. the bordercolor you get with no contrast is because of some Box-Shadow that is around the box that make it looks like that color, but with contrast 50+ It is barely noticeable. Darkreader is doing it job like asked.
Asking for a border is a no-go that will simply add a new 'element' to the side that was never inteded by the Developers. I can try to make the box-shadow working but it will be just a fix that won't be globally added.

**Comment by Gusted** [comment]
Seems like the standard box shadow color is gray
```
.main-header {
    box-shadow: 0 1px 4px 0 rgba(0,0,0,0.37);
}
```
So it will be a wontfix probaly.

**Comment by Gusted** [comment]
Wontfix/can't fix - It contrast 50+ It won't even try to show grey when I tried to set it to it.
