### ISSUE TITLE
To work with Facebook's newly introduced Dark Mode

### ISSUE THREAD

**Issue by ballII** [darkreader/darkreader#2465]
**Is your feature request related to a problem? Please describe.**
![Screen Shot 2020-05-08 at 7 25 23 AM](https://user-images.githubusercontent.com/7100993/81354188-8b838780-90fd-11ea-9ac4-ba148d250ad7.png)
I choose Facebook's built-in Dark Mode, and use Dark Reader's Light mode to enhance its contrast. Then the flashes of white backgrounds appear frequently when I scroll the webpage fast enough or when I click Home of Facebook. These white flashes seldom appear if I turn off Dear Reader, probably due to a faster loading speed without Dark Reader.

**Describe the solution you'd like**
To use built-in dark modes of certain websites, can Dark Reader provide a mode in which colors are "not" inverted (but can be enhanced), but the white flashes can be prevented? Thank you.

**Comment by devanshuDesai** [comment]
With due respect, I don't see the point of keeping darkreader enabled on a website where the frontend engineers have already put in a lot of work to provide a native dark mode. You can try tweaking the brightness and contrast settings manually to achieve the enhancement effect you desire. Don't see why this should be implemented on the master branch.

**Comment by Gusted** [comment]
@Myshor :)

**Comment by alexanderby** [comment]
Hi, until we fix it for the new Facebook design, I suggest you to use Filter mode along with Light mode to reduce the brightness of the web page.

**Comment by Myshor** [comment]
Well... I can only say that new design is very (how to name it delicate) hard to touch.
Now the fixes are done to force dark filtering when using dark reader in both Facebook modes.

Problem with flashing comes out because when you use light mode in DarkReader it tries to render page with white background then my fixes switch it back to dark.
My bad... I wasn't even check how it will work with light mode in Dark Reader. I just use dark or disable DR completely for the site if I want to have original styles.

Keep in mind that even when using light mode all Dynamic filtering fixes is processing and that makes the problem.

One solution for this I have in my mind is to disable whole filtering from config files when light mode in Dark Reader is enabled.

@alexanderby just confirm I got it right. I could mess something how exactly Light mode in Dark Reader works.

**Comment by alexanderby** [comment]
Unfortunately until the new Facebook design is shipped to me I cannot suggest anything. We will seek for a solution, which requires as less configuration as possible.

**Comment by Gusted** [comment]
Hi @ballII,

Can you check with the newest released version of dark reader 4.9.9/4.9.10 If this mostly has been fixed?

**Comment by ballII** [comment]
Hi @Gusted,

Sorry, but with the Light mode in Version 4.9.9, I still see white flashes when I quickly scroll the page down or click a new page. (If I turn off New Facebook's native Dark Mode and use Dark Reader's Dark mode instead, there are no white flashes.)

**Comment by Gusted** [comment]
Weird behaviour than I don't recommend to use the native Dark Mode to be enabled.

**Comment by Gusted** [comment]
Many many fixed by @Myshor I think it's good for now. However if you find any issues don't hesitate to report them!

Regards,
Gusted
