### ISSUE TITLE
In Firefox, Filter mode causes standalone images to render halfway up the viewport

### ISSUE THREAD

**Issue by ivan** [darkreader/darkreader#2541]
**Describe the bug**

Thank you for the very good extension.

I have noticed that in Firefox, Filter mode causes standalone images to render halfway up the viewport.

**To Reproduce**
> Install Dark Reader in Firefox
> Set Dark Reader to use mode Filter
> Go to https://old.reddit.com/r/aww/comments/glrkuh/thats_my_mama/
> Click on the cat photo
> Observe photo rendering halfway up the viewport
> Reload to see it render correctly

This should reproduce, I have tested it in a fresh Windows 10 VM and Firefox profile.

**Expected behavior**
Rendering within the viewport :-)

**Screenshots**
![cat Annotation 2020-05-18 055034](https://user-images.githubusercontent.com/4458/82178473-95f70b80-98cb-11ea-9ed7-de5949793a34.png)

**System Information:**
 - OS: Windows 10 1909
 - Browser: Firefox
 - Version: tested 76.0.1 and 77.0b7

**Additional context**
This does not happen in Chrome/new Edge.

**Comment by Gusted** [comment]
After having a look, it's looks like this is not right an can be related to a browser bug.

**Comment by curbengh** [comment]
This issue has been going on for a while https://github.com/darkreader/darkreader/issues/1142

**Comment by epakai** [comment]
This isn't limited to standalone images. I also see it with ebay's pop-over (such as when viewing tracking on an item.

Removing the html { -webkit-filter: ...; filter: ...; } is enough to revert the positioning, but obviously this ruins filter and filter+ modes.

There's some more info that I think is relevant in this [stackoverflow question](https://stackoverflow.com/questions/52937708/css-filter-on-parent-breaks-child-positioning?noredirect=1&lq=1). To me it seems that since Dark Reader is applying filter on the root element then by the spec the browser shouldn't be creating any containing block that would affect child positions. This may be a browser bug, but this is not my expertise.

One workaround I found in this [stackoverflow question](https://stackoverflow.com/questions/37949942/firefox-position-bug-by-parent-with-filter) is to just set html {height: 100%;} alongside the filter settings.

**Comment by Gusted** [comment]
Unfortunate height: 100% Will scale up images

**Comment by curbengh** [comment]
Add this to Dev Tools, just before the first `======`:

``` css
@media not print {
  img {
    bottom: auto;
  }
}
```

It's not persistent over addon update though.

**Comment by Gusted** [comment]
🤷🏽‍♀️ Let's hope Firefox does something about it 
https://bugzilla.mozilla.org/show_bug.cgi?id=1654504

**Comment by Gusted** [comment]
Dup of #1142
