### ISSUE TITLE
[Feature Request] Add support for Safari using new Web Extension APIs

### ISSUE THREAD

**Issue by tzm41** [darkreader/darkreader#2927]
**Is your feature request related to a problem? Please describe.**
Currently the Safari version of Dark Reader seems to be far behind the version of other browsers, thanks to Safari's limited extension APIs which required extra work.

**Describe the solution you'd like**
With the new Web Extension APIs announced at this year's WWDC, it might make sense to provide up-to-date version of the extension using the new APIs.

**Comment by Gusted** [comment]
Yes we are planned to support it.

**Comment by tzm41** [comment]
Great! Good to hear.

**Comment by sn0wyfall** [comment]
@Gusted That's awesome to hear, thank you! If you don't mind my asking, do you have any idea what features are planned to be supported? I was sad that there were a couple of features in Dark Reader for Safari that seemed behind from Chrome's extension:

1. There is no ability to schedule a dark mode by time (I always use the system dark mode but only want to use Dark Reader at night)
2. The layout of Dark Reader seems a bit less advanced. For example, when you click on the icon you get global rather than site-specific settings, unlike in the Chrome version, which means you also don't have grayscale and sepia options. It would be amazing to have site-specific settings there directly. 
3. Enabling and disabling the extension seems a bit buggy—sometimes when disabling it websites momentarily flash dark. It's not that big of a deal though. 

I was really hoping that Dark Reader could be ported much more easily with the new Safari APIs, although I'm not a developer and don't understand how that works. But your comment gives me much hope, and I would love to hear what plans there are or if there's any roadmap for Safari. 

I am assuming you're one of the contributors, and so once again thank you for your work. Dark Reader is amazing and I honestly can't believe such an extension exists that works so well! You people are amazing.

**Comment by Gusted** [comment]
The current version is made in x Code and closed source, my best guess is to detect safari browser and just test it and and than see if any problems shows up and fix them. Aka we port the open source extension of this to safari codebase that way it will have the same features :D  that's right I'm a maintainer or however you want to call me. The owner of dark reader wrote the safari code and majority of current codebase. I also saw nog so hoping news in their documentation about some features that won't be or are not yet supported so we will see but it will have definitely more options and reliability :D not sure if it's official to download safari to a windows machine else I  would start right away.

**Comment by sn0wyfall** [comment]
Awesome! I understand, thank you for taking the time to reply! I greatly appreciate it. I can't wait for what you people have planned in the future :D

**Comment by cariacou** [comment]
any news on this?

**Comment by Gusted** [comment]
> any news on this?

Their is work in progress for this and some testing has been done. Some functionality like MediaQuery is different has been fixed for now in the code https://github.com/darkreader/darkreader/commit/9f386ea4c2100ddcac9cfe7a75825d28712133dd. I think I might be able to get MacOs running as well and test Dark Reader's current code against the newest Safari.

Regards,
Gusted

**Comment by sn0wyfall** [comment]
Can't wait! Really looking forward to this :)

**Comment by sn0wyfall** [comment]
Any news so far, or anything I can do to help? I would be happy to test a beta version and report bugs :)

**Comment by serovar** [comment]
Any news?

**Comment by lesterlo** [comment]
If the new web extension is done, we can use the dark reader on iOS 15. 💯

**Comment by alexanderby** [comment]
It's a bit different, but yes, good news.

**Comment by sagz** [comment]
Considering that the Mac App Store's Dark Reader extension is listed for $5 (in the US store), and assuming similar pricing strategy continues for iOS/iPadOS, this feels like a good thing to prioritize from a Dark Reader sustainability perspective. iOS users will likely get the paid extension. It's also squarely in the FOSS ethos to have products be Free as in Freedom (and not Free as in Beer)

**Comment by sohansubhash** [comment]
When is Safari going to get feature parity with Chrome and Firefox? It's almost been two years since Safari gained webextension support.

I'm happy to support Dark Reader. But I find it quite frustrating that the **paid** Safari version is the buggiest and most stripped down.

At the very least, could we get a roadmap for when Safari will get essential features like setting's export and Filter+?

**Comment by Gusted** [comment]
CC @alexanderby (he maintains the Safari version).

**Comment by alexanderby** [comment]
Hi @sohansubhash! Sorry for the delay with the release. The Safari version has become an opportunity to experiment with the user interface, review the new available APIs and remove the clutter we have in our Chrome/Firefox version, which appeared due to my poor knowledge and bad technical decisions many years ago. This work will benefit the whole project.

Unfortunately I had to change countries twice during these 2 years, and lost a huge amount of time as a result. The good news is the work is actively going on. Let's hope it will be done by the end of June. One technical problem is moving the settings from the old Safari extension to the new one (due to bad technical decisions by me, and by Apple to be honest). If users will be fine to loose their old settings, the release will happen sooner.

**Comment by alexanderby** [comment]
It's got a little bit delayed. Currently I'm polishing the UI and should test the settings transfer well. Should be finished the next week.
