### ISSUE TITLE
Toggling dark mode opens ad window and stuff. 

### ISSUE THREAD

**Issue by AKasera** [darkreader/darkreader#3114]
Whenever I toggled between dark mode and light mode, I would often get a new tab or window opened up with some type of ad. The ads were most always for express-vpn but also had other ads. I know that what I installed is from official channels because I have used the link posted by you guys in this GitHub and have even verified the ID of the extension. I am using the normal Opera Browser (not GX) if that helps at all. This isn't the first time I've had this issue but there are a few sites these days that I need to toggle between so its kind of annoying.

**Comment by alexanderby** [comment]
Can you make a screen recording?

**Comment by Gusted** [comment]
We actually had a similair issue a while ago with ads #2694

**Comment by alexanderby** [comment]
Even if it is a malware, please, don't remove it immediately. Locate your user profile folder, extensions, pack your Dark Reader extension folder into a ZIP file and share here.

**Comment by AKasera** [comment]
So currently I found a temporary solution. Which was toggling on and off dark mode so often that the ad pop ups just stopped. If it happens again, I will send a screen recording. Also I checked out that previous post and attempted the solution from there but it did not work.

**Comment by alexanderby** [comment]
[Here](https://www.howtogeek.com/255653/how-to-find-your-chrome-profile-folder-on-windows-mac-and-linux/) you can find out how to locate your profile folder. `Extensions` folder contains the extensions. Find one with `eima...` ID (if you have one with this ID).

**Comment by AKasera** [comment]
I have it. ID also matches what you guys say it should match

**Comment by alexanderby** [comment]
Anyway pack it into a ZIP, I will check the files

**Comment by AKasera** [comment]
[eimadpbcbfnmbkopoojfekhnkhdbieeh.zip](https://github.com/darkreader/darkreader/files/4919775/eimadpbcbfnmbkopoojfekhnkhdbieeh.zip)

**Comment by Gusted** [comment]
Does your UI looks like ![](https://i.imgur.com/MWGkwTJ.png) ?

**Comment by AKasera** [comment]
![image](https://user-images.githubusercontent.com/15956410/87449542-5008ac00-c5cb-11ea-8255-0f89e09d8248.png)

**Comment by Gusted** [comment]
[diff.log](https://github.com/darkreader/darkreader/files/4919923/diff.log)
This the differences between the compiled build version of 4.9.13 and your. It just some tabs and the manifest.json. But I don't see any malware nor any ads. It should rely on a different factor do you have any other extension?

**Comment by AKasera** [comment]
Yes, I have Adblocker Plus, Netflix Party and 8K for YouTube. And of course the install any chrome extension for opera

**Comment by Gusted** [comment]
Okay could try try to disable the extension 1 for 1 while trying to recreate the ad pop-up.

**Comment by AKasera** [comment]
So the ad pop up thing sort of stopped after I toggled it over and over until I guess it got tired of loading ads. So when it starts to happen again, i'll try this and see if it works or not

**Comment by starkexpo42** [comment]
Now I'm using Dark reader at least everything is well but with some website it's black all the element of the selected website. 
do something with this bug.

**Comment by Gusted** [comment]
1. Why posting on this bug.
2. Open up a new issue for this with the good information.
3. `do something with this bug.` This comes passive aggresive over.

**Comment by starkexpo42** [comment]
Hey I'm learner. If I do something wrong I'm sorry.

**Comment by matthewperrin** [comment]
A couple of weeks ago I experienced the same behaviour and as a result, I reinstalled my operating system entirely.

Since then I have been very careful to sandbox everything.

However today, after installing this extension, I noticed this exact same behaviour (it was opening urls to investingalerts.pro) when accessing en.wikipedia.org and reddit.com.

I think someone has potentially compromised an asset or the plugin directly and you might want to investigate this further.

**Comment by Gusted** [comment]
Run a scan of malwarebytes and see if 8t finds anything other than that I didn't saw the previous time anything suspicious into your installed dark reader.

**Comment by matthewperrin** [comment]
> Run a scan of malwarebytes and see if 8t finds anything other than that I didn't saw the previous time anything suspicious into your installed dark reader.

lol I just explained this is a fresh install of windows and it was made using an oem installation media (not writable)

however it may pleasure you to know that before the re-installation last time I did decide to download and run _malwarebytes_ (this is something I do not enjoy doing, as it clutters the system immensely) and it returned no results

I'm not pointing fingers at this chrome extension but since removing it, it has stopped redirecting me to ads

perhaps a small step could be taken to stop relying on so much cdn based content in the package

**Comment by Gusted** [comment]
Define CDN based content.

**Comment by matthewperrin** [comment]
> Define CDN based content.

there seems to be uris to external (not _githubusercontent_ or _github_ and in this repo) resources

![image](https://user-images.githubusercontent.com/5142957/88280927-deeb9600-cd3a-11ea-89b5-1ab0d538f1b6.png)

and they are in a lot of locations, _svg_s are a prime suspect

**Comment by Gusted** [comment]
...
Look how the file is named its for fixes of certain sites you can read how it works in README.md they are CSS selectors not code that can do any harm at all.

**Comment by Gusted** [comment]
btw next time if you get a popup could you make a screenshot of it?

**Comment by matthewperrin** [comment]
> btw next time if you get a popup could you make a screenshot of your screen?

yes, I've actually been trying to record network traffic (and use shadowplay but that only captures the middle monitor) when it happens but it gets annoying pressing f12 for every tab I have open, I have hundreds of the things and it gets pretty monotonous so I was considering moving to winpcap or similar until the next one shows up

to describe the behaviour - I type the characters, `en.wikipedia.org` and the resource acquisition indication in the bottom left does not appear to mention `en.wikipedia.org` and instead an advertising site `https://investingalerts.pro/nz/benett/index.htm?uclick=3va8dv6o&uclickhash=3va8dv6o-3va8dv6o-hebl-0-u3bl-2tg5-2t9r-697785` showed up rather rapidly - this contains some information that I can't be sure of the origin of since I wasn't able to capture a 301, 302, etc - note that it has geolocated me to nz which is accurate - also note that if I go to the address bar and `^z` on it that it correctly returns to `en.wikipedia.org` and if I then navigate to it (by pressing enter) the correct website loads indicating that I did not mis-type it

I haven't also been able to capture any interesting dns information regarding it meaning I didn't get the impression it was a dns spoofing attack locally

**Comment by Gusted** [comment]
DNS cache poising? It's not that common around these days their are far more intrested techniques. But if it is the case you could try setting your dns to Cloudflare or Quad9 or another public DNS.

**Comment by alexanderby** [comment]
Please share a screen recording, your browser version and the list of all installed extensions.

**Comment by matthewperrin** [comment]
I haven't had the problem since removing the plugin and don't really want to reinstall it.

**Comment by Gusted** [comment]
Your choice, but just remember the installed dark reader didn't contain malware at all.

**Comment by AKasera** [comment]
https://drive.google.com/file/d/1iluzhGmwcnJLpG6SVNSsQdxccHz-GSE2/view?usp=sharing

**Comment by AKasera** [comment]
Sorry, you guys closed this but you did ask for a screenshot/vid thing and this is one when it started acting up again
