### ISSUE TITLE
Evaluating Dark Reader for use in Tor Browser

### ISSUE THREAD

**Issue by Tarzan5** [darkreader/darkreader#3274]
Dear developers,
Thank you for your work on this extension. I'm currently evaluating this extension for use in the Tor Browser with Javascript disabled. Tor Browser Bundle (TBB) is basically Firefox ESR tailored for anonymity. I had some questions:

1. With and without Dark Reader, is there a difference in what content is loaded from a website or the order it is loaded in? Or does Dark Reader only work once content has been rendered by the browser, and does not alter the web traffic itself? 

    For example, if Dark Reader alters the setting for `prefers-color-scheme` to "dark", then it might cause a different CSS file to be loaded, which can be used as one more data point to fingerprint the user. I believe this feature is planned. Can it be made optional?

    This is also why TBB devs don't include uBlock, because different users will block different things, and the difference in web traffic patterns can distinguish them from each other.

2. Dark Reader shouldn't need internet access for its functionality. Does it make network connections in the background? If so, can this be made optional? The concern of TBB devs with such extensions is that they might bypass the Tor Proxy, and communicate over clearnet.

3. My understanding is that Dark Reader inserts its own CSS in `<head>`, and makes no other changes to the page. Is this correct?

4. If I don't choose to modify settings per website, what data is logged to disk? The concern TBB devs have here is forensics (where information about which websites a user uses or visits, is written to the disk). 

Thanks!

**Comment by Gusted** [comment]
Hi their!

> Javascript disabled.

Just for webpages right, extension still have javascript access?

1. Every background-image that is avaible in CSS is being fetched trough https://github.com/darkreader/darkreader/blob/master/src/utils/network.ts#L3(and other things are being used in it) we are forced to do this due browsers giving limitation on what we can do. So if a background-image is not being used we still fetch it and make a CSS rule for it so if a image changes(e.g. another class) and use the Background-image we already have it modified in order to not create flashes for it.
`prefers-color-scheme` Uhm I've seen so many people misunderstanding the media query. It's just a fetch from the system if the user has a LIGHT scheme or DARK scheme [for example in Windows](https://i.imgur.com/zniEbZT.png) We just receives it and does anything with it if [the user has automation for System color enabled](https://darkreader.org/blog/automation/) For the rest we don't alter it or anything else. However I'm thinking because of certain situations we might get a check in place to just fetch background-images that's being used(as some sites load thousand of little icons and slows down Dark Reader).

2. Standard settings -> Just to save user settings to the sync API but not sure if TBB Blocks this else just to local. We need to fetch certain things because their's no way how else to get certain objects. Tor Proxy? If TBB just relay the fetch function trough the proxy their shouldn't be any bypasses from our site.
3. Our `static CSS` is being loaded in head we also make a instance marker to let know dark reader is already in use because of some issues if the webAPI of dark reader is running on a site, it will conflict. [the code](https://github.com/darkreader/darkreader/blob/master/src/inject/dynamic-theme/index.ts#L378) And every stylesheet so a <style> a <style class="darkreader--sync"></style> will be created with the modified CSS for the Style above it.
4. N o t h i ng. So long you don't modify any setting so what ever. Than [this](https://github.com/darkreader/darkreader/blob/master/src/defaults.ts) is being saved to disk/sync(standard both for a failsafe when network is unreachable).

If their is somehow a option to let extension knows TOR is running I'm more than happy to modify our code to disable certain features and maybe use less fingerprinting :) 

Regards,
Gusted.

**Comment by sprinkledcheese** [comment]
Sites can detect that you have dark reader installed. Doesn't matter whether you use it or not. So it's advisable to not use dark reader in Tor browser.

**Comment by Tarzan5** [comment]
@sprinkledcheese Even if Javascript is turned off (through Firefox pref `Javascript.enabled`)? Could you explain more? Thanks. For the case where Dark Reader is turned on, I can understand why it can be detected (because it pre-fetches background images, based on above comment).

@Gusted Thank you for the explanation.

**Comment by Gusted** [comment]
> Even if Javascript is turned off

Pretty sure extension will still work as it's all based on javascript.



> Could you explain more?

We need to insert styles into the webpage and that can be detected trough a site.



> web traffic patterns

Yep if a programs outside of a site as they haven't access to that. Could detect the extra fetch.

**Comment by sprinkledcheese** [comment]
I'm not sure about js pref in ff, but Tor recommends this: https://2019.www.torproject.org/docs/faq.html.en#TBBOtherExtensions.
