### ISSUE TITLE
[BUG] Dynamic mode - scrollbar line up/down buttons missing

### ISSUE THREAD

**Issue by kubalav** [darkreader/darkreader#3338]
Every mode have line up/down button, but dynamic not. It is bug for me, but it can be feature for someone else.
How can I add those missing parts to scollbar?

**Comment by Gusted** [comment]
Hi @kubalav 

This was intended behaviour and not rather a bug(unintended behaviour).
I think it's better to get a custom Style like [this](https://pastebin.com/xufdscGT) one and install it trough something like Stylus. Make sure you have `(https?|file)://.*` in the applies to section. 

As back to the intended behaviour, after tests with the up/down button. It didn't look good and Firefox was having some issues with it. That's why I think this was simply just overriden by 1 dark bar.

Regards,
Gusted
