### ISSUE TITLE
[Feature Request] Change color of svg icons

### ISSUE THREAD

**Issue by jascodes** [darkreader/darkreader#3340]
I think if you are able to detect svg has single color. Perhaps you can invert it?

**Comment by jascodes** [comment]
Attaching and example; Check out below connect with me.

![image](https://user-images.githubusercontent.com/1231593/89314155-ed20a700-d696-11ea-8c89-303cd33d9795.png)

**Comment by Gusted** [comment]
Hi @jascodes!

Github loads them as `img` element and due to performance and logic issues we don't touch them to analyze it, something on the other hand we do with SVG's already do to modify the color to a white-ish one. For this kind of images we have the `INVERT` section in devtools to invert the colors and in this example make them white. You can read more about it in [the README.md](https://github.com/darkreader/darkreader/blob/master/README.md#use-dev-tools).

Regards,
Gusted
