### ISSUE TITLE
gmail.com multiple accounts with different themes

### ISSUE THREAD

**Issue by leodoi3** [darkreader/darkreader#3366]
**Is your feature request related to a problem? Please describe.**
Different inbox themes under Gmail

**Describe the solution you'd like**
I've got different gmail accounts and each of them has a different theme.  One of them uses a light inbox , the other is a dark inbox. I would like it to tell which account I'm using so it automatically enables DarkReader. 

**Additional context**
Adding it to whitelist would not disable it for that Gmail account only.

**Comment by Gusted** [comment]
Hi @leodoi3!

In the URL you can see which user is active.
Example:
`https://mail.google.com/mail/u/0/`
This means I'm on the default/primary account due to the `0` number in the URL.
You can manually add these URLs with it's corresponding number to the site-list in order to not style them.

Regards,
Gusted
