### ISSUE TITLE
[Broken Website] Capitalone.com

### ISSUE THREAD

**Issue by ACodingGenie** [darkreader/darkreader#3516]
**Website**
https://www.capitalone.com/

**How to Reproduce**
> 1. Go to https://www.capitalone.com/
> 2. Make sure "Dynamic" filtering is enabled in Dark Reader under "more" tab.
> 3. Toggle Dark Reader to "off" and take note of all the background images on the webpage.
> 4. Toggle Dark Reader back on. 
> 5. Notice how all background images are covered in black. 

**Expected behavior**
All the background images should not be replaced with a dark background and they should be visible with the dynamic theme on. 

**Actual behavior**
Background images are replaced with a dark color / blocked or not visible to the user.

**System info:**
 - OS: Windows 10 Version 2004 (OS Build 19041.450)
 - Browser: Brave Browser: Version 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
 - Dark Reader Version: 4.9.16

**Comment by Gusted** [comment]
Unfortunate, because of the way how we inject our Styles and they have their CSS selectors(Some obsolete way) I'm not able to make a fix for this site as they place some the style with all images before the element, but we have a own element next to it that actually now receives the images. I recommend using Filter/Static for this site as it's fixing all images will take too much code in the devtools.

Regards,
Gusted
