### ISSUE TITLE
[Feature Request] Use WeData for Storage and Submission of Site Rules

### ISSUE THREAD

**Issue by kimpurcell** [darkreader/darkreader#3555]
**Is your feature request related to a problem? Please describe.**
Whenever I need to contribute a new rule to DarkReader, I need to submit a pull request and do a merge. This is inefficient and slow. 

**Describe the solution you'd like**
DarkReader can benefit from using a social contributor powered database that anyone can easily contribute to.

The Japanese figured it out with a system called WeData, used by the popular chrome extension AutoPagerize.

Here's the whitepaper on it:
https://www.opensym.org/ws2012/wikisym12submission53.pdf

**Additional context**
Caveat: I'm still trying to figure out how to submit entries into WeData though. I can't read Japanese and a user friendly documentation does not exist! (or I can't find it because I can't read Japanese. ):-(

**Comment by Gusted** [comment]
> Whenever I need to contribute a new rule to DarkReader, I need to submit a pull request and do a merge.

Well, this is the workflow of any Version Control system.

>This is inefficient and slow.

Yes but it's manage-able and won't be 1 big mess.

Well, after reading the white-paper I get a similar idea with [Sponser's block crowdsourced database](https://github.com/ajayyy/SponsorBlock). This means some things, first somehow we now need a separate server to host the .config file on and a .php to receive `POST` requests to add CSS Rules. Problem with that it means everyone can submit this and will be added instant, as the user base who actually contributes to the `.config` is small, a `vote` system is not going to work as well.
Also as you say it's inefficient this means the current implementation needs also a rewrite in order to make it work with a submit button and logic. 


Second trollers, Well as will be possible to let everyone submit and as their can be hardly a voting system(as majority users don't need this and will be confused if they get a pop-up to ask if this is a correct CSS). A simply 
```CSS
* {
     background-color: pink !important;
     color: pink !important;
}
```
Can be added to sites which in order will break the site of course.

I'm seeing too much trouble and work and time to implement this idea, as once again maybe 1% of the users uses the Dev tools and even a smaller group is willing to contribute.

Regards,
Gusted

**Comment by kimpurcell** [comment]
Didn’t think about the trollers.

**Comment by kimpurcell** [comment]
Thanks!
