### ISSUE TITLE
Lighter custom settings and dark flashes

### ISSUE THREAD

**Issue by az456123** [darkreader/darkreader#3608]
Hi,

Since a day I think, the addon loading seems slower and it has some weird effect at page load, the time to switch from default light/contrast to my custom settings (+30/-50) I suppose. I have these dark flashes (dark to lighter) almost each time I load a page now, even on sites where I disabled it.

Am I the only one to encounter this? It's maybe linked to something else on my side.
I'm using this addon for years and it's awesome, keep the good work.

**Comment by az456123** [comment]
See attached short video.
It wasn't doing it before.
It does it also when I open a new tab on a blank page.

[darkreader.zip](https://github.com/darkreader/darkreader/files/5185464/darkreader.zip)

**Comment by Gusted** [comment]
Hi @az456123!

We have made some changes to the order of execution and to prevent white flashes, we now are executing a hard coded style into the DOM what you notice as a `slow loading` due it's a hard coded style and nothing is being accounted for your settings/preferences. It doesn't actually slower load, but due to your custom settings which makes it notice-able it could be experienced as slower loading.

Regards,
Gusted

**Comment by az456123** [comment]
I see, thanks for your clear reply!
But, would it be possible to make it optional in the future?
As you can see in the video, the user experience isn't the best with lighter custom settings like mine, and these "dark flashes".

**Comment by Gusted** [comment]
> But, would it be possible to make it optional in the future?

Nope.

> Or, use also custom settings into the DOM instead of hard coded dark style? Easy to say I guess :(

Performance overhead.

**Comment by az456123** [comment]
If it's ok for you to have these ugly dark flashes now, I won't push :/
Good work so far though.
