### ISSUE TITLE
[Broken Website] moodle.herzen.spb.ru

### ISSUE THREAD

**Issue by Rakleed** [darkreader/darkreader#3623]
**Website**
https://moodle.herzen.spb.ru/

**How to Reproduce**
1. Go to https://moodle.herzen.spb.ru/ or https://moodle.herzen.spb.ru/course/index.php site.

**Expected behavior**
The background is dark and the text is light.

**Actual behavior**
Somewhere the background is dark, and somewhere light. The problem is the same with the text. And somewhere, both the color and the text are about the same color, which makes the content on the site unreadable.

**Screenshots**
<details>
<summary>Details</summary>

![screenshot-moodle herzen spb ru-2020 09 10-16_33_02](https://user-images.githubusercontent.com/19418601/92736961-65a81100-f383-11ea-9583-823e4057c34e.png)

![screenshot-moodle herzen spb ru-2020 09 10-16_33_34](https://user-images.githubusercontent.com/19418601/92736970-66d93e00-f383-11ea-9733-872b957396d3.png)

</details>

**System info:**
 - OS: Windows 10 v. 2004
 - Browser: Chrome 85
 - Darkreader Version: 4.9.19
 
**Additional context**
In 1 out of 10 cases, the site can load and display correctly, I don't know how to explain this. Removing the rule from the https://github.com/darkreader/darkreader/pull/1847 pull request did not help. This problem appeared sometime in late spring - early summer 2020, although everything worked correctly before that.

**Comment by Gusted** [comment]
Hi @Rakleed!

Somehow chrome is blocking our request to get the CSS rules of certain elements in order to modify it. It even seems like a browser bug as it's not continues as a simple on/off get the correct site and Firefox have 0 problems with this. So far I can see we didn't change any code related to this behavior so it could be some server side or some new Chrome security policies like again.

Regards,
Gusted

**Comment by Gusted** [comment]
4.9.22 seems to resolve this issue else #4005 in 4.9.24 will do this.
