### ISSUE TITLE
https://groupme.com/signin | Memory Leak

### ISSUE THREAD

**Issue by alanbixby** [darkreader/darkreader#3626]
**Website**
https://web.groupme.com/signin
https://web.groupme.com/chats

**How to Reproduce**
Enabling DarkReader (in Dynamic Mode) on GroupMe causes an infinite increase in memory usage; this behavior is seen on both Firefox and Google Chrome. This _does not_ occur on the main landing page.

Google Chrome seemingly has protections halting tabs at ~4GB of RAM usage, while Firefox does not- causing the tab crash your machine from out of memory errors.

**Screenshots**
- [GroupMe tab using >24GB RAM.](https://i.gyazo.com/b4af4e47f1fc5693a40abda83de6c08d.gif)
- [Google Chrome's dev-console error.](https://i.gyazo.com/1745c752250c95f75958adc9be4dbd4c.png)

**System Info:**
 - OS: Windows 10 Pro : Version 2004, Build 19041.508
 - Browser: Firefox 80.0.1 (64-bit); Chrome 85.0.4183.102 (64-bit)
 - Dark Reader Version: 4.9.19
 - System: Ryzen 7 2700, 32GB RAM (3000Mhz), GTX 980

**Additional Context:**
I have tested disabling all other extensions, which validates it is Dark Reader causing the memory leak.

**Comment by cjdm24** [comment]
I have the same issue as well as another friend of mine. Hope this gets fixed soon!

**Comment by saspelund** [comment]
Same. Closing groupme immediately causes RAM usage to plummet. I then reopened groupme which cause the ram usage to start spiking. I then disabled darkreader for groupme and refreshed groupme (now blastingly white) which caused the ram usage to also plummet.

If other's find themselves here, does giving upvotes to the main post boost it up or is commenting the best way to show support?

**Comment by Gusted** [comment]
Hi everyone!

Sorry to hear you are experiencing this memory leak, fortunate I've found the problem and made a fix(#3635) for this.
In short terms what happen, You can import other files and due to our code base we like to replace it with the full CSS. However in this case in the imported file it had a import file reference to itself and that caused a infinite loop and the increasing memory usage(not actually a leak as a leak is that you still have memory that is not longer used still in memory, what wasn't this case).

Regards,
Gusted

**Comment by Gusted** [comment]
This is the memory usage with the fix 
![](https://i.imgur.com/sq77mIj.png)

**Comment by ei14** [comment]
Similar issue still occurs on Chromium, Linux. Instead of memory usage, the extension fails completely and must be restarted.
