### ISSUE TITLE
[BUG] PDF-Viewing in Chrome not darkened/darkened wrong

### ISSUE THREAD

**Issue by XilefTech** [darkreader/darkreader#3647]
### **Describe the bug**

The builtin Chrome-PDF-Viewer behaves weird with Darkreader.

When opening any online-PDF like [this one](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf), Darkreader makes the background appear brighter than it is without dark reader, which is contra-productive when trying to avoid all-white sites.
When opening PDFs from the local drive tho, Darkreader doesn't do anyting.

### **Steps to reproduce**

- Go to 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'
- look at the uglyness of the background
- try to open a PDF from your local disk in chrome
- see that you can see nothing

### **Expected behavior**

the background should remain as-is or made a little bit darker
And when opening local PDFs the same should happen as if it was a PDF from the internet

### **Actual behavior**

already described above

### **Screenshots**
with darkreader:
![image](https://user-images.githubusercontent.com/52332196/93245615-d7b99500-f78b-11ea-983c-409250e6fbe5.png)
without:
![image](https://user-images.githubusercontent.com/52332196/93245646-e30cc080-f78b-11ea-910a-229d0de4ccd4.png)

### **System Information:**
 - OS: Windows 10
 - Browser: Chrome 85.0.4183.102
 - Dark Reader version: 4.9.19

### **Additional context**
dunno what to put here

**Comment by Gusted** [comment]
Dup #3585

**Comment by B14CK313** [comment]
I noticed this issue myself and decided to look into it a bit. I unfortunately don't have the time to dive in the code and find out how this plugin works exactly, but i wanted to share my findings here, because I think they may be useful:
I copied the code from this answer on stackoverflow: https://stackoverflow.com/a/60996953/9458846
and just changed the background-color to '#555'. This darkens the whole page, but without inverting it. I think this leads to a much better experience than the default bright background. Maybe a similar approach could be used in the plugin.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```
