### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by esa1975** [darkreader/darkreader#3671]
**Is your feature request related to a problem? Please describe.**
Previous releases allowed for copying the entire list of sites. This was handy to find iterations of sites since DR tends to be a little specific at times and toggling the current site doesn't work because there is already an entry in the list (that's difficult to find).

**Describe the solution you'd like**
It would be nice to be able to still select all the sites in the list so I could edit them in a text editor. Alternatively, if there was a search feature that allowed me to find sites that would overcome this issue.

**Additional context**
If there was a way to get to the configuration file that holds the sites and I could edit that file manually then that would be an acceptable workaround.

**Comment by Gusted** [comment]
Hi @esa1975!

> If there was a way to get to the configuration file that holds the sites and I could edit that file manually then that would be an acceptable workaround.

I think this is the best option as having 1 big list was in our eyes a bit messy and that's why it was brought down to `individual sections`.

You can currently export the settings/configuration, by going into Settings -> Manage settings -> Export Settings.

Under the `siteList` option are all site's stored. The siteListEnabled is for sites that are in the global dark file and are manually enabled by the user. 

After you have modified the siteList you can import the settings trough Settings -> Manage settings -> Import Settings.

Regards,
Gusted

**Comment by rgtk** [comment]
On latest release Dark Reader 4.9.22, I cannot find Settings or Export @Gusted mentioned: not in built-in "Options", no appropriate button in Extension's UI. Am I missing something or the option disappeared?

I'm in between browser migration and, after using Dark Reader extensively for last couple of months, I have lots of rules and wouldn't like to do it by hand again :smile:

**Comment by GithubUser5462** [comment]
You have to enable the version 5 preview to access the new settings.

**Comment by rgtk** [comment]
> To activate the new user interface do the following:
>
> 1. Click Dark Reader icon.
> 2. Click Dev tools (in the bottom-right corner).
> 3. Click Preview new design.
>
> -- https://darkreader.org/blog/v4-9/
