### ISSUE TITLE
[BUG] Firefox for Android Drops frames when scrolling gfl.zzzzz.kr

### ISSUE THREAD

**Issue by yoasif** [darkreader/darkreader#3676]
From: https://www.reddit.com/r/firefox/comments/iwjh7u/frame_drops_when_scrolling_page_with_many_images/

### **Describe the bug**

User reports that Firefox for Android drops frames when scrolling on pages with many images.

### **Steps to reproduce**

- Go to https://gfl.zzzzz.kr/story.php?q=-33-40&lang=ko
- Scroll up and down

### **Expected behavior**

No frame drops.

### **Actual behavior**

Dropped frames. 

### **Screenshots**

Profile: https://share.firefox.dev/3iOpT35

### **System Information:**
 - OS: lineageos official 16.1
 - Browser: Firefox for Android Nightly
 - Dark Reader version: 4.9.19

### **Additional context**

User is on a LeEco Le 2 snapdragon version(codename s2)

WebRender did not help the issue for them, neither did enabling the warp interpreter in Firefox (`javascript.options.warp` set to true).

**Comment by Gusted** [comment]
Hi @yoasif!

Thanks for reporting this issue.

Unfortunately, I can't say much about this behavior other than all the code to load and initialize dark reader(Which seems a bit slow maybe time to go optimize mobile instead of desktop) is all happening before the the screenshots indicate it's scrolling and all the timestamps(Marker Table) is confirming this. The rendering itself is all Firefox Native code(Gecko) and the best option is have someone of Firefox Profiler team have a look at it to get the cause of this. If this leads back to dark reader somehow let me know and I will have another look with the additional info on it.

Regards,
Gusted
