### ISSUE TITLE
[Feature Request] Disable dark reader in all PDFs by default

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [darkreader/darkreader#3949]
Every single PDF I view in Chrome's PDF viewer turns dark and looks terrible. I want to disable this extension in all PDFs by default.

**Comment by Grelo4ka** [comment]
I agree; it would be great to see this enhancement in Dark Reader.

**Comment by Gusted** [comment]
Hi @asdsadsaasd12312132!

Unfortunate, everyone have their own opinion and from the past the open issues it looked like a lot of people like to have darkend PDF by default. You can of course override this behavior in the new UI.
-    Click Dark Reader icon.
-    Click Dev tools (in the bottom-right corner).
-    Click Preview new design.

Then 
- Click on Settings
- Click on Site List
- Disable PDF

Regards,
Gusted

**Comment by trebory6** [comment]
> Hi @asdsadsaasd12312132!
> 
> Unfortunate, everyone have their own opinion and from the past the open issues it looked like a lot of people like to have darkend PDF by default. You can of course override this behavior in the new UI.
> 
> * Click Dark Reader icon.
> * Click Dev tools (in the bottom-right corner).
> * Click Preview new design.
> 
> Then
> 
> * Click on Settings
> * Click on Site List
> * Disable PDF
> 
> Regards, Gusted

I'm sorry for necroposting, but your response really rubbed me the wrong way.

Because I can not sit here with a straight face think that people prefer [this](https://i.imgur.com/Gq90J8S.png)(PDFs with Dark Reader activated) over [this](https://i.imgur.com/9DITVzw.png)(PDFs with Dark Reader deactivated). And surely not enough people to be considered a majority to make this setting default. For Christ sake. 

Mainly because if you already have dark mode activated in the browser, it inverts the already dark mode of the PDF interface making it lighter!

Anyways, just my two cents. Getting sick of having to manually disable every single time I install Dark Reader on a new device.

**Comment by lance8765** [comment]
> Hi @asdsadsaasd12312132!
> 
> Unfortunate, everyone have their own opinion and from the past the open issues it looked like a lot of people like to have darkend PDF by default. You can of course override this behavior in the new UI.
> 
> * Click Dark Reader icon.
> * Click Dev tools (in the bottom-right corner).
> * Click Preview new design.
> 
> Then
> 
> * Click on Settings
> * Click on Site List
> * Disable PDF
> 
> Regards, Gusted

Disable PDF doesn't exist for me.
