### ISSUE TITLE
[Feature Request] "Night Vision" / "Dark room" mode

### ISSUE THREAD

**Issue by kosich** [darkreader/darkreader#4051]
**Is your feature request related to a problem? Please describe.**

While Dark mode is awesome for the evenings, for the night/bed reading it's still a bit too bright. Especially if we compare pitch black with grayish backgrounds on AMOLED (and similar) displays (modern phones use this type of matrixes and it's coming to laptops). And the white-on-dark text and borders are still quite bright.

**Describe the solution you'd like**

Some screen overlay applications provide a "Dark room" (Night Vision) mode — when we color everything with a `red ↔ black` gradient. The red color is the most tender to our eyes (that's why astronomic equipment is built with red-only displays). And the pitch-black background makes sense for modern-day displays to completely eliminate background light.

**Additional context**

Some screenshots of existing solutions:

[f.lux](https://justgetflux.com/) on MacOS:

<img height="200" alt="flux example" src="https://dukeofmedway.files.wordpress.com/2013/10/darkroommode.jpg" />

Windows 10 Night Vision Mode:

![windows 10 example](https://www.atm-workshop.com/assets/img/win10-red-mode-art.jpg)

source: https://www.atm-workshop.com/win10-red-mode.html

**P.S.**

Thanks for the extension! ❤️

**Comment by Gusted** [comment]
Hi @kosich!

I think this can be solved without adding such mode.
We have `Dynamic coloring` which in other words mean you can control Dark Reader to modify the colors to a specific 'color' and use it as reference.
To use this feature:

    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Then `under Theme click See all options, Colors.` you can tweak the background/text color to whatever you like and is best for the eyes. And make sure create a new `Theme/Preset` in order to switch to this style and then back to the default settings 
![image](https://user-images.githubusercontent.com/25481501/98304067-8a091e00-1fbf-11eb-83ec-87e6489d7f42.png)

Regards,
Gusted
