### ISSUE TITLE
[BUG] Colors from some selectors are applied when they shouldn't

### ISSUE THREAD

**Issue by everdimension** [darkreader/darkreader#4249]
Hi!

I'm using the npm version of the plugin and the dynamic mode.

### **Describe the bug**
When dark mode is enabled, for some elements their color changes to the color that is only supposed to be applied when they are in some state.

### **Steps to reproduce**
Example. Initial styles:

```
.decoration {
  border-color: grey;
}
input:checked + .decoration {
  border-color: blue;
}
```

So, if the input is not in a `:checked` state and we enable the darkreader plugin, I expect the decorator to stay grey.
But in fact it becomes blue. Both for when the input is checked and not.

### **System Information:**

- OS: macos 10.15.7
- Browser: tested in Chrome 86.0.4240.198 and Safari 14.0.1
- Dark Reader version: 4.9.22

---
Also I cannot find a way to somehow override this behavior. So please help me find a way how to that if it's possible.

**Comment by Gusted** [comment]
Hi @everdimension!

Are you sure that it's not because of some other CSS?
I've created an minimal test case with the CSS you provided.
[weow.zip](https://github.com/darkreader/darkreader/files/5585026/weow.zip)
And wasn't able to reproduce this behaviour

See as in my GIF, that it works perfect.
![Peek 2020-11-23 19-36](https://user-images.githubusercontent.com/25481501/100001351-543ba600-2dc3-11eb-8527-22c5037a8946.gif)

Regards,
Gusted
