### ISSUE TITLE
[Question] Best practices to make a website "Dark Reader compliant" ?

### ISSUE THREAD

**Issue by KaKi87** [darkreader/darkreader#4342]
Hello,

I'm building websites for companies and customers of all kind, and they're very rarely interested in implementing dark themes.

As sad as I feel about this, I was wondering if, at least, it would be possible to "optimize" it for Dark Reader, so it can be compatible with the default dynamic filter without additional patches required.

If there is no clear enough answer to that question, perhaps another way to ask would be : what are the most common issues that the dynamic filter cannot properly invert without fix by human intervention, in which case those should be avoided ?

Thanks

**Comment by alexandru** [comment]
For my own website, I have a background in light mode that doesn't look good in dark mode. Plus it was inverted by Dark Reader, and looked horrible.

So I added a small hack that detects Dark Reader in JavaScript, and adds a CSS class, which I can then use to disable the background:

```js
var isDarkReaderEnabled =
  "querySelector" in document &&
  !!document.querySelector("meta[name=darkreader]");

if (isDarkReaderEnabled)
  $("html").addClass("dark-reader");
```

Afterwards I can apply fixes meant for Dark Reader:

```css
html.dark-reader body {
  background-image: none;
}
```

After I did this hack, I realized that having an image with a white background wasn't ideal. So I converted the image to a PNG that uses transparency, and thus the color of the background then gets dictated by CSS, instead of the image. So as a "best practice", don't use images for styling, or when you do, make sure they look good with a dark theme.

**Comment by KaKi87** [comment]
> it doesn't work when you enable Dark Reader after the page was loaded

Regarding that matter, at least, I can help you :

```js
(new MutationObserver(() => document.body.classList.toggle('dark-reader', document.querySelector('meta[name="darkreader"]'))).observe(document.querySelector('head'), { childList: true }));
```

![](https://i.ibb.co/fHfX1MW/2020-12-01-15-14-51-min.gif)

Note that I added the `.dark-reader` class to `<body>` directly as targeting `<html>` is usually useless in CSS. ;)

**Comment by KaKi87** [comment]
> as a "best practice", don't use images for styling

Even without the Dark Reader context, this is an actually important recommandation. ^^

**Comment by Gusted** [comment]
Hi @KaKi87!

Thanks for asking this question and considering Dark Reader as dark mode implementation.
I will point some common fixes and `best practices`out in an non-logical order.

- One of the most inverted elements in the Dynamic theme fixes are logo's because they are black-ish and the background-color changes to a black-ish color it will be not visible to see. A good workaround for this is to use SVG's as logo so Dark Reader can override the `fill` attribute to a natural white-ish color and make it visible, loading SVG's where possible instead of a images is also a good practice in general for loading speeds.
- Dark Reader has improved greatly in detecting colors and elements and style them, however their are still exceptions. If a element has been left with the default colors that the browsers assign, Dark Reader will in some cases not style them right. A workaround for this is to have a simple CSS Rule to style it, even if it with the same colors as before. It will simple let Dark Reader know to style that rule as well.
- An rather uncommon issue are color pickers, they intend to use inline-styles and will be modified by Dark Reader. However you want color pickers to have it's original value. Unfortunate their is no workaround this other than passing an IGNORE INLINE STYLE setting into Dark Reader's API when the website enables Dark Reader with the proper CSS rule that matches the element that needs to have it's original color.
- Also in certain cases images are detected as white-ish and will be inverted when it's not needed also in this case an IGNORE IMAGE ANALYSIS setting has to be passed to Dark Reader's API with the exact CSS Selector that has this background-image.
- A still ongoing performance bug is that certain websites load's icons as Images regardless if they are going to be used, because we analyse Images you can imagine that having to analyse a thousand images is quite heavy and will endlessly load the website because of it.

Some specific one's to Dark Reader's API.
- iFrames will not be styled, because it's not possible to duplicate Dark Reader and insert it into the iFrame and have the proper enable/disable currently. A hacky workaround is to insert Dark Reader's source *locally or remote* into the iFrame and have a system that enables/disable Dark Reader's API when needed.
- Please don't use [closed shadowRoots](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot), *open shadowRoots are fine* Because javascript can't tell what's inside an **Closed** shadowRoot, it won't be styled as well. An workaround is just to use open Shadow roots.

This are some major points that I could quick come up with and should cover all `major` issues currently. You can close it if you like to if you don't have further questions. 

Regards,
Gusted

**Comment by KaKi87** [comment]
Thanks Gusted for your exhaustive answer.

One last thing : how does the Dark Reader API work ?

**Comment by sam1rm-hiretech** [comment]
@Gusted nice location on profile!  More so.. I bet with some effort one could find your location using this extension. They already have it. 

Would love an exhausted answer of some sort https://github.com/darkreader/darkreader/issues/4348.

**Comment by Gusted** [comment]
> One last thing : how does the Dark Reader API work ?

The same as the extension does, however it doesn't have the back-end infrastructure e.g. that handles when an settings changes in the UI that all the active instances update it's styles according to the new settings.
Some of the options can be seen in the example https://github.com/darkreader/darkreader#using-for-a-website however it's not really complete.

**Comment by Gusted** [comment]
> @Gusted nice location on profile!

I'd like to have such things as locations :D



> I bet with some effort one could find your location using this extension.

I don't use the location feature, as I like to have it always on and don't need to have it changes when sunrises/sunsets.

> They already have it.

What are you trying to indicate? And please define `they`.

**Comment by KaKi87** [comment]
So, the repository contains the JS library and the browser extension at the same time. Awesome xD

---

> Why?

`01000011 01110101 01110010 01101001 01101111 01110011 01101001 01110100 01111001 00100000 00111010 01110000`

> please define `they`.

I guess : GitHub.

**Comment by Gusted** [comment]
> So, the repository contains the JS library and the browser extension at the same time. Awesome xD
> 
> > Why?
> 
> `01000011 01110101 01110010 01101001 01101111 01110011 01101001 01110100 01111001 00100000 00111010 01110000`
> 
> > please define `they`.
> 
> I guess : GitHub.

Yep, the build scripts only compile the code that usually injects into the webpage and with a few changes it doesn't depend on a background script in fact using the API e.g. Enabling it can be considered the backend for it

**Comment by Gusted** [comment]
Well, never guessed I came back here.

- If for some reason your using the darkreader API and some of the styles/link elements aren't getting styled add the cross origin attribute. #4853

**Comment by milahu** [comment]
> Regarding that matter, at least, I can help you :
> 
> ```js
> (new MutationObserver(() => document.body.classList.toggle('dark-reader', document.querySelector('meta[name="darkreader"]'))).observe(document.querySelector('head'), { childList: true }));
> ```

nice! but a pure CSS solution would be even more nice, see #4494

**Comment by KaKi87** [comment]
What you call a *pure CSS* will be so only for you anyway, because Dark Reader will still use JS to add this attribute anyway. ;)

**Comment by milahu** [comment]
current version:

```js
(new MutationObserver(() => document.body.classList.toggle('dark-reader',
  document.querySelector('style#dark-reader-style') != null
)).observe(document.querySelector('head'), { childList: true }));
```

**Comment by milahu** [comment]
> a pure CSS solution would be even more nice, see #4494

was implemented in #4860

```html
<html>
  <head>
    <style>
      div.highlight {
        background-color: lightgreen;
      }
      /* darkreader darkmode */
      [data-darkreader-mode="dynamic"] div.highlight {
        background-color: darkgreen;
      }
    </style>
  </head>
  <body>
    <div class="highlight">highlight</div>
    <div>no highlight</div>
  </body>
</html>
```

**Comment by chelseaawrence** [comment]
ARE YOU A VICTIM OF INVESTMENT OR NFT SCAM? DO YOU WANT TO INVESTIGATE A CHEATING SPOUSE? DO YOU DESIRE CREDIT REPAIR (ALL BUREAUS)? SCHEDULE A MEETING WITH AN ETHICAL HACKER TO GET STARTED. JAMES is a private investigator and funds recovery genius. Who specialize in cases regarding HACKING, CRYPTOCURRENCY RECOVERIES, FAKE INVESTMENT SCHEMES. They are also experts in CREDIT REPAIR and also analyze what’s impacting your score. All software tools needed to execute RECOVERIES from start to finish are available in stock. Be ALERT to FALSE reviews and testimonies on the internet, Contact JAMESMCKAYWIZARD & team as soon as you can via the email address below jamesmckaywizard at gmail dot com or WhatsApp +31622647750.

**Comment by chelseaawrence** [comment]
ARE YOU A VICTIM OF INVESTMENT OR NFT SCAM? DO YOU WANT TO INVESTIGATE A CHEATING SPOUSE? DO YOU DESIRE CREDIT REPAIR (ALL BUREAUS)? SCHEDULE A MEETING WITH AN ETHICAL HACKER TO GET STARTED. JAMES is a private investigator and funds recovery genius. Who specialize in cases regarding HACKING, CRYPTOCURRENCY RECOVERIES, FAKE INVESTMENT SCHEMES. They are also experts in CREDIT REPAIR and also analyze what’s impacting your score. All software tools needed to execute RECOVERIES from start to finish are available in stock. Be ALERT to FALSE reviews and testimonies on the internet, Contact JAMESMCKAYWIZARD & team as soon as you can via the email address below jamesmckaywizard at gmail dot com or WhatsApp +31622647750.
