### ISSUE TITLE
Facebook top-bar and sidebars stay on top while scrolling down (no Dynamic)

### ISSUE THREAD

**Issue by DallasBelt** [darkreader/darkreader#435]
On Facebook, the top-bar and sidebars (both left and right) stay on top while scrolling down the feed. Using the Dynamic engine fix this, but the site(s) takes more time to load. I hope the developer can look into this.

**Comment by alexanderby** [comment]
I haven't seen the issue in Chrome. Toggling "filter" property for `<html>` element makes it work in Firefox, so this is most likely a browser bug.

**Comment by DallasBelt** [comment]
Sorry, but how do I do that?

**Comment by alexanderby** [comment]
There is no fix possible, only Firefox team can fix it. They will need some minimal example to reproduce the problem, but I failed to create such an example, because it's hard to determine what exact combination of elements crashes the rendering. We can try just send them a links to facebook.com or github.com, but most likely they will not do anything. I cannot remember that Chromium team fixed any of CSS filter issues, they have lower priority.

By the way, why do you prefer using Filters rather than Dynamic Theme?

**Comment by DallasBelt** [comment]
Too bad, especially for Firefox users like me. Dark Reader on Chrome works like a charm, and dark themes are consistent across the application. (I switched to FF because Chrome display the colors inaccurately, at least on Ubuntu and Antergos). 

Answering to your question, I use filters because of the loading times. I have noticed that the Dynamic theme takes more time to render the page, while using filters instantly invert the colors.

**Comment by alexanderby** [comment]
On some websites the reason for slow loading is that if stylesheet is hosted in another domain (usually some CDN), many websites use security restrictions to manage loaded style, so it has to be loaded by extension. Also images hosted in another domain are protected from direct analysis due to some copyright restrictions, they are also loaded by extension again.

It seems possible to make it work without extra delay, but I should make more investigation to prevent introducing a security hole.

I think I will publish a bug report to Bugzilla soon.

**Comment by alexanderby** [comment]
Should be fixed now.
