### ISSUE TITLE
[Broken Website] egypt.souq.com looks broken if opened in a background tab

### ISSUE THREAD

**Issue by OmarNamis** [darkreader/darkreader#4404]
**Website**
https://egypt.souq.com

**How to Reproduce**
> With dynamic mode:
> 1. Open the website in a new tab without switching to it.
> 2. Wait for a few seconds until the tab fully loads.
> 3. Switch to the tab.

**Expected behavior**
The page to invert normally

**Actual behavior**
The page looks weirdly inverted, and my logo fixes from #4403 have a white background.

**Screenshots**
![image](https://user-images.githubusercontent.com/14346945/101284781-66b5d680-37ea-11eb-8794-cc95f0eae935.png)

**System info:**

- OS: Windows
- Browser: Firefox and Chrome
- Darkreader Version: 4.9.26

**Additional context**
This weird look happens when opening the website normally too, but it inverts correctly shortly.
However, it doesn't invert correctly when opened in the background as stated.

**Comment by Gusted** [comment]
Hi @OmarNamis!

This wasn't reproduce-able for me, after a couple of seconds it reverted how it should look like(notice-able due to my low-spec machine). Do you have by any chance any other extension?

Regards,
Gusted

**Comment by OmarNamis** [comment]
Did you make sure not to switch to the tab until it has fully loaded first?

Yes I have some other extensions, and I tried disabling everything except Dark Reader and the issue still persists for me on both Firefox and Chrome.

**Comment by Gusted** [comment]
Yes I made sure that it was fully loaded before switching to it, but the issue you described didn't occur to me.

**Comment by OmarNamis** [comment]
I did some more testing, and it seems to happen to me like 50% of the time.

Not sure what is causing this...

**Comment by OmarNamis** [comment]
Is there a way for me to get any logs out of Dark Reader? It might be helpful.

**Comment by Yash-Singh1** [comment]
@OmarNamis Go to chrome://extensions and turn on developer mode. Press on the background page at darkreader

**Comment by OmarNamis** [comment]
Thanks @Yash-Singh1 !

I tested this page:
https://egypt.souq.com/eg-en/huawei-gt-2-pro-1-39-inch-amoled-display-waterproof-smart-watch-night-black-12410100511/u/

The issue happened almost every time when I opened it in the background and it never happened when I opened it in the foreground.

And the log didn't say anything useful in both cases:
> Creating CSS for url: https://egypt.souq.com/eg-en/huawei-gt-2-pro-1-39-inch-amoled-display-waterproof-smart-watch-night-black-12410100511/u/

**Comment by Gusted** [comment]
Nothing to debug from dark reader, It's waiting on a Stylesheet to load before it can remove the fallback style.

**Comment by OmarNamis** [comment]
So what do you suggest I do to try to find what's causing this?

**Comment by Gusted** [comment]
> So what do you suggest I do to try to find what's causing this?

You don't have to find the cause, it's that when the site becomes visible to the user the styles that already has been found will now be loaded and styled and after the last one is `styled` the fallback can be removed safely. however their seems to be a problem whereby 1 style doesn't get styled for some reason and therefore the removal of fallback style is never called and causes this weird issue.

**Comment by OmarNamis** [comment]
> however their seems to be a problem whereby 1 style doesn't get styled for some reason and therefore the removal of fallback style is never called and causes this weird issue.

A problem from Dark Reader's side or from my side?

**Comment by Gusted** [comment]
> A problem from Dark Reader's side or from my side?

Dark Reader, I would like to have a bit more of an investigation why this weekend.

**Comment by KaKi87** [comment]
Hello,

---

@Gusted 

I would like to report that several websites are broken when opened in a new background tab.

For example :
- sentry.io on desktop Brave : the page looks empty, until disabling (and eventually re-enabling) Dark Reader ;
- m.youtube.com on mobile Kiwi : the page is wrongly colored, and the youtube video is invisible, until refreshing the page ;

There are more cases like those, although I don't remember, I'll think of adding some in the future if you'd like.

Additionally :
- there are several websites which requires disabling & re-enabling Dark Reader even when opened in foreground, usually in order to fix glitches looking like OP's screenshot ;
- websites are always broken when mobile Kiwi is opened as a custom tab ;

---

@OmarNamis

I can't check out your bug because here's what I see when opening your link :

![screenshot-egypt souq com-2022 05 17-11_36_58](https://user-images.githubusercontent.com/21284089/168784333-3fb737e7-83d7-4166-be71-cfc67f990def.png)

Obviously I don't know what to do. :sweat_smile: 

---

Thanks !

**Comment by Gusted** [comment]
This issue is invalid as the site doesn't exist anymore. @KaKi87 Please try to open issues and not comment on existing issues when they don't relate with the original issue.
