### ISSUE TITLE
[Feature Request] Stick with newlines or no newlines between CSS rulesets

### ISSUE THREAD

**Issue by Yash-Singh1** [darkreader/darkreader#4425]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Currently, the Dynamic Theme Fixes, Filter Theme Fixes, and the Static Theme Fixes sometimes have newlines between rulesets or sometimes they don't. I think that there should be one solution that should be used all the time, either stick with newlines or without newlines.

**Additional context**

This will keep the configuration more consistent

**Comment by Gusted** [comment]
Hey @Yash-Singh1!

I agree with this and think to have no newlines as I doesn't improve that greatly of an readability between rule sets.

However I also think that those new lines if created by an user should be formatted back to no new lines in the sections in order to have a consistent CSS-style and not have any issues in PR when reviewing.

Regards,
Gusted
