### ISSUE TITLE
[Broken Website] haxx.se

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4483]
**Website**
The link to the broken website
https://haxx.se/

**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Hover over x button
> 3. See that when hovering it isn't changing colors

1.  open https://haxx.se/

**Expected behavior**
must look clean

**Actual behavior**
A clear and concise description of what happened.
looks dirty

**Screenshots**
darkreader ON:
![image](https://user-images.githubusercontent.com/14617699/101952222-59915100-3c09-11eb-874d-d40a5296484f.png)
darkreader OFF:
![image](https://user-images.githubusercontent.com/14617699/101952228-5c8c4180-3c09-11eb-90a1-d221244dee81.png)

**System info:**

- OS: [e.g. Windows, MacOS, Linux] linux
- Browser: [e.g. chrome, safari] firefox
- Darkreader Version: [e.g. 4.9.9] 4.9.26

**Additional context**

**Comment by ath-github** [comment]
adding CSS: `height: 100vh` to BODY fixes your broken image problem (image getting cropped from below) and areas marked by red circles have such grain like pattern because haxx.se used a JPG image which compresses the image which in turn creates that grainy pattern. 
Instead an svg, png or any other lossless image format should be used. 
In this case I would recommend an svg.

![image](https://user-images.githubusercontent.com/47277932/101973583-0c3fce80-3c5f-11eb-8158-512107464a2e.png)

Hope this solves your problem 😄

**Comment by Gusted** [comment]
Hi @532910!

Their seems to be like mentioned above me some compression in place that causes to have the edges have slightly different colors to get a lower size that isn't noticeable on default settings, however it will become noticeable when you Invert+Modify the hue-lightness of the images, In the image under me you can see red/green/blue where the `noise` is. Dark Reader isn't causing this
![Inverted+100%Lightness](https://user-images.githubusercontent.com/25481501/101988026-2db8ae80-3c8f-11eb-84e5-dabf0373e1cf.png)

Regards,
Gusted
