### ISSUE TITLE
[Broken Website] basilisk-browser.org

### ISSUE THREAD

**Issue by TheFrenchGhosty** [darkreader/darkreader#4507]
**Website**
https://basilisk-browser.org/

**How to Reproduce**
Just go there

**Expected behavior**
White background becomes dark

**Actual behavior**
White background becomes green

**Screenshots**
![s](https://user-images.githubusercontent.com/47571719/102259398-f81dfa80-3f06-11eb-8c0a-34ddf7ebd615.png)

**System info:**

- OS: N/A
- Browser: Firefox
- Darkreader Version: 4.9.26

**Additional context**
It isn't *that* bad, but it looks weird.

**Comment by Gusted** [comment]
Hi @TheFrenchGhosty!

It's not broken, it's rather Dark Reader doing a little bit too good on this site. The background color of the original element is `rgb(217, 249, 240)`, which is considered `green` in the HSL space and therefore will be modified and treated as a dark color, I personally think that dark reader is doing it's job here.

Regards,
Gusted

**Comment by TheFrenchGhosty** [comment]
@Gusted Mmh, makes sense I guess. Though, I think it might be better to consider colors that are REALLY close to white as white, so that they can be changed to gray (basically, rely on what users see and not what the "HSL space" says).

**Comment by Gusted** [comment]
> @Gusted Mmh, makes sense I guess. Though, I think it might be better to consider colors that are REALLY close to white as white, so that they can be changed to gray (basically, rely on what users see and not what the "HSL space" says).

In terms of HSL, it's another way to look at an RGB color and gives 3 good indication Hue, Saturation, Lighting based on these 3 factors Dark Reader modifies the color. Their is no suchs thing in the `Color space` to know exactly what Users sees. 



> As I said, the fact that it's "supposed" to "look" white, but becomes green (instead of gray) is weird.

I personally don't think it was supposed to look like white due to the header that is already green and considering that basilisk's general theme is green, It has it's purpose to look like light green.
