### ISSUE TITLE
[Broken Website] pdf.js

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4510]
**Website**
The link to the broken website
https://mozilla.github.io/pdf.js/web/viewer.html

**How to Reproduce**
An example of this is
>
> 1. Go to x site
> 2. Hover over x button
> 3. See that when hovering it isn't changing colors
1. open website

**Expected behavior**
must look good

**Actual behavior**
A clear and concise description of what happened.
looks bad

**Screenshots**
![image](https://user-images.githubusercontent.com/14617699/102291225-bc5d5200-3f53-11eb-94f1-9c2bd01fc4f7.png)

**System info:**

- OS: [e.g. Windows, MacOS, Linux] linux
- Browser: [e.g. chrome, safari] firefox
- Darkreader Version: [e.g. 4.9.9] 4.9.26

**Additional context**

**Comment by Gusted** [comment]
PDF's are not supported by Dark Reader in Firefox due to restrictions by Firefox.

**Comment by 532910** [comment]
What does it mean "not supported" while Dark Reader breaks it!
Compare with Dark Reader turned off:
![image](https://user-images.githubusercontent.com/14617699/102422459-e5dfb180-4017-11eb-89cf-c57896c5be67.png)

**Comment by Gusted** [comment]
Dark reader doesn't support `pdf.js` and as this is a wrapper around it it won't work either, those buttons are outside pdf.js wrapper for the pdf itself.

**Comment by 532910** [comment]
I refuse to accept the fact that Dark reader breaks https://mozilla.github.io/pdf.js/web/viewer.html

Moreover it doesn't break internal embedded pdf.js:
![image](https://user-images.githubusercontent.com/14617699/102581264-40106d80-4111-11eb-94d3-60965b85d0f3.png)

or pdfjs.express:
![image](https://user-images.githubusercontent.com/14617699/102581348-6cc48500-4111-11eb-9418-91519d42deec.png)
![image](https://user-images.githubusercontent.com/14617699/102581351-6fbf7580-4111-11eb-992b-fc3f8dcb5054.png)

**Comment by Gusted** [comment]
Dark reader doesn't break it, it rather make them hard to see due to only modifying the html/body. Fixing this issue is reverting back what dark reader did which is effective as disabling dark reader. Might be time to go back to the drawing table and see if I can implement a dark mode for pdf.js last time it succeeded as a little prototype. It's more effective then fixing this with a dirty fix.

**Comment by trysten** [comment]
Dark reader `4.9.62` from firefox addon store
![image](https://user-images.githubusercontent.com/4760903/222014247-6fe41475-8a50-4449-a710-745c9653309d.png)
This is how an embedded pdf.js looks in default settings (filter mode)
Not the rectangle on the far left, properly darkified portion of the main site. For some reason pdf.js just inverts. This looks great on the actual pdf page but pretty bad on everything else. I don't have much to add. I think upgrading pdf.js to support dark mode makes the most sense.

**Comment by luo-chuan** [comment]
If you use Firefox, you can edit [userContent.css](https://davidwalsh.name/firefox-user-stylesheet) like this:
```css
@media (prefers-color-scheme: dark){
  .pdfViewer{filter: invert(1) hue-rotate(180deg);}
}
```
If you use [Chrome](https://chromewebstore.google.com/detail/pdf-reader/ieepebpjnkhaiioojkepfniodjmjjihl) or [Edge](https://microsoftedge.microsoft.com/addons/detail/pdf-reader/nhppiemcomgngbgdeffdgkhnkjlgpcdi), install the extention "PDF Reader", then edit the extention option like this:
```css
html[data-theme*="dark"] .pdfViewer{
  filter: invert(1) hue-rotate(180deg);
}
```

**Comment by lalishansh** [comment]
![Image](https://github.com/user-attachments/assets/e1add290-19d2-4696-9db5-1182b0e6232f)

For me, Added this for yomitan pdf viewer
```
yomitan.wiki

CSS
@media (prefers-color-scheme: dark) {
    .pdfViewer {
        filter: invert(1) hue-rotate(180deg);
    }
}
```

update:
```
yomitan.wiki/yomitan-pdf-viewer

CSS
@media (prefers-color-scheme: dark) {
    .pdfViewer {
        filter: invert(0.94) hue-rotate(180deg);
    }
    .toolbarButton:not(.labeled) {
        background-color: cyan;
    }
    .toolbarButton.toggled:not(.labeled) {
        background-color: yellow;
    }
}
```

**Comment by 0zitro** [comment]
For firefox users ::

Just wanted to throw this in: On some random website I encountered a pdfjs viewer and for some then-unknown reason the PDF was actually rendered in dark mode, with inverted colours. I had then looked into how that worked, because I tried making the PDF.js render PDFs in dark mode before and couldn't.

Turns out that PDFs rendered in `<embed>` containers are accessible for Dark Reader. You may try opening the following HTML ::

```html
<style>
:root, html, body {
  margin: 0;
  padding: 0;
  border: 0;
}
embed {
  width: 100vw;
  height: 100vh;
}
</style>
<embed src="https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf">
<!-- <embed src="https://static.mozilla.com/moco/en-US/pdf/mozilla_privacypolicy.pdf"> -->
```

and compare that to the raw PDF render on <https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf> and the non-natively "embedded" page <https://mozilla.github.io/pdf.js/web/viewer.html>. Dark reader can't access only the browser-chrome version.

By the way, this works **only in the mode "Filter" or "Filter+"**.

Maybe someone could get an extension working that replaces the embedded .pdf handler with a simple stub webpage that has that HTML I wrote before? Recursion may be prevented by using anchors in the `<embed>`'s `src` and probed at the request time.

This would sidestep all the "this is a protected page and a part of browser's chrome" BS like <https://bugzilla.mozilla.org/show_bug.cgi?id=1454760#c3>
