### ISSUE TITLE
[Dynamic] Page won't invert if cookies are disabled

### ISSUE THREAD

**Issue by rEnr3n** [darkreader/darkreader#455]
Enabling cookies will make it work.

Example:
https://stackoverflow.com/

**Comment by alexanderby** [comment]
Dynamic Theme mode currently uses Session Storage to cache requests to CSS files and images (this is needed due to CORS restrictions in browser). For some reason there is a blocking error when you are trying to access the storage.

The fix should be simple. In future we will analyze web requests and there will be no need in additional requests and cache.

**Comment by alexanderby** [comment]
I've made a fix and will publish it soon. Without the cache you will see white flashes due to the delay. In future we will use Web Requests API to prevent extra loading time.
