### ISSUE TITLE
[Feature Request] Implement Darkreader support via CSS body class?

### ISSUE THREAD

**Issue by Asitis** [darkreader/darkreader#4835]
I'm a full time webdeveloper and I use Darkreader almost everywhere, even on my own sites while developing them and I love it.
There are however minor css issues that pop up that I could fix for myself locally in the extension, but I'd rather fix it for every visitor who uses darkreader on these sites.

Would it be possible for the extension to just add something like a "darkreader-activated" body class to pages? That way I can easily hook in for users that use this extension and fix my sites up properly for them, because my bosses probably won't give me the time or budget to do a full manual darkmode..

**Comment by Gusted** [comment]
Hey @Asitis!

> but I'd rather fix it for every visitor who uses darkreader on these sites.

We have such [config file](https://github.com/darkreader/darkreader/blob/master/src/config/dynamic-theme-fixes.config) to add in those fixes.



> Would it be possible for the extension to just add something like a "darkreader-activated" body class to pages? That way I can easily hook in for users that use this extension and fix my sites up properly for them

It won't be a hassle to add it, however their could be certain scenario's that sites expect certain classes in the body, but we've then added "darkreader-dynamic"(I'd like to use the `theme's engine` for anyone that also might want to fix certain things for `Filter` mode. Because of adding that class it could break a portion of the site, however AFAIK don't know a site that could possible do this kind of check. I will open up a PR for it. 

Regards,
Gusted

**Comment by Gusted** [comment]
#4860

**Comment by guacamoleRiver** [comment]
Gusted, I'm not sure how that particular patch works! Could you update the documentation?
I tried "HTML", and "darkreader-dynamic-light"/dark, nothing worked!
What about making something like `"darkreader-ignore"` or `"darkreader-retain"` with an optional -`static`/`filter`/`dynamic` appended.
- *ignore* would remove all inserted theming on that element
- *retain* would check the elements color values, either explicit or inherited and override other darkreader rules with these original values, leading to the element retaining its original look.

Also, `darkreader-norecurse` or something similar could be added to make this only apply to the element specified, and no child elements.

Now, this could have adverse effects for the user, so adding a site-specific (or global) toggle to allow/disallow sites from using these theming classes would also be beneficial.

----

I think that this is a crucial step in the plugins development, that could relieve a lot of burden on the maintainers. This would allow people to make fixes for their own sites without requiring the user to update their Darkreader!

(  slightly unrelated tangent →  )
Anyway, I use another extension that doesn't work well on sites because of this, and with these rules I could avoid making an upstream merge request, and just modify the extension itself. More on that here: #4946

**Comment by Gusted** [comment]
Hi @guacamoleRiver!

I think you misunderstand what the idea behind the patch is. It is simply to identify which mode/engine is currently applied on the page. 



> What about making something like `"darkreader-ignore"` or `"darkreader-retain"` with an optional -`static`/`filter`/`dynamic` appended.
> 
>     * _ignore_ would remove all inserted theming on that element
> 
>     * _retain_ would check the elements color values, either explicit or inherited and override other darkreader rules with these original values, leading to the element retaining its original look.
> 
> 
> Also, `darkreader-norecurse` or something similar could be added to make this only apply to the element specified, and no child elements.

See point 2 and 3 why not https://github.com/darkreader/darkreader/issues/4856#issuecomment-766191834



> Now, this could have adverse effects for the user, so adding a site-specific (or global) toggle to allow/disallow sites from using these theming classes would also be beneficial.

Wait so site make specific fixes and user could disable them? My logic is that the site will make those fixes because x doesn't work or y isn't really readable with dark reader etc.



> I think that this is a crucial step in the plugins development, that could relieve a lot of burden on the maintainers. This would allow people to make fixes for their own sites without requiring the user to update their Darkreader!

This can be done trough the patch by something like
```CSS
.darkreader-dynamic-dark .error-text {
    color: red !important;
}
```
No need to have such mess in classes to specify.

Regards,
Gusted

**Comment by guacamoleRiver** [comment]
Site specific fixes would be good as a toggleable option because some sites may dislike users changing their theme, and intentionally force light mode. Cruel, and a rare case, but I already hardly touch the settings, so I think it'd fit well.

But, I've tried your patch, and it works, looks mostly good to me. Perhaps some overrides could be added to prevent the need for `!important`?

**Comment by Asitis** [comment]
> Site specific fixes would be good as a toggleable option because some sites may dislike users changing their theme, and intentionally force light mode
This would be possible, I guess. I don't think any webdeveloper is going to take the time to do that however. And you know, there are some websites who break entirely using Darkmode (content becomes invisible or whatnot) and if they use it in that way, it's still an improvement I guess!

> I've tried your patch, and it works, looks mostly good to me. Perhaps some overrides could be added to prevent the need for `!important`?
As far as I know if the class is added on the top `<html>` element, a webdeveloper should never need `!important`, due the cascading nature of CSS. Also, this is of course up to each webdev who decides to add some darkreader specific fixes to their css.

**Comment by guacamoleRiver** [comment]
I must be doing it wrong, because even when I added the class to the top HTML element, `!important` was still needed. I know you can always override it with over-specificity, but that's more pain than its worth and, frankly, `!important` does the job in that regard.

**Comment by Gusted** [comment]
> As far as I know if the class is added on the top `<html>` element, a webdeveloper should never need `!important`, due the cascading nature of CSS.

+1, it should override the normal CSS as browsers will use the extra `.darkreader-[...]` to prioritize over normal CSS as it's taken in account that's 'more specific' and gets priority. There will be edge-cases where this can differ.



PS: The patch could need some additional patches as dark reader will modify those 'CSS' as well and might break it again. A current workaround is adding a separate
```HTML
<style class="darkreader">
```
However it's better to just have a simple check like
```javascript
if (selectorText.includes('darkreader') {
    continue;
}
```

Regards,
Gusted
and ignore anything that has the 'darkreader' in the selector.
