### ISSUE TITLE
Text Highlight Color

### ISSUE THREAD

**Issue by nmehrle** [darkreader/darkreader#484]
On some sites, particularly in Jupyter Notebooks, the text highlight color is so close to the background color it is hard to see. Could you add an option for modifying highlight contrast?

**Comment by alexanderby** [comment]
Could you please add some screenshot?

**Comment by nmehrle** [comment]
Sure, see below for the screenshot. To make this, I loaded up a Jupyter notebook and activated Dark Reader, then highlighted the text as labeled. I'm using the Dynamic option in Dark Reader, and vanilla Jupyter notebooks.

If you look closely you can see a blue box around the highlighted text

![screen shot 2018-05-30 at 3 23 24 pm](https://user-images.githubusercontent.com/5505487/40742849-c28f8ba2-641d-11e8-8709-f92dfa3c6875.png)

**Comment by alexanderby** [comment]
Thanks. They are using some custom text selection. It will be possible to improve using custom CSS soon.

**Comment by mohammedyunus009** [comment]
Right , Even im facing the same issue with jupyter notebooks , But mean while , U can select the site list> inverted list only .... this will disable the dark mode for jupter notebooks only(localhost),

**Comment by sanyam5** [comment]
I am a heavy user of Jupyter notebooks. This issue still exists... any updates on this? Loving the extension other than this. Keep up the good work!

**Comment by abisowri** [comment]
Hi, any updates on this issue? I am facing a similar issue with highlighting text using dark reader mode.

**Comment by safijari** [comment]
I have the same issue

**Comment by jhadida** [comment]
FYI, although this is not technically a fix of the issue _per se_, the following works for me:

 - Click on the Dark Reader app in your Toolbar
 - Select the tab "More"
 - Toggle the button "Only for localhost:8888", to apply the following change only to locally served notebooks
 - Then select "Filter" instead of "Dynamic" under the "Theme generation mode"

This really improved the colours in my case (used to be all dark-gray before that, and could not even see highlighted text in code blocks). HTH!

**Comment by jtraub** [comment]
I also observe the problem.

However, I am not able to produce a fix in this case due to the fact that Jupiter notebooks can be served from any domain and they can have different themes (see this - https://github.com/dunovank/jupyter-themes as an example).

@alexanderby do you have any plans to add more flexible mechanisms for applying fixes to the dynamic theme?

**Comment by mireiner** [comment]
I got the same issue. Hightlight color is too close to the background. Using Firefox 69.0.1. That makes it really hard to select text! Is there any solution for this problem yet?

**Comment by hallohallo333** [comment]
same. please offer fix.

**Comment by ajdajd** [comment]
Also when using Google BigQuery web UI. My quick fix is to set Brightness to +50 and Contrast to -50.

**Comment by shail-burman** [comment]
any update on this issue? I am having the same problem.

**Comment by mathsmathsmaths** [comment]
Same issue, but it can happen on any site. Take nytimes.com for instance. On my Mac, the accent color is set to purple, but the highlight is blue instead of purple.

**Comment by Gusted** [comment]
So far I know darkreader V5 will have a color picker to change selection text in the new UI

**Comment by swarnadeep** [comment]
+1 Need this 
text selection colour on editable code boxes on jupyter are to close to background colour

**Comment by Gusted** [comment]
I'm going to work on this

**Comment by jaimesoza** [comment]
Hi

It seem's it is closed, but I am having the issue in Jupyternotebooks:

![image](https://user-images.githubusercontent.com/21311599/82961238-c5bca800-9f8a-11ea-94c1-41ed459cab35.png)
(lines 2, 3, 4, and 5 are highlighted)

This only happens inside the cells; if I have some text as markdown, it works.

**Comment by Gusted** [comment]
Devtools -> Preview new design
See all options -> Selection 

@jaimesoza

**Comment by jaimesoza** [comment]
@Gusted 

Thanks, I managed to do what you said. It was a bit buggy at the beginning, but after closing and reopening Chrome I could change the selection colour.

However, the issue is still there: If I highlight text outside the cells, it works:
![image](https://user-images.githubusercontent.com/21311599/83027874-afe8ca80-9ffe-11ea-8ce4-bc4d6317793e.png)

But it remains the same as before if I do it inside the cell:
![image](https://user-images.githubusercontent.com/21311599/83027999-d7d82e00-9ffe-11ea-8566-dfaccce8d5aa.png)

Hope it can be easily fixed, I would deeply appreciate it

**Comment by Gusted** [comment]
It could be Jupyter override selection inside cells if that is the case it will almost impossible to make a fix for this.

**Comment by PyroGenesis** [comment]
Adding this to the config in Dev tools worked for me.

```
localhost:88*

CSS
.CodeMirror-selectedtext {
    background-color: #1d558f !important;
}
```

**Comment by Gusted** [comment]
I will look if we can try to expose the selection color to dev tools so it will anticipate on it.

**Comment by mc-marcocheng** [comment]
![image](https://user-images.githubusercontent.com/57459045/103472987-a1516580-4dce-11eb-8604-7e9ad11bec88.png)
It seems to me that the selection background color is slightly off. How do I get a pure white selection background color?

**Comment by Gusted** [comment]
HI @mc-marcocheng!

The color can differ if you have custom theme settings.

Regards.
Gusted

**Comment by Jesse-Ray** [comment]
Under the 'more 'tab, I changed the Dynamic Theme to Filter.
Filter is similar to VS FireFly Pro which I currently use

**Comment by lrq3000** [comment]
I had to implement all 3 fixes ([1st](https://github.com/darkreader/darkreader/issues/484#issuecomment-634573920), [2nd](https://github.com/darkreader/darkreader/issues/484#issuecomment-640175429), [3rd](https://github.com/darkreader/darkreader/issues/484#issuecomment-778826392)) above by @Gusted, @PyroGenesis and @Jesse-Ray to get a finally satisfactory enough result:

![image](https://github.com/darkreader/darkreader/assets/1118942/7bf687a7-4593-49f4-b978-b7db6a52f982)
