### ISSUE TITLE
[Feature Request] Ignore fill/text color + more in Google Docs, Sheets, Slidets etc. content

### ISSUE THREAD

**Issue by Arxareon** [darkreader/darkreader#4856]
Hey!

**The problem in detail:**
Google Docs, Sheets and web apps alike have a problem where Dark Reader does wonderfully translate the page to a dark theme but at the cost of having the content being worked on misrepresented. Not every content is simple docs with black text on white paper - in this case a simple translation of black and white works fine, everyone can imagine the page is actually white and how other without a dark theme would see it. However, if it is a complex spreadsheet for instance, with important color coding, how it really looks does matter.

The biggest problem is the dimming and darkening of text and fill colors. Even the color palette is altered, you can't possibly work without seeing the true colors they they truly matter. I have having to turn on Dark Reader in these cases (which is almost all of the time for me - especially in Google Sheets).

I'm using the Dynamic filter on all sites, I love how it scans through the page and alters content to preserve the original look of images and other elements while seamlessly intergrading them into the dark look. It does still work for the web apps mentioned above, they look fine and the colors - even though the light tones are dimmed - are the same in the content as within the color palette in the menu, so they are consistent. (As I said, the problem is that they are not consistent with how the content looks with no dark theme applied for other users).

**Requested feature to solve this problem:**
I'd suggest a filtration option that would ignore specific parts of a site from being translated into a dark look. There are multiple was it could be done. You could manually add exceptions for popular sites such as Google Docs, Sheets, Slides, possibly Office Live web apps (haven't tested) etc. to prevent the content as in the page, background color, the cells of a spreadsheet, text and other graphical elements as well as the color palette in the menu from being dimmed.

As a bonus, alternative option, you might be able to think about using website element selection (something like what Adblock Plus uses) to allow us to select elements of a page to let us manually exclude them from being darkened. This would not be the best solution for solving the issue with office web apps, but it might still be a cool feature that would help ironing out other possible anomalies in edge cases and whatnot.

Please consider a solution to this problem! I already love your dark theme app the most (the Dynamic filter is a killer feature), and I'd love if I could use it while working with these apps and not just for browsing.

Thank you, have a nice day!

**Comment by Gusted** [comment]
Hi @Arxareon!

Sorry for the unlogical order of how I will type things.

- You seems to have a special problem with Google Sheets, we cannot do anything with this due to #490 #1934 TL;DR we cannot change thins individually for Google Sheets.
- So, Dark mode = Dark mode. Not Dark Mode = Partial Dark Mode. Actually not by default should this be the case, of course we could provide that certain option however this are rare cases and some should be by default due to reasons. It's an complex issue(More on this later). Of course we could not style the color pallet, but the user is in dark mode not doing this will break the look and have text/elements unreadable and will defeat the purpose of an overall dark color scheme.
- Complex: We have no logic to not style certain issues, why you might ask: It's expensive as **** in terms of performance, performance can go brrr. Especially on larger elements and areas. Plus the fact we have no way to see if style x will be used on element y and their isn't a reliable way to do so. Well the most reliable way will be slow and painfully to implement.


*Note: Thank you for the detailed explanation! Not common to see that these days.*

Regards,
Gusted

**Comment by Arxareon** [comment]
I see!

> Google sheets expose it as a whole element so it will also target images. I tried to do anything to this but I can't specify any individual elements.

It seems like Google needs to get their act together and make a dark theme themselves.. or it might be a whole project in itself making a customizable extension just for these web apps.. A bummer.

Well, thanks for the response! :)
