### ISSUE TITLE
Setting font causes some images to be render as boxes

### ISSUE THREAD

**Issue by ApprovedDB** [darkreader/darkreader#491]
As seen here:
Before

![Before applying a font](https://i.imgur.com/wYtAVuc.png "Before applying a font.")  
After

![After applying a font](https://i.imgur.com/5q44r9e.png "After applying a font.")

**Comment by Aqa-Ib** [comment]
That is not a problem with Dark Reader, it is a problem with the browsers. It happens in both, Chrome and Firefox and I am aware that users have already informed of this bug, at least to the Mozilla developers.

**Comment by Aqa-Ib** [comment]
Here is the Mozilla Firefox bug report in case you want to see it:
https://bugzilla.mozilla.org/show_bug.cgi?id=789788

It was reported 6 years ago and still no fix.

**Comment by Aqa-Ib** [comment]
Actually I think that there could be a simple fix for Dark Reader. Create the rule font-family to apply to all elements except those who match with class=icon.

I don't know how this rule could be written. I tried with ":not[(class*=icon)] {font-family: FreeSans !important}" but it does not work as intented because it is not applying to all elements except for those whose class is icon.

**Comment by Gusted** [comment]
Probably they use unicode characters(For sure)/Symbols(Also Unicode) and somehow that is also rendered by the font so if you use a font that don't support it. It will show like a box and Dark Reader have no influence on that.
