### ISSUE TITLE
[Broken Website] https://parcelsapp.com/en/tracking crashed DarkReader

### ISSUE THREAD

**Issue by kubax** [darkreader/darkreader#4935]
# Broken Website

## Website
https://parcelsapp.com/en/tracking

## How to Reproduce

- Go to https://parcelsapp.com/en/tracking site
- wait for site to load
- Press F5 or reload, DarkReader should have been crashed

## Expected behavior
- nothing...

## Actual behavior
- DarkReader crashed

## System Information

- OS: Arch Linux
- Browser: Chromium 88.0.4324.96
- Dark Reader Version: 4.9.26

**Comment by Gusted** [comment]
Hi @kubax!

It doesn't crash for me, updating to 4.9.27 might help. I can see from the profiler that parcel is loading a lot of images which Dark Reader is analysing. Thereby it's _not_ possible to properly debug this, due to an anti-behaviour of parcelsapp of rapidly spamming an `debugger;` breakpoint into the user. Which practically make debugging unusable. Therefore I have to close unfortunately close this issue with a wont fix due to this ridiculous anti-behaviour of the site.
![image](https://user-images.githubusercontent.com/25481501/106467673-e4b5f700-6494-11eb-96e3-5940a0f21054.png)

Regards,
Gusted

**Comment by kubax** [comment]
Yeah, i also stumbled upon the debug "feature" but could not find a reason why this pops up everytime.. At least i now know that it's the website doing some stupid things here -.-

I tried to upgrade to 4.9.27 or 4.9.28 but neither of those are available in the web store. Do you have a hint for me how i could update it anyway?

also, thanks for having a look at this.

**Comment by Gusted** [comment]
> I tried to upgrade to 4.9.27 or 4.9.28 but neither of those are available in the web store. Do you have a hint for me how i could update it anyway?

I actually was just informed that Google, didn't review the 4.9.27 version *yet* which was submitted around 10 days ago. You could side-load the 4.9.28 version: [build.zip](https://github.com/darkreader/darkreader/files/5904511/build.zip)




> Yeah, i also stumbled upon the debug "feature" but could not find a reason why this pops up everytime..

The site is looping an certain function that creates an script put "debugger" into it and execute it. And have 0 idea why in the world an company would do that.

**Comment by kubax** [comment]
Thanks. That actuelly fixed the issue...

So i think i'll keep the side loaded extension for some time, until google decides that the update is fine :)

Thanks for you help. This was driving me nuts...
