### ISSUE TITLE
[Broken Website] gmail add to task

### ISSUE THREAD

**Issue by 532910** [darkreader/darkreader#4942]
# Broken Website

## Website

https://mail.google.com

## How to Reproduce

goto https://mail.google.com and log in

## Expected behavior

add to task icon must be visible

## Actual behavior

add to task icon is invisible

## Screenshots

![image](https://user-images.githubusercontent.com/14617699/106442123-f6df6780-648b-11eb-812e-750e2eadd626.png)

## System Information

- OS: linux
- Browser: firefox
- Dark Reader Version:  4.9.27

**Comment by Gusted** [comment]
Hi @532910!

Gmail + Dark Reader is known for their _performance_ and due to the large amount of images, certain images might take a while before it actually might get modified
![image](https://user-images.githubusercontent.com/25481501/106469701-89393880-6497-11eb-8db8-6701e745227f.png)

Regards,
Gusted
