### ISSUE TITLE
[Broken Website] cppreference offline archive

### ISSUE THREAD

**Issue by bb1950328** [darkreader/darkreader#4985]
# Broken Website

## Website

https://github.com/PeterFeicht/cppreference-doc/releases/download/v20201016/html-book-20201016.zip

## How to Reproduce

1. Download https://github.com/PeterFeicht/cppreference-doc/releases/download/v20201016/html-book-20201016.zip
2. Extract the archive
3. Open `reference/en/index.html`

## Expected behavior

The background should be dark, like https://en.cppreference.com/w/

## Actual behavior

The plugin does nothing, the background is white

## Screenshots

![Offline cppreference vs online](https://i.imgur.com/Abeagxw.png)

## System Information

- OS:  Ubuntu 20.10
- Browser:  Firefox 85.0 (64-bit)
- Dark Reader Version:  4.9.27

**Comment by Gusted** [comment]
Hi @bb1950328!

Yes, that's expected behavior, due to security reasons. Extension cannot request local CSS files and thus dark reader won't work. However a simply workaround(due your on Linux) will be opening an terminal on the main folder with the .xml files and type `python3 -m http.server 1337` and then open firefox on `http://localhost:13457/reference/en/`

Regards,
Gusted

**Comment by bb1950328** [comment]
Hi @Gusted 
Thank you very much for your quick response. I think a message inside the Dark Reader window would be very useful for users who don't know about this.

Regards,
bb1950328
