### ISSUE TITLE
[Feature Request] Export Site CSS

### ISSUE THREAD

**Issue by Goddard** [darkreader/darkreader#5055]
From a web dev perspective this extension takes an existing website and makes a pretty beautiful site for people who prefer dark mode.

I wonder either through existing means, or just some new feature if it would be possible to export the actual website CSS that is generated in order to make a real dark mode for my website.

I imagine to have maximum effect it could do a web crawl and compile a complete CSS/SCSS file for the entire site and then output a single file.  Then the web dev could take that and make any needed tweaks to make it look perfect.

I personally would love this feature.  Any suggestions welcome.  

Thanks

**Comment by Gusted** [comment]
Hi @Goddard!

You are either looking for #13 or if you meant programmatically exporting the CSS you can look from https://github.com/darkreader/darkreader/issues/604#issuecomment-711052527 whereby a good example can found at https://github.com/phseiff/phseiff.github.io/tree/master/darkreader from @phseiff.

Make sure to use the proper template next time.

Regards,

Gusted

**Comment by Goddard** [comment]
Thanks.  That did help a bit.  

Just curious though.  Is this supposed to work with JS elements?  For example I have fullcalendar on a site and it works great with the extension, but not the exported css.

Thanks.

**Comment by Gusted** [comment]
> Just curious though. Is this supposed to work with JS elements? For example I have fullcalendar on a site and it works great with the extension, but not the exported css.

Could elaborate what you mean with JS elements?

**Comment by Goddard** [comment]
Well the js element is fullcalendar.

It is fully generated via ajax.

**Comment by Gusted** [comment]
Hmm, they should I just had a look on their demo page and nothing seems out of the ordinary and the exported CSS works perfect.
https://fullcalendar.io/demos
![image](https://user-images.githubusercontent.com/25481501/109310058-f6907d00-783b-11eb-9cd7-f8ea5ba770d8.png)

**Comment by phseiff** [comment]
@Goddard  The exported darkmode-CSS will only contain darkmode-versions of styles defined within `<style>` tags or styles that are embedded from a CSS file (a restriction the browser extension does not impose, which explains @Gusted 's screenshot).

So if you have something like the following, you won't get a darkmode-version of it in the exported CSS:

```html5
<p style="color: red;">lorem ipsum</p>
```
or
```
<p color="red">lorem ipsum</p>
```

If you have something like the following, however, you **will** get a darkmode-version of it in the exportet CSS (this also works if you embedded the style into your website from a CSS-file rather than using `<style>`-tags):

```html5
<p class="red-p">lorem ipsum</p>

<style>
.red-p {
    color: red;
}
</style>
```

You should probably check whether the styles used by your ajax-generated calendar use inline-style definitions, and then maybe check if you can change that.
