### ISSUE TITLE
[Feature Request] Make a DarkReader web app!

### ISSUE THREAD

**Issue by rashil2000** [darkreader/darkreader#5063]
# Feature Request

## Is your feature request related to a problem? Please describe
Browsers that don't support extensions. Chrome on Android is the most popular one. Edge on Android too.

## Describe the solution you'd like
Don't know if it's possible or ever been suggested here (I couldn't find similar issues already), but I think a really simple solution would be to make a DarkReader webapp - basically a simple website, with a URL field. Users type in the URL, and the DarkReader webapp will show the page in an iFrame, with its own awesome stylesheets applied, so that the iFrame pages are dark. Would be very useful for viewing websites like Wikipedia etc. on mobile phones.

## Additional context

The webapp can be hosted right here on GitHub - _darkreader.github.io/web_
Future plans for the webapp could include storing the user's bookmarks in localstorage or something, so that access is easier. Back and Forward navigation buttons can be implemented.

**Comment by Gusted** [comment]
> Don't know if it's possible or ever been suggested here (I couldn't find similar issues already)

Not that I know of.


> but I think a really simple solution would be to make a DarkReader webapp - basically a simple website, with a URL field. Users type in the URL, and the DarkReader webapp will show the page in an iFrame, with it's own awesome stylesheets applied, so that the iFrame pages are dark. Would be very useful for viewing websites like Wikipedia etc. on mobile phones.
> ##

I really like this idea. Sounds promising.



> The webapp can be hosted right here on GitHub - _darkreader.github.io/web_

Couldn't agree more.


> Future plans for the webapp could include storing the user's bookmarks in localstorage or something, so that access is easier. Back and Forward navigation buttons can be implemented.

That's of course up to future discussion.

I will have a look in the weekend and might get some prototype working of this idea.

Regards,
Gusted

**Comment by rashil2000** [comment]
> I really like this idea. Sounds promising.

Thanks! I was surprised to find this doesn't exist already, given that it's so simple (there might be some caveats unbeknownst to me).

> I will have a look in the weekend and might get some prototype working of this idea.

I have some frontend dev experience, and would love to contribute myself, if possible.

**Comment by AndrewDaGuy** [comment]
I kind of like this idea :], maybe a dark reader icon in top-right to edit brightness/contrast/etc. + additional settings for the web app itself :o.

**Comment by Gusted** [comment]
Hi everyone!

So a little update, I've now setup a workflow over at https://github.com/Gusted/darkreader-web. With (compiling) Typescript & TO-DO watch mode & Serving the files trough `serve` which eventually can be replaced by [esbuild's serve](https://esbuild.github.io/api/#serve) functionality.
So I can today? Tomorrow? In the weekend? Make a simple POC with a simple searchbar where you can insert the URL an IFrame where the site is loaded and on miraculous way insert's darkreader.js into it. and then I can polish the code further and anyone who likes to do some CSS and HTML can do that, because surprising I can't even center an element.

Regards,
Gusted

**Comment by Gusted** [comment]
Hey!

So due to technical implementation on the web app, I will be using IFrames to load the site. However remembering Dark Reader and IFrames don't go really good along side each other. So remembering a recently issue #5082 I just got around to make this(#5085) possible and will using Dark Reader making a lot simpler for the web app.

Regards,
Gusted

**Comment by rashil2000** [comment]
That's great news!

**Comment by Gusted** [comment]
Continuing the discussion at https://github.com/Gusted/darkreader-web/discussions/2 as it would be more suited
