### ISSUE TITLE
[Question] How to apply dark mode to all iFrames when using DarkReader API in React Project?

### ISSUE THREAD

**Issue by hvaoc** [darkreader/darkreader#5082]
# Question

Is there a way to apply dark mode to all iFrames in a page when using API (When using Extension, all iFrame in a page are also rendered in Dark Mode).

## Is your feature request related to a problem? Please describe
If this is not possible currently when using as API, can we get it added?

## Describe the solution you'd like
When using enable, disable methods from API, iframes in a page must be identified and applied with dark mode as it happens when using Extension. I understand Extension uses Extension API to do this. Is it possible to do something similar for API ?

**Comment by hvaoc** [comment]
Currently iFrame from the same domain (One Level) is able to get changes as Dark Mode is enabled / disabled. But nested iframe from another domain remains with White Background.

**Comment by Gusted** [comment]
Hi @hvaoc!

I have experimented with this situation before, however due to the nature of IFrame's, it is hard to have out-of-the-box solution.
Because we have 2 problems here:
1. Detect an IFrame and add a source of Dark Reader into it. Possible solution to this can is for Dark Reader to listen into IFrame's and let e.g. an callback that's provided trough the Dark Reader API by the user, handle what to do with it. E.g. they could simply add another `script src="darkreader.js"` or use something else what is efficient.
2. Pass events/functions trough IFrames. e.g. what if the site/API user disables Dark Reader. All nested IFrames should receive that communication. This can be _potentially_ solved trough [iframe.contentWindow](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow) and then dispatch some [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) on the window to let them know what to do.

To implement this, it can be very tricky to not break anything nor due to detecting IFrames be a huge performance lost.

Regards,
Gusted

**Comment by Gusted** [comment]
Hi @hvaoc!

Primarily due to #5063 was on my TO-DO list and ask design concept using IFrames, making logic inside darkreader.js to handle this was resolving this issue and making #5063 a lot easier to create. #5085 has all the related code compiled version of darkreader.js of that branch + some example of how I did it.

Regards,
Gusted

**Comment by Gusted** [comment]
Closing, as this will currently not be supported within Dark Reader API. Current solutions relied on slippery slope code.
