### ISSUE TITLE
When data has z-index: -1, its hidden underneath the black layer;

### ISSUE THREAD

**Issue by jsandr** [darkreader/darkreader#5142]
Hi !

I was styling a web-page with dark reader OFF, used z-index for tooltips (z-index: 1) and data in cells (z-index:-1). Display was fine as I wished it.
Turned dark reader back ON to admire my work and my whole data was gone ! As I'm using a change of opacity when hoovering I'm able to see the data when I hoover it, so its there.

I believe its an issue ?

<img width="364" alt="example 1" src="https://user-images.githubusercontent.com/61015242/109187728-78c46700-7792-11eb-8e4d-4a6480ee7632.PNG">
<img width="334" alt="example2" src="https://user-images.githubusercontent.com/61015242/109187732-79f59400-7792-11eb-8021-f8c2fb9add9d.PNG">

**Comment by Gusted** [comment]
Hi that is normal behaviour due to having background-color on the html element, make the cells z-index 0 to have the same effect and work nicely with Dark Reader, please make sure to follow the [issue template](https://github.com/darkreader/darkreader/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+Replace+with+title) next time.
