### ISSUE TITLE
[Broken Website] Chrome vs Firefox issues

### ISSUE THREAD

**Issue by Arion-Kun** [darkreader/darkreader#5187]
# Broken Website

## Website

https://www.pinterest.com

## How to Reproduce

  An example of this is:
  - Go to the Pinterest site
  -  Look at the search bar
  - The search bar stays white in Firefox but not in Chrome

## Expected behavior

Expected behavior is that the site will show the dark theme like it does properly in chrome but not in Firefox.

## Actual behavior

There is a disparity between the two browsers causing one to look different than the other

## Screenshots

Firefox: ![Firefox](https://cdn.discordapp.com/attachments/751546899332464811/817902807150624768/unknown.png)
Chrome: ![Chrome](https://cdn.discordapp.com/attachments/751546899332464811/817902840806637618/unknown.png)

## System Information

- OS: Windows
- Browser: Firefox v88.0a1 (2021-03-06) (64-Bit)
- Dark Reader Version: 4.9.16

**Comment by Gusted** [comment]
> Dark Reader Version: 4.9.16

Update to 4.9.29

**Comment by Arion-Kun** [comment]
Issue still persists on 4.9.29.

**Comment by Gusted** [comment]
I could sometime reproduce it on 4.9.16 not on 4.9.29. Not on Firefox Nightly nor on stable. It might be due to some custom settings, try it on a fresh profile.

**Comment by Arion-Kun** [comment]
No addons apart from DarkReader active, no themes active either
![image](https://user-images.githubusercontent.com/53127594/110247973-8094c000-7f77-11eb-915b-079e39334f14.png)
Enhanced tracking from firefox is also disabled
DarkReader settings:
![image](https://user-images.githubusercontent.com/53127594/110248003-a5893300-7f77-11eb-86d3-5767b939f57b.png)
![image](https://user-images.githubusercontent.com/53127594/110248008-ac17aa80-7f77-11eb-89db-4fbbca6713e4.png)

**Comment by martinhartmann** [comment]
Same issue for me since the latest Nightly. The dynamic theme really doesn't work (anymore) or produces very weird results.

| Firefox Nightly 88.0a1 | Firefox Dev 87.0b6 |
|--|--|
| ![dark-reader-firefox-nightly-88 0a1](https://user-images.githubusercontent.com/15929417/110258224-d716f400-7fa1-11eb-9a5d-ac6d8ec09ed1.png) | ![dark-reader-firefox-dev-87 0b6](https://user-images.githubusercontent.com/15929417/110258229-db431180-7fa1-11eb-8893-88c70b07590a.png) |
| ![dark-reader-firefox-nightly-88 0a1-imdb](https://user-images.githubusercontent.com/15929417/110258234-e138f280-7fa1-11eb-8d54-7ad0c1ff0c03.jpg) | ![dark-reader-firefox-dev-87 0b6-imdb](https://user-images.githubusercontent.com/15929417/110258238-e6963d00-7fa1-11eb-91b5-e27491cec9a1.jpg) |

(both using new profiles)

Happend today after I upgraded to the latest version. On IMDB it doesn't seem to work at all.

See the original version:

![firefox-nightly-imdb](https://user-images.githubusercontent.com/15929417/110258302-3bd24e80-7fa2-11eb-8788-c4807c70c91c.jpg)

On mobile it looks correct like the Dev Edition version on Builds #2015797131 and #2015797323. Chrome and Edge (both Canary) look like the Dev Edition of Firefox.

Dark Reader version is always 4.9.29.

**Comment by Gusted** [comment]
Nightly is probably having some bad builds atm. Some other things are broken as well #5182. In their commit log their doesn't seem to be any changes in specs. Nor does our code produce any errors. and under certain conditions our styles are getting cleared and thus can produce to these results. I can have a look over some days and run `mozregression` over it, if they haven't fixed by then. It's nightly after all and expected behavior.
