### ISSUE TITLE
[Broken Website] https://developer.apple.com/xcode/ showing improper images

### ISSUE THREAD

**Issue by JoseDeFreitas** [darkreader/darkreader#5263]
# Broken Website

## Website
https://developer.apple.com/xcode/

## How to Reproduce
- Go to https://developer.apple.com/xcode/
- Scroll down down to see all images

## Expected behavior
The images stay the way they are.

## Actual behavior
Colors of images seem to be inverted or with a filter applied.

## Screenshots
https://imgur.com/a/Bx0tG7H

## System Information
- OS: Windows 10 Pro (version 1903)
- Browser: Mozilla Firefox 86.0.1
- Dark Reader Version: 4.9.29

## Additional context
I navigated through more pages of the website and noticed the images are the only thing that look weird.

However, what's interesting is that only this page https://developer.apple.com/xcode/ is where you can see this bad behavior. If you go to https://developer.apple.com/documentation/xcode/ (for example) you can see an image without this issue. It's the same if you go to the main domain https://developer.apple.com, every image looks good (interestingly, if you scroll down to "Introducing Xcode 12" in this main page you'll see the image is the same that the one at the top of the page with the issue).

Because of this I've looked at the code using the Dev Tools and saw that the image in https://developer.apple.com is inside an `<img/>` tag, while the images in https://developer.apple.com/xcode/ are inside `<figure>` tags. I don't know how that's structured but I guess that's causing the issue.

**Comment by AndrewDaGuy** [comment]
> Colors of images seem to be inverted or with a filter applied.

Yep, its inverted. The only reason I can think that it's weird is that there's some sort of darkish filter, if that gets inverted there would be probably turn into a white filter and that's why the images probably look weird, I guess.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/66189242/111104784-60519c00-8549-11eb-9645-bc763b8deb63.png">

<img width="538" alt="image" src="https://user-images.githubusercontent.com/66189242/111104812-70697b80-8549-11eb-9726-95acc0df8f40.png">
