### ISSUE TITLE
[BUG] DarkReader is DoS-ing our Jira server

### ISSUE THREAD

**Issue by bb1950328** [darkreader/darkreader#5387]
# Bug Report

## Describe the bug

This AddOn creates around 30 requests **per second** when I'm on our company's jira server. They all are redirected to our SSO service. Because of that, our admin noticed it in the log files. We then opened the jira website with the DarkReader AddOn enabled and disabled. The requests happen only when the AddOn is enabled so they have to be from DarkReader.

## Steps to reproduce

I'm not sure if this is on every jira server, but at least on our company's server it happens. I would try to set up a free plan of jira to test it, but currently I don't have time for that.

## Expected behavior

DarkReader doesn't send that many Requests

## Actual behavior

DarkReader sends around 30 Requests per second. They aren't visible inside the Dev-Tools of Firefox.

## System Information

- OS: Windows 10
- Browser: Firefox 87.0
- Dark Reader Version: 4.9.29

## Additional context

I have used DarkReader on Jira many times before and it wasn't a problem until today, so it's likely that this problem is introduced in a recent update of DarkReader, Firefox or Jira.

**Comment by Gusted** [comment]
Hi @bb1950328!

Not a lot of information to go on and as this is the first time with such issue regarding Dark Reader.

> They aren't visible inside the Dev-Tools of Firefox.

So then either they must come from the background-page.
When you open `about:devtools-toolbox?id=addon%40darkreader.org&type=extension` and go to network, do you see the requests that is being sent every 30 second?

Regards,
Gusted

**Comment by wolfaba** [comment]
Hi @Gusted,

Usually user comes to jira, SAML SP (simplesamlphp) do not find SAML session for jira, then redirects to IdP and user has to login or get from IdP valid SAML session for Jira. Sometimes the jira session expires but some JS code stays running on open jira page and tries to access jira and jira redirects to IdP for new SAML session, but IdP session is expired too and JS code cannot login. And this generates the some load on IdP server.

But in this case, user is logged in Jira, the Jira page is fully loaded, the network tab of webdeveloper tools in Firefox do not show any requests.

I have tested the addon on my firefox and after the Jira page is fully loaded, the Jira server does not show any access from my firefox, but the IdP server logs many access. So in this case, there are no redirects from Jira SP to IdP. I looks like the Addon is doing some sort of scan or caching itself. And from some reason, it's doing this scan on incorrect server. Maybe because there was a redirect from Jira to IdP at the beginning?

Do you know about some sort of this feature in this addon?

Even the `about:devtools-toolbox...` show no network activity. Really strange. BTW, the firefor generates high CPU load even if the page is already fully loaded. After some time, the requests to IdP stop. It really looks that something tries to read every found resources in some CSS or HTML.

I hope this will help you.

Regards.

Robert Wolf.

**Comment by Gusted** [comment]
Hi @bb1950328!

Thank you for the throughout information, I'm probably going to try run a local Jira server for this instance and check why in name Dark Reader is doing.

>  looks like the Addon is doing some sort of scan or caching itself.

Most likely scenario is that Jira is loading CSS/images that we have to scan and if we cannot access such CSS we send it to our background-script that can fetch without any restrictions and I think their is something within Jira that is refreshing every 30 seconds that causes us to fetch it and why it goes to the incorrect server? When we fetch such things we omit any credentials for security-sake whereby I guess the fetch doesn't have proper credentials and the SP sends it to IdR as it just things "Oh this user needs new session".

Just to make sure I'm not missing anything, do you have any other extensions loaded other than Dark Reader. Sometimes an combination of Extension can cause weird malfunctions.

Regards,
Gusted

**Comment by wolfaba** [comment]
@alexanderby I thought this too, but then I have found, that there are no requests on jira server, which means, firefox is requesting the URLs directly on IdP.

**Comment by Gusted** [comment]
Hi,

Oops, Sorry then I've read that wrong and that's indeed quite a lot more and concerning. As for that the user can use Filter(+) to not cause that problem. However it should be able to just handle Dynamic as it just should request some extra CSS and not have an constant 30 req/sec. That's more concerning that constant requests and how it's caused. I will try to poke a little more around sith my local Jira deployment and maybe some configuration caused it. But I'm unsure. 

As we cannot detect that it's being redirected to the Auth server etc, to fully anticipate that dynamic mode isn't a good option. 

Regards, 
Gusted

**Comment by wolfaba** [comment]
@Gusted I can confirm, that with Filter and Filter+ it makes no requests to IdP! Thank you. The Jira does not look as nice as with dynamic, but at least it works without doing DoS. Is the Filter/Filter+/Dynamic per site configurable or is it global? Dynamic configuration has better results, so bb1950328 could you Filter/Filter+ only for Jira server and Dynamic for all other sites.

**Comment by wolfaba** [comment]
@Gusted  thank you! it works perfect :-)

@bb1950328 you can set the filter or filter+ mode for jira server only, the colors are little bit different as in dynamic mode but at least you have dark mode for jira too

**Comment by Gusted** [comment]
Feel free to open a issue if their is something missing within the filter+ mode for Jira(white-ish area's etc).
