### ISSUE TITLE
Fixes in Dev Tools ignored after some time

### ISSUE THREAD

**Issue by unstope** [darkreader/darkreader#540]
When I add rules using Dev Tools, it works. But after some time (about 10-15 minutes) DarkReader starts ignoring these rules till I open Dev Tools and click Apply button. New rules do not dissapear from Dev Tools, they are just ignored for some reason.

**Comment by niawag** [comment]
Same for me: the fixes I made for Google Calendar are working fine (pull request: https://github.com/darkreader/darkreader/pull/698) but I need to reapply them from time to time or they are ignored

**Comment by stevencohn** [comment]
First, this is a fantastic extension! FWIW, I think the Dynamic engine is far better that the others even if it is slower to render. I know the author has commented that he has other priorities but... I would vote to concentrate on improving the Dynamic engine and addressing its bugs.

OK, so I see similar behavior, although happen far sooner than 10-15 minutes - just visited a new page might exhibit this behavior. The dynamic engine isn't always applied and I tend to keep open the Dynamic Theme Editor window in the corner of my screen just so I can hit the Apply button when it doesn't apply automatically. It seems to apply most dynamic things but not theme customizations specifically. If the problem is hard to fix, would it be possible add an interim "fix" like adding a shortcut key to the Apply button?

Thanks!

**Comment by stevencohn** [comment]
It seems that this problem has been resolved. For at least the last few days, maybe the last week, I haven't had to manually apply the dynamic theme after loading a page or revisiting a loaded tab. I'm not sure there has been a direct fix, maybe an inadvertent fix but I'm happy nonetheless! :-)
