### ISSUE TITLE
[BUG Possible] Disabling Dark Reader on a website may not yield as good of performance as setting Dark Reader to "Off"

### ISSUE THREAD

**Issue by Gitoffthelawn** [darkreader/darkreader#5470]
# Bug Report

## Describe the bug
Disabling Dark Reader on a URL may not yield as good of performance as setting Dark Reader to "Off".  They *should* be equivalent.

## Steps to reproduce
1. Disable DR on a website, but leave DR set to "On".
2. Go to the website and use whatever tools you prefer to evaluate its performance.
3. Repeat step 2 several times.
4. Set DR to "Off".
5. Go back to the same website and evaluate performance again.
6. Repeat step 5 several times.
7. If necessary, repeat steps 1-6.

## Expected behavior
One would expect the performance to be equivalent.

## Actual behavior
I'm still in the process of evaluating this *possible* issue, but before I spend more time on it, I want to ensure that my premise is correct that the performance should be the same in both cases.

## System Information

- OS: Windows
- Browser: Firefox 87.0 64-bit
- Dark Reader Version: 4.9.30 with version 5 preview enabled

## Additional context
If the performance should not be equivalent in both cases, feel free to close this as "not an issue".  If you have time, it would be helpful to indicate why the performance should not be equivalent.

**Comment by Gusted** [comment]
Hi @Gitoffthelawn!

Always appreciate this kind of toughs. So let me first say they have similar-_ish_  performance.
The only performance difference is behind the scene and on the website itself it has same performance(we inject the fallback style regardless and later on remove it when we can the signal we don't have to style this site).

**Explaination**
So when you disable dark reader(on/off button). We know for sure we don't have to style any page and thus we can simply send the `clean-up` command to the 'tab' whereby the fallback style is removed. 
On [this line](https://github.com/darkreader/darkreader/blob/v4.9.31/src/background/extension.ts#L400) we see it's being checked if the extension is enabled, if not [we send the clean-up](https://github.com/darkreader/darkreader/blob/v4.9.31/src/background/extension.ts#L454) command.

Now when you disable an particular site, we go trough different steps assuming the extension is enabled.
Now back at [the same line](https://github.com/darkreader/darkreader/blob/v4.9.31/src/background/extension.ts#L400) we have to execute the [isURLEnabled](https://github.com/darkreader/darkreader/blob/v4.9.31/src/utils/url.ts#L176) function, which is a bit of a performance eater, due to [this line](https://github.com/darkreader/darkreader/blob/v4.9.31/src/utils/url.ts#L183) whereby [that function](https://github.com/darkreader/darkreader/blob/v4.9.31/src/utils/url.ts#L59) has to loop trough the list and check if it's matching. This is all on the background while the website is loading etc and don't interfere with each other. When it finally see it's matching on the disabled site list, [we then send the clean-up](https://github.com/darkreader/darkreader/blob/v4.9.31/src/background/extension.ts#L454) command.

So is it similar performance? No. Does it impact the website? No. Because it impacts background-scripts and doesn't interfere with website.

When does this actually becomes a problem? When it either becoming slow or CPU is going to spike. Then any performance regulations with the current matching should be done within #2517 which relies on simple regex and has an cache built-in.

Regards,
Gusted

**Comment by Gitoffthelawn** [comment]
Hi @Gusted !

You're welcome, and thank *you* for the great explanation!

My time is very limited at the moment, and I'm hoping I'll have more time soon to reply in more depth.  But first, a quick question:  When Dark Reader is disabled via the on/off button, is the fallback style injected/removed on new tabs or new URLs on existing tabs?  Or is there supposed to be no performance impact at all when Dark Reader is toggled off?

Separately, and please excuse the brevity of this comments, but regarding *"which is a bit of a performance eater, due to this line whereby that function has to loop trough the list and check if it's matching"*, I wonder if that can be done much more efficiently.  Perhaps take a look at how uBO handles that sort of process, as it handles tens of thousands of filters and the main developer prides himself on writing efficient code (I haven't personally verified the efficiency of that code, however).

**Comment by Gusted** [comment]
Hi @Gitoffthelawn!

> When Dark Reader is disabled via the on/off button, is the fallback style injected/removed on new tabs or new URLs on existing tabs? Or is there supposed to be no performance impact at all when Dark Reader is toggled off?

In this case, the fallback style will still be applied to new tabs and as in the process removed pretty quickly afterwards.
The fallback code is very minimal and should run under 25ms. We could yield this by disabling injecting code when dark reader is disabled or before hand checking the website's URL #3921(which allows dynamic injecting and providing such logic to do this)





> I wonder if that can be done much more efficiently.

I wonder too :)

> Perhaps take a look at how uBO handles that sort of process, as it handles tens of thousands of filters and the main developer prides himself on writing efficient code (I haven't personally verified the efficiency of that code, however).

I had a brief look, but I couldn't figure out where the actual code for this is.

Regards,
Gusted
