### ISSUE TITLE
[BUG] DarkReader renders page incorrectly when page visibility API is disabled in chrome 

### ISSUE THREAD

**Issue by lvmm** [darkreader/darkreader#5591]
# Bug Report

## Describe the bug
I am using chrome extension https://chrome.google.com/webstore/detail/disable-page-visibility-a/eecfoibnnhheckhfokpihgefmlnenofb to disable page visibility API, and if this API is disabled DarkReader renders pages incorrectly in the background e.g. when link is opened with a middle click in a new background tab or when DarkReader is disabled and re-enabled.

## Steps to reproduce
Prerequisites: dynamic darkreader engine, dark mode, page visibility API is disabled.

1.    open wikipedia title page: https://en.wikipedia.org/wiki/Main_Page
2.    middle-click on "Welcome to Wikipedia" - new tab opens in the background
3.    switch to this tab
 
or

1.    open https://en.wikipedia.org/wiki/Wikipedia in a tab
2.    switch to another tab
3.    turn DarkReader off and back on
4.    switch to the tab opened in step 1

## Expected behavior
Page should've been rendered the same way as in the foreground.

## Actual behavior
Page text is monochromatic. Reloading the page in the foreground restores colours. I am using a similar page visibility API-disabling extension in Firefox but cannot reproduce this issue there, only chrome is affected.

## System Information

- OS: windows 10
- Browser: chrome 89
- Dark Reader Version: 4.9.31

**Comment by Gusted** [comment]
Hi @lvmm!

This sounds weird, but this is correct behavior, we cannot fully darken a page when it's on the background and when it switches to the foreground(visibility API) we then can fully darken the page without having a thousand workarounds for unforeseeable bugs that happens when it's in the background.

Now In Firefox we somehow get beforehand the event listener before that extension gets to cancel it and in chromium they get to cancel it before we can execute the code to darken the page.

Regards,
Gusted

**Comment by lvmm** [comment]
I don't get it: if visibility API is properly disabled, there should be no difference between background and foreground pages, they should either all be 'good' or 'bad', but they couldn't be different.

**Comment by Gusted** [comment]
> there should be no difference between background and foreground pages,

Well, yeah*

* No, internally within Chrome they still know the difference of course etc and thus will still treat it the same, but now sites + extension don't know the difference. I can see why you would disable it for sites, however extension can have a legitimate reasons for this. As I said before a lot of problems can happen especially DOM-wise(which we use quite a lot), when such page is still in background and can result in even more looking worse pages thereby, this code was originally implemented due to a behavior that when you would active a tab it could lead to Dark Reader double doing things. 



> they should either all be 'good' or 'bad', but they couldn't be different.

No, no. Like I said chrome still obviously knows the difference and will treat as such. However now you've disabled this API to websites/extension and thus we cannot anticipate on this and thus the code that darkens the page won't run as it will never get executed when you switch to the tab.

Regards,
Gusted
