### ISSUE TITLE
[Feature Request] Replace Dark Reader's CSS

### ISSUE THREAD

**Issue by 0J3** [darkreader/darkreader#5677]
# Feature Request

## Is your feature request related to a problem? Please describe

I am currently developing a website, and by default it uses a dark theme, which I would like to look identical with Dark Reader enabled. There is currently no way to replace what dark reader does, even by doing something like `border-color: #2a2b2c !important`.

## Describe the solution you'd like

Something like `--darkReader-[propName]: [colour]` for all proprieties dark reader replaces, which would allow me to do something like ```--darkReader-border-color: #2a2b2c;``` to replace the `border-color` propriety of the selected element, with `#2a2b2c`, regardless of what dark reader wants to replace it with

## Additional context

None

**Comment by 0J3** [comment]
In my use case, the site looks almost identical, with the exception of one border.

**Comment by Gusted** [comment]
Hi @0J3!

Such solution isn't possible because it will quite frankly do 2 things that are bad.
1. Collision with existing variables that we use with the --darkreader- prefix. 
2. "Regardless of dark reader wants to replace it with" I get that. Ain't that simple, it should look pleasant for the users such that it's correspondents to the settings of the users and if some website decides a hard coded value it will be very unpleasant to look at.

However you mention that's dark by default and thus can submit it to the dark-sites.config file.

Regards,
Gusted

**Comment by 0J3** [comment]
ok thanks for the reply!
