### ISSUE TITLE
[Broken Website] Coindera account automatically logs out on any action

### ISSUE THREAD

**Issue by fredddd1** [darkreader/darkreader#5692]
# Broken Website

## Website

app.coindera.com

## How to Reproduce

1. Login to the website.
2. Click on any link afterwards.
3. You get force logged out.

## System Information

- OS: Windows 20H2 64-bit
- Browser:  Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)
- Dark Reader Version:  4.9.32

## Additional context

@Gusted I have e-mailed you test credentials.

**Comment by Gusted** [comment]
Oh-oh, this is something. 
So their is this script that initiate the login process, however when dark reader is enabled it seems to be erroring:
![image](https://user-images.githubusercontent.com/25481501/116780961-13d20980-aa80-11eb-8813-a2ef7d050e31.png)
Thus not initiating the login process which probably causes the logs out after any link. Il try to understand why and how to fix this.

**Comment by Gusted** [comment]
Okay so after a lot of testing(Ah github comment says 1 hour ago so), I've come to 2 things.
They doesn't like external things.
Because I've seen this behavior:
I first tought, oh they probably don't like our styles and getting errored or something, so I've moved them to another place. But still the same behavior. However at the moment the style doesn't have any effect anymore(various way to achieve this) Coindera won't have a problem with us. This seems like they are checking for some security measure(I couldn't find) and we are affecting that? somehow. < It could be one of the widgets or embedded things. However I don't expect them to give such information about it as that's to malicious uses quite valuable. 

In this situations I recommend to use Static/Filter(+), or you could use an extension like Stylus and use:
[DarkReader-app-coindera-com.zip](https://github.com/darkreader/darkreader/files/6409546/DarkReader-app-coindera-com.zip)
to have the same effect minus the widgets as I suspect them 👀.

Regards,
Gusted

**Comment by fredddd1** [comment]
@Gusted I will mail them to see if they can make their website more compatible with the plugin.

Thank you for your efforts!
