### ISSUE TITLE
[Broken Website] A site turns pink

### ISSUE THREAD

**Issue by ItsMeHoppy** [darkreader/darkreader#5776]
# Broken Website

## Website
https://forum.cfx.re/

## How to Reproduce
Go to the site and wait for the site to turn pink.

## Expected behavior
Stay gray

## Actual behavior
The site loads while being gray in color but turns pink.

## Screenshots
![image](https://user-images.githubusercontent.com/46980766/117575714-609e8b80-b0e3-11eb-91bd-5c91382068bd.png)

## System Information
- OS: Windows
- Browser:  Brave: 1.24.82 Chromium: 90.0.4430.93
- Dark Reader Version: 4.9.32

**Comment by Gusted** [comment]
Hi @ItsMeHoppy!

This is very interesting, I thought how in the world this could happen from our side. Turns out the website is doing this:
![image](https://user-images.githubusercontent.com/25481501/117584605-6acd8380-b0fd-11eb-9f93-8ae5f0b69ac9.png)
This code is some kind of bypass? for some sort of issue? And due to this it makes every background-color pink.

I'm going to try reach out to them and ask them what in the world this code is and why they have it.

**Comment by blattersturm** [comment]
Ah. Sorry for consuming maintainers' time, there's not really any valid reason for this code to be here other than to make users respect(tm) design decisions and _perhaps_ showcase a little of "why do extensions have the ability to get detected?" limitations in modern-day UA extensibility.

**Comment by Gusted** [comment]
> Ah. Sorry for consuming maintainers' time

It's fine, got to know that subtree modifications includes changes to the textContent. Good to know for later.



> to make users respect(tm) design decisions

Respect design decisions? Just that an users wants to have a dark mode for any kind of valid reasons, shouldn't inpact how the UI or UX has been chosen.



> _perhaps_ showcase a little of "why do extensions have the ability to get detected?" limitations in modern-day UA extensibility.

Then we maybe should go ahead and show the abilities of javascript's prototype design by making our styles nilhil to textContent changes.

Just to be clear, if this isn't being removed due to any kind of reason either some long-running joke or to respect the design choices, we'll get an bypass for that bypass. As in the end of the day, some people really rely on any kind of dark-mode for there system and Il do whatever it needs to have that experience.

Regards,
Gusted

**Comment by blattersturm** [comment]
> Then we maybe should go ahead and show the abilities of javascript's prototype design by making our styles nilhil to textContent changes.

Except that would still lead to an infinite chain of fighting that would be resolved if UA vendors were to treat UA extensions as first-class citizens and not _bait_.

What is being used for perhaps benign reasons here (pink colors for presence of a style element) may very well be used in some arbitrary anti-fraud system, targeting black box or anti-ad-blocking trash, and would all be resolved if UAs would have, uh, proper extensibility again?

This check will be removed next time I'm at a desktop, _hopefully_ - it wasn't meant to stay there but seriously some users need to learn about lighting and monitor configuration and not shill "please add dark color option" stuff.

**Comment by vednoc** [comment]
> seriously some users need to learn about lighting and monitor configuration and not shill "please add dark color option" stuff

Dark mode is a part of accessibility and they have the have all the rights to request it. What a destructive way to showcase that extensions can be detected. People that use extensions chose to use them for a reason. It's in your best interests to improve the integration if dark mode isn't available natively.

No matter how much brightness you decrease on your monitor, the default light theme will still be more blinding than whatever dark theme is used. On top of that, some people prefer working in dim/dark environments. Besides, why would anyone have to change settings of their monitor just to use your website?

**Comment by blattersturm** [comment]
Oh, since you're continuing this argument...

> Dark mode is a part of accessibility

Referring to a color scheme option as some sort of global "mode" is a part of people shilling for a counterintuitive display option. 

Also, note the context of the linked site. It's about a video game that would already be difficult to impossible to play if visually impaired. 

> and they have the have all the rights to request it.

And we have all the right to mock people repeatedly bothering us with low-priority "requests". 

> People that use extensions chose to use them for a reason.

Cool, but usually this reason seems to be "wow dark color schemes are cool and we will mock anyone who even dares use dark text on a light background".

We choose to not offer a dark color scheme option for a reason, and similarly we'd like this choice to be respected, not circumvented with some generic extension that leads to various visual flukes that people then pin on us. 

> No matter how much brightness you decrease on your monitor, the default light theme will still be more blinding than whatever dark theme is used.

Incorrect, and an invalid comparison since "dark" color schemes are inherently unreadable on pleasant brightness settings for default light color schemes, leading to full white brightness having to be set higher and therefore be more blinding when using a "dark" color scheme.

> On top of that, some people prefer working in dim/dark environments. Besides, why would anyone have to change settings of their monitor just to use your website?

Sorry to break it to you, but you won't ever get a "perfectly dark world". It makes infinitely more sense to change a setting that _is_ possible to adjust globally (monitor brightness and environmental lighting) than be some sort of rebel and force "dark" color schemes on everyone everywhere.

If your crowd stops harassing everyone who posts a lighter color scheme screenshot in group chats or other communities, maybe I'll reconsider my standpoint, but until then, I'll be fighting the counter-fight to what your crowd is doing.

**Comment by vednoc** [comment]
> Also, note the context of the linked site. It's about a video game that would already be difficult to impossible to play if visually impaired in such a weird way as to need an oddly low light output.

Even if that's not the case, there are people that simply prefer using dark mode colors. I do, too, unless I'm in a very bright environment or if I'm using hardware that's not mine. We may account for a low percentage of total users, but that doesn't mean we don't exist.

> And we have all the right to mock people repeatedly bothering us with low-priority "requests".

You do have the right to do that, which is ridiculous to me, but don't be "that guy" when there is a way for your users to have the dark mode they want and/or need. By turning it pink, you're not doing anyone a favor.

> We choose to not offer a dark color scheme option for a reason, and similarly we'd like this choice to be respected, not circumvented with some generic extension that leads to various visual flukes that people then pin on us.

You can't enforce how someone uses your website. We're all different and thus what works for you doesn't mean it's going to work for someone else, and vice versa. If people pin those issues on you then I don't know what to tell you other than slap a "wonfix" and move on. They should know that some things won't be perfect.

> Incorrect, and an invalid comparison since "dark" color schemes are inherently unreadable on pleasant brightness settings for default light color schemes, leading to full white brightness having to be set higher and therefore be more blinding when using a "dark" color scheme.

Majority of people that use dark mode colors don't set their brightness levels on maximum. On multiple of my monitors, I keep brightness levels roughly the same in both modes, only in rare cases having to increase the brightness depending on the dark color-scheme that I'm using.

This will vary from person to person since accessibility about visual impairment is a rather huge topic, but it's also about personal tastes – I like having consistent colors across websites, and Dark Reader helps with that tremendously.

> Sorry to break it to you, but you won't ever get a "perfectly dark world".

I'm sorry to break it to you, but Dark Reader allows for a "perfectly dark world". It's not that perfect at times, but it's pretty damn good, and it's websites that do a bunch of weird things that cause things to break. Without any doubts, the web is much more usable with it than without it.

> If your crowd stops harassing everyone who posts a lighter color scheme screenshot in group chats or other communities, maybe I'll reconsider my standpoint, but until then, I'll be fighting the counter-fight to what your crowd is doing.

I haven't seen that in a long time. If someone occasionally makes a joke about it, I don't see that as something bad, but if someone does it constantly then release your ban hammer. You'll be fighting a fight that you can't win if you decide to go for it, but I hope you'll at least have fun doing so.

**Comment by blattersturm** [comment]
Right. Thanks anyway.

**Comment by Gusted** [comment]
> Oh, since you're continuing this argument...

Great now I will be too! I don't want to miss out on this awesome party. But it will be the last comment as well on this rather heated topic.





> Referring to a color scheme option as some sort of global "mode" is a part of people shilling for a counterintuitive display option.

Color scheme option, yeah it is. It's more referred to either the one or the other. Light mode or dark mode. anything otherwise can be categorized in those modes. Pink mode/color scheme, falls under light mode. darkblue mode/color scheme? falls under dark mode. 

> Also, note the context of the linked site. It's about a video game that would already be difficult to impossible to play if visually impaired in such a weird way as to need an oddly low light output.

What if someone wanted to read the FAQ, for say to find an email. Like me, I don't give a shit that FiveM is about modding Gta V.



> And we have all the right to mock people repeatedly bothering us with low-priority "requests".

Correct, that's your right to do so. I don't have a problem with that.

> Cool, but usually this reason seems to be "wow dark color schemes are cool and we will mock anyone who even dares use dark text on a light background".

I don't think so, we don't have any surveys or data on why people use dark reader. But from the people I've met over the years that uses dark mode, either it's due to a health issue(accessibility) or because white-ish color are burning your eyes and no that isn't solve by "oh let's turn the brightness down on this monitor or screen" so that we can even sit closer to the screen and check what's actually on the damn screen.




> We choose to not offer a dark color scheme option for a reason

That's okay I respect that.

> and similarly we'd like this choice to be respected, not circumvented with some generic extension that.

"No", sure that you'd like to have this choice respected.
The thing I respect that you don't offer it for your reason, but that doesn't have to mean that people can seek or create their own way of this dark mode. 

>  leads to various visual flukes that people then pin on us.

Well you don't have problem by closing issues about dark modes and now it's fucking pink you'd probably have more issues coming in about it, lucky @ItsMeHoppy has created an issue on the correct page, which I btw really appreciate.



> Incorrect, and an invalid comparison since "dark" color schemes are inherently unreadable on pleasant brightness settings for default light color schemes, leading to full white brightness having to be set higher and therefore be more blinding when using a "dark" color scheme.

Not sure how your monitor is color graded, I'd really like to advice checking it out if this is case with you. But a good made dark mode should be just as readable as light mode on the same brightness level. 






> If your crowd stops harassing everyone who posts a lighter color scheme screenshot in group chats or other communities, maybe I'll reconsider my standpoint, but until then, I'll be fighting the counter-fight to what your crowd is doing.

"your crowd" I can interpreter this as 2 ways
1. Dark reader's users, in that case I will personally tell them myself if I knew someone was doing it.
2. Some user that prefers dark mode, this is very little percentage I've never came across anyone in my years that actually harassed somebody due to this fact. So, yes might have happen to you by 1 or some users but that doesn't fucking mean every means it.
Caitlyn jenner is transgender and states "trans girls shouldn’t compete in girls’ sports". Does that mean this whole transgender crowd means this? NO it doesn't.


I think and see that you had bad experience with people that prefer dark mode and is mocking in the forums about it, I'm sorry but if they are harassing I don't stand behind it, I'm really sorry for you to deal with such people and make me clear that this extension doesn't not stand behind that behavior and that counterfeiting the dark reader extension won't solve that(I've just noticed that the pink making code is gone, thank you for that). Thereby you seems to have an issue with extensions? Please raise it to people that can actually do something with it, open up an issue with chromium and firefox but once again impacting extension due to that, won't help. Maybe it does by pressuring browsers, but in the end you've made a lot of people angry.

Regards,
Gusted
