### ISSUE TITLE
[Broken Website] signal.org

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5814]
Weird behavior.

Dark Reader not handle properly  twitter icon. Same selector (icon). Please investigate. 
```
signal.org

INVERT
.signal-logo
.icon
```

@Gusted 

![20210513-1620927678-001](https://user-images.githubusercontent.com/9846948/118164284-37536780-b423-11eb-853c-378160357670.png)
![20210513-1620927613-001](https://user-images.githubusercontent.com/9846948/118164286-37ebfe00-b423-11eb-90a2-6a085e8ae2a0.png)
![20210513-1620927599-001](https://user-images.githubusercontent.com/9846948/118164288-38849480-b423-11eb-810a-9c83ab669609.png)

**Comment by Gusted** [comment]
Ah this sucks, they use svg so technically we could modify the colors of the SVG but they inject it as background-image.

https://github.com/darkreader/darkreader/commit/bb2eca8b3c856249dcc7249a59cbd4f905ebf130 I'd really have to stop misclicking enter as that automatically push it as an commit instead of branch :)
