### ISSUE TITLE
[BUG] Grey backgrounds become a disgusting dark brown/yellow with dark reader on

### ISSUE THREAD

**Issue by mathsmathsmaths** [darkreader/darkreader#5854]
# Bug Report

## Describe the bug

For most with websites with light grey backgrounds (namely those without website fixes) Dark Reader injects CSS to make the background a very ugly dark brown-yellow which makes everything else on the page look out of place.
## Steps to reproduce

Example sites: Can't think of any off the top of my head but will update when I find one
## Expected behavior

applies a dark grey or black background
## Actual behavior

dark yellow-brown background is applied
## Screenshots

Again, will update when I find one
## System Information

- OS: macOS
- Browser: Chrome 88
- Dark Reader Version: 4.9.32

## Additional context

Got tired of doing local fixes so I opened an issue.

**Comment by Gusted** [comment]
Please actually put websites/examples before opening up a bug that nobody can investigate and/or fix.

**Comment by mathsmathsmaths** [comment]
@Gusted 

http://tibasicdev.wikidot.com/

A website I visit frequently for questions about TI calculators. Notice without Dark Reader and with it on

![without](https://user-images.githubusercontent.com/40340216/118859371-c3d8ac80-b89f-11eb-9ef0-903c9bcc5667.png)
![with](https://user-images.githubusercontent.com/40340216/118859381-c6d39d00-b89f-11eb-98a9-47d10b82e2cf.png)

The background of this site is not quite grey I know but it is very similar looking when I do stumble across one

**Comment by Gusted** [comment]
Other then some images that still has this grey-ish looks which due to limitations cannot be fixed, and that site already has this weird color-scheme whereby the colors tends to happen on the yellow color spectrum. If this is really a problem for you then I'd like to say that you take a look at modifying the filter settings for the site to set it right for your taste. 


    Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Than have a good look over at the "See all options" button.
