### ISSUE TITLE
[Feature Request] Recognize and ignore automatically QR Codes

### ISSUE THREAD

**Issue by FadeMind** [darkreader/darkreader#5891]
# Feature Request

Automatically recognize and ignore inverting QR codes on sites. 

## Additional context

When DR is enabled - QR codes are damaged. 

Sample: https://bilkom.pl/profil after login to system offer connect with goverment ID service (mObywatel). 
When DR is enabled app cannot recognize QR. 

Reference https://github.com/darkreader/darkreader/issues/16

**Comment by Gusted** [comment]
Hi @FadeMind!

Unless we want to make the current analyzing more complicated then it is at the moment, and want to spend time analyzing all canvas(on which most QR-codes are being drawn on) + watching them. It will be technically a lot of code whereby a simple CSS fix is just good enough. Thereby certain cases the QR code is good to go but the outline is being darkened(whatsapp web), thereby a CSS fix is more likely because the QR code itself is good to go.

Regard,
Gusted

**Comment by Gusted** [comment]
Not persuading this, CSS should be do it for now.
