### ISSUE TITLE
outlook.live.com display problem

### ISSUE THREAD

**Issue by holefrog** [darkreader/darkreader#5990]
The text color is black on this page. Makes it almost impossible to read.
![图片](https://user-images.githubusercontent.com/17289895/121282997-ff99eb80-c90c-11eb-84f2-d1a4f971f2a6.png)

**Comment by Gusted** [comment]
@alexanderby Root variables aren't being collected correctly?

**Comment by holefrog** [comment]
> 
> 
> @alexanderby Root variables aren't being collected correctly?

How to solve this problem?

**Comment by X-m7** [comment]
In my case turning dark mode off and on again (or whatever the `Alt+Shift+A` shortcut does specifically) makes it work, the colors make sense after that.

**Comment by geertvdheide1** [comment]
FYI: outlook.live.com has a pretty good dark mode of its own, so I'd recommend excluding the site from Dark Reader and turning the site's own dark mode on instead.

**Comment by DJ-Katalina** [comment]
Hello everyone,

I also (accidentally) made a duplicate report of this issue here: #6215. The issue was marked as solved there with #6217. My understanding is that we will have to wait for the next release of Dark Reader to have this fix.

@Gusted, do you agree? I believe this issue report can be closed with the fix implemented in the other issue report.

Thank you.

**Comment by Gusted** [comment]
> @Gusted, do you agree? I believe this issue report can be closed with the fix implemented in the other issue report.

ding ding, forgot to mark this one as resolved. Thanks for reminding!
