### ISSUE TITLE
[Question] How much bandwidth (estimated) did every user automatically syncing site fixes use? Can another CDN be used?

### ISSUE THREAD

**Issue by Rubydesic** [darkreader/darkreader#5991]
According to the README,
> Automatically syncing the site fixes to every Dark Reader user was disabled because the GitHub team doesn't allow using GitHub as a CDN. 

Could another [free] service or CDN be used, like CloudFlare + GitHub pages, or Netlify? How much bandwidth did this really consume?

**Comment by Gusted** [comment]
> Could another [free] service or CDN be used, like CloudFlare + GitHub pages, or Netlify?

Hmm we are now using raw.githubcontent.com which is from github itself to be fetched from. And by standard the fixes fetching are disabled as little percentage of users will need those fixes really immeditaly(most people who submitted issues will have them enabled after the issue was fixed) and with breaking changes that required a CSS fix a simple update will be pushed to ensure all users get it.



>  How much bandwidth did this really consume?

🤷🏽 enough to get a email from github stating that it isn't allowed to use it as a CDN.

**Comment by Rubydesic** [comment]
Yea, I think raw.githubcontent.com is not designed for high scale, but if you used GitHub Pages or Netlify + Cloudflare I think you'd easily be able to serve the data to all users, as the files themselves are pretty small. Guess it's not too important, though.

**Comment by Gusted** [comment]
>  Guess it's not too important, though.

+ I don't like to involve more third party URL's within the the extension and like I said people who want to have the syncing will be a small amount that github won't really care.
