### ISSUE TITLE
Styles are cached

### ISSUE THREAD

**Issue by LoganDark** [darkreader/darkreader#6075]
Dark Reader apparently now caches styles. That makes it impossible to fix the broken style when visiting websites based on mdBook (most of which are consistently broken all the time). The only solution is to turn off Dark Reader, refresh the page, and make sure the styles are fully loaded before toggling it for the first time.

Thanks to this caching behavior it is even more inconvenient to fix broken webpages.

# Broken Website
## Website
https://poga.github.io/lua53-notes
Most other websites based on mdBook 

## How to Reproduce
visit site

## Expected behavior
Syntax highlighting exists, header border isn't way too bright, the entire page doesn't share one background color

## Actual behavior
The exact opposite

## Screenshots
Broken:
![image](https://user-images.githubusercontent.com/4723091/122657804-93449680-d11b-11eb-8270-bbea18478fc4.png)

Non-broken:
![image](https://user-images.githubusercontent.com/4723091/122657807-98a1e100-d11b-11eb-8b50-93ce28e42dc7.png)

## System Information
- OS: Microsoft Windows 10 Home build 19041
- Browser: Google Chrome 91.0.4472.77 (Official Build) (64-bit) (cohort: Stable)
- Dark Reader Version: 4.9.33

## Additional context
Possibly similar problem to #3540?

**Comment by Gusted** [comment]
> Dark Reader apparently now caches styles

Hmh? You know more than I do. Did I miss something 😄?

Okay, so I totally understands why you see this as a caching thingy. As this is constant behavior and even while on/off(at least for me).

So finally after a exhausting week of school I finally had the perfect challenge to debug. Why are styles tagged as "loading"(in dark reader) while the site is setting them as disabled. Because as long styles are loaded, we don't remove the fallback style which is the style you're seeing at this moment.

So after asking my ~~rubber~~ duck, we came to the conclusion we where forgetting to call the `loadingEnd` function when we destroy the manager of the style(the manager makes sure to stay in sync with the original style and ensure the correct position in the DOM). So... that should be fixed with the patch I will send in any moment.

Regards,
Gusted's duck.

**Comment by Gusted** [comment]
#6078
