### ISSUE TITLE
Extension not saving static CSS

### ISSUE THREAD

**Issue by Remston** [darkreader/darkreader#612]
Extension don't saving user-static CSS from Stylish. After restarting chrome it simply drops all user-static CSS inputs.

**Comment by alexanderby** [comment]
I think the reason is settings size limit. Currently the extension is using Sync API, which shares the settings across all devices, it's just 8KB and can be extended up to 102KB. Local storage has 5MB size and can become unlimited if the extension asks additional permissions. So, maybe we should store custom CSS in local settings and also add the ability to clean up them.

**Comment by alexanderby** [comment]
I've published version 4.6.3. When there will be not enough space, you will be switched from sync storage to local (so your settings will not be synchronized across devices). There is a 5MB limit for local storage, if it will be exceeded, the extension can ask for unlimited storage permission (not implemented yet).

I hope the latest release didn't break anything.

**Comment by CollinChaffin** [comment]
@alexanderby I've peeked at the code but haven't gotten to it yet - once the 8k quota for sync is exceeded and per this change the switch is made to local storage, which DB is it then stored in?  Also, it then does not appear that the prior posted JS to manually export full config or site list then works because I'm only getting my old sync data before the switch occurred.

So, the reason I'm asking here is for the new local location but my intent is that I need to find a way to at least backup (and is restore even still possible) once utilizing local storage.

TIA!
