### ISSUE TITLE
Import / Export Site List

### ISSUE THREAD

**Issue by popey456963** [darkreader/darkreader#615]
Dark Reader has improved enough that I'm considering switching it on by default and only disabling it for sites that are broken.  However, currently I don't want to do that due to my inability to switch back at a later stage whilst keeping my enabled / disabled sites list.

A way to export / import a list so that I don't have this concern anymore would be great.

**Comment by ylluminarious** [comment]
@alexanderby Do you have an equivalent script for  Firefox? I am also interested in having a backup of my settings.

**Comment by alexanderby** [comment]
Same script should work for Firefox, [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging#The_Add-on_Debugger) are the steps for opening the debugger.

**Comment by ylluminarious** [comment]
@alexanderby Ok, the script "worked" after following those steps, but the JSON value is totally empty. It simply returns:

```
undefined
{}
```

**Comment by rolagg** [comment]
Try to use this:
```
chrome.storage.sync.get('siteList', (settings) => console.log(JSON.stringify(settings, null, 4)));
```
If doesn't work, change `chrome` to `browser` at the beginning.

**Comment by ylluminarious** [comment]
@rolagg Thanks! Your command there worked and I also appreciate having the reference to the other commands given by @alexanderby in #666.

**Comment by ylluminarious** [comment]
@alexanderby FYI, it would still be quite useful to have a built-in way to do this since setting the preferences via the console can result in an error from Chrome:

```
{message: "QUOTA_BYTES_PER_ITEM quota exceeded"}
```

This error is triggered when the settings are too large, i.e., too many sites, too many customizations, etc. I imagine this could be an issue for a number of people who want to restore a backup of their settings so it would be great if we had a built-in way to do this (like a JSON editor).

**Comment by FolkSong** [comment]
Is there a way to export from Chrome and import into Firefox, or vice-versa?

**Comment by popey456963** [comment]
@FolkSong The data seems the same for both, so you should be good to just export it from Chrome and import it into Firefox.

**Comment by AxJ11** [comment]
Isn't there any easier way to achieve doing sites & settings data backup?
I'm so lost on "click Inspect popup, open Console tab, ..."  from there on.  XD
I don't see it when I right-click on the icon.  Sad.

**Comment by alexanderby** [comment]
If you are signed in into Chrome and Firefox, the settings should be synced (if settings size didn't exceed 8KB). It is planned to add a Settings section and place all the settings, that are not used frequently.

**Comment by minikold** [comment]
Also excited for this. Most extensions hold their config in a file that is in the Extensions folder, so if just transfers over. This one doesn't seem to. Using a file change monitor, there are no changes to any of the files when editing the site list.

I'm interested for this to be added somehow, as I'm switching from Chrome to Brave, and don't want to have to manually re-add all my of sites.

**Comment by CollinChaffin** [comment]
Hi @alexanderby sorry I just posted in the wrong issue (similar one that's closed) so I'll repost here since this is the open one.

Question:  When the quota is exceeded and switched to local storage it appears I then get an outdated list from sync (from when it switched). What DB is the local storage using if I need to back it up after the switch? TIA!

**Comment by CollinChaffin** [comment]
I'll post the answer here for everyone that are power-users like me of this extension and have quickly exceeded their sync quota.  I know there is refactoring in the works so hopefully in the future this becomes easier, but my solution (IMO) is actually even easier than the above - plus you can restore just as quickly!  

Unfortunately, this also means that until the refactoring can hopefully prompt to expand the sync size and go back to full sync, the syncing does in fact stop proven by my VERY outdated site list which did successfully export using the above commands.  

**So, beware that you MUST know if you've already exceeded because once you have, your export data will NOT be up to date!**

## Instructions for Import/Export of all DarkReader Settings from LocalStorage

1. Install the following Chrome extension (**I am not affiliated with this extension nor do I take any responsibility**):
a. https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb
2. Right-click the DarkReader toolbar button and click `Inspect Popup`
3. Click the new tab in the devtools window labeled `Storage Explorer`
4. There you will see ~10 key/value pairs including the `siteList`, `customThemes`, and current theme
5. Click the `notepad/pen icon` at the right of each you wish to backup/restore to open the values
6. Copy/Paste the `data` you wish to backup or restore
a. If backup, click `cancel` and paste into a file and save with `.json` extension
b. If restoring, past your backup data and click `save`

**Comment by doronbehar** [comment]
Does anybody here knows if there a sync quota for Firefox as well? I don't get my sites lists synced at all and I have a lot of machines I'm logged in to Firefox on them (University computers farm). 

BTW since I've had the chance to inspect this issue thoroughly, I've managed to discover a most annoying inconvenience - after _every_ new Firefox Login (which installs the extension), all other Firefox sessions forget the sites lists and themese already configured for them.  @alexanderby are you aware of this issue? Solving https://github.com/darkreader/darkreader/issues/444 would help in this manner...

**Comment by fgimian** [comment]
After some further digging, I found another way to obtain these settings and restore them later for Firefox.

**Note**: The following instructions assume you are quite comfortable with the terminal and have SQLite3 installed on your chosen system.

You'll first need to exit Firefox before you begin, as it locks the SQLite database we'll be working on.

Now, browse to your profile directory and issue the following commands (read and understand before running of course):

```bash
# On the old system, backup all Dark Reader settings to dark-reader-settings.sql
sqlite3 storage-sync.sqlite \
    ".mode insert collection_data" \
    "SELECT *
     FROM collection_data
     WHERE collection_name = 'default/addon@darkreader.org'" \
    > dark-reader-settings.sql

# On the new system, clear all Dark Reader settings
sqlite3 storage-sync.sqlite \
    "DELETE FROM collection_data
     WHERE collection_name = 'default/addon@darkreader.org'"

# On the new system, insert all the settings you saved earlier
sqlite3 storage-sync.sqlite ".read dark-reader-settings.sql"
```

Using this approach at least makes it easier to automate and requires less clicking around :smile: 

Hope this helps someone
Fotis

**Comment by Gusted** [comment]
In the next update of Dark Reader this will be a function.

**Comment by OzakIOne** [comment]
Any news about this feature ? I searched for it in v 4.9.22 and it doesn't seem to have a export/import button for site list

**Comment by ylluminarious** [comment]
Yeah, I've been forward to this feature too, but haven't seen it yet for several months...

**Comment by Gusted** [comment]
Click Dark Reader icon.
    Click Dev tools (in the bottom-right corner).
    Click Preview new design.

Then in the popup Under Settings Under Manage Settings, you will find an Export/Import Settings button.

**Comment by prohtex** [comment]
> ```
> Click Dark Reader icon.
> Click Dev tools (in the bottom-right corner).
> Click Preview new design.
> ```
> 
> 
> Then in the popup Under Settings Under Manage Settings, you will find an Export/Import Settings button.

Not seeing this setting in Safari...

**Comment by Gusted** [comment]
> Not seeing this setting in Safari...

Darkreader for Safari has another codebase, whereby I don't know if the next update(their is an update or by now released) includes this setting.

**Comment by prohtex** [comment]
> > Not seeing this setting in Safari...
> 
> Darkreader for Safari has another codebase, whereby I don't know if the next update(their is an update or by now released) includes this setting.

Is it possible to migrate the settings manually in Safari by copying a preferences file?

**Comment by Gusted** [comment]
> Is it possible to migrate the settings manually in Safari by copying a preferences file?

I don't know. I don't have any experience/knowledge about Safari.

**Comment by Termuellinator** [comment]
> > Not seeing this setting in Safari...
> 
> Darkreader for Safari has another codebase, whereby I don't know if the next update(their is an update or by now released) includes this setting.

It doesn't work on firefox either, albeit i would assume chromium and firefox share most of the codebase?

**Comment by itaranto** [comment]
> After some further digging, I found another way to obtain these settings and restore them later for Firefox.
> 
> **Note**: The following instructions assume you are quite comfortable with the terminal and have SQLite3 installed on your chosen system.
> 
> You'll first need to exit Firefox before you begin, as it locks the SQLite database we'll be working on.
> 
> Now, browse to your profile directory and issue the following commands (read and understand before running of course):
> 
> ```shell
> # On the old system, backup all Dark Reader settings to dark-reader-settings.sql
> sqlite3 storage-sync.sqlite \
>     ".mode insert collection_data" \
>     "SELECT *
>      FROM collection_data
>      WHERE collection_name = 'default/addon@darkreader.org'" \
>     > dark-reader-settings.sql
> 
> # On the new system, clear all Dark Reader settings
> sqlite3 storage-sync.sqlite \
>     "DELETE FROM collection_data
>      WHERE collection_name = 'default/addon@darkreader.org'"
> 
> # On the new system, insert all the settings you saved earlier
> sqlite3 storage-sync.sqlite ".read dark-reader-settings.sql"
> ```
> 
> Using this approach at least makes it easier to automate and requires less clicking around smile
> 
> Hope this helps someone Fotis

This doesn't work with `storage-sync-v2.sqlite`.

**Comment by kevinlekiller** [comment]
> 

Export: `sqlite3 storage-sync-v2.sqlite ".mode insert storage_sync_data" \ "select * from storage_sync_data where ext_id='addon@darkreader.org';" > dark_reader.sql`

Clear: `sqlite3 storage-sync-v2.sqlite \ "delete from storage_sync_data where ext_id='addon@darkreader.org';"`

Import: `sqlite3 storage-sync-v2.sqlite ".read dark_reader.sql"`

**Comment by sepo27** [comment]
Most recent instructions on how to import/export site list in FIrefox
```

# Inspect extention

1) Type in the Firefox search bar: about:debugging
2) Lookup "Dark Reader" extension and hit "Inspect" buttom
3) Navigate to "Console" tab

# Export site list

browser.storage.sync.get(null, config => console.log(JSON.stringify(config.enabledFor, null, 2)))

# Import site list

const siteList = {exported_site_list_raw_array};

browser.storage.sync.set({ enabledFor: siteList })
  .then(() => console.info('OK!'))
  .catch(err => console.error('FAILED !', err));

# Reload (for extension to re-read from storage)

browser.runtime.reload()
```
_(ℹ️ See [debugging FF extensions here](https://extensionworkshop.com/documentation/develop/debugging/))_

**Comment by sepo27** [comment]
👍 for the import/export UI
