### ISSUE TITLE
[Feature Request] Proper treatment of `about:blank` pages

### ISSUE THREAD

**Issue by elibarzilay** [darkreader/darkreader#6151]
# Feature Request

## Is your feature request related to a problem? Please describe

When a window is created in JS with no URL it gets a `window.location` of `about:blank`:

    win = window.open("", "_blank");
    win.location.href // => "about:blank"

These windows are currently mistreated by darkreader in that there is no way that I see to turn it on/off for such a specific page.  Even more than that, the darkreader dropdown on these pages look like something went bad somewhere: there is the top on/auto/off at the top, but clicking the buttons does nothing, and there is nothing else below them (none of the regular UI).

It makes semi-sense to just ignore such pages, since they seem to come from nowhere and it's still good to avoid the jarring sea of bright whiteness if you happen to run into one of them, *however* there are valid uses of such windows, but there's no way currently to disable darkreader for them other than turning it off globally.  (See below for further context.)

## Describe the solution you'd like

For such `about:blank` windows, it makes sense to use their `window.origin` to decide how to treat them.  This way a blank window that was opened from `https://foo.bar/` would be treated as *that*, so if I disable darkreader for `foo.bar`, it would also be disabled on `about:blank` windows it spawns.

## Additional context

What I ran into is an issue with my home-cooked music player, which can use such windows for visualizations.  (Why?  Because having multiple monitors all showing changing colors in sync is a very nice thing...)  My code does something like:

    win = window.open("", "_blank");
    win.document.body.style.background = "#fcc";

but that doesn't work since darkreader gets in its way, and there is no way to turn it off locally.  But if you look at `win.origin` you'll see where it originated.

**Comment by Gusted** [comment]
Hi @elibarzilay!

This is a security restriction(from what I [see it](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/WebExtensionPolicy.cpp#716)) by the browser and disallow any extensions(no mater what) to be matched with `about:blank` that is created from another context, in this case from a website. So we cannot give a proper treatment to `about:blank`, because browsers disallows us. And yes I've checked the permission etc to get around this, but looking from the source-code it's a hard no from the browsers to extensions.

Regards,
Gusted

**Comment by elibarzilay** [comment]
@Gusted, um, I'm confused then: the source of my problem is trying to *disable* darkreader from doing its thing on these `about:blank` windows -- but what you're saying sounds like it shouldn't be possible for it to do anything in the first place (which is clearly not the case for me).

**Comment by Gusted** [comment]
Uhm, wait... Dark reader is enabled on those pages? I'd really need a demo to test that out. Because we aren't allowed on most `about:blank`.

**Comment by elibarzilay** [comment]
Here's a [quick demo](https://tmp.barzilay.org/DarkReader.webp) and [an annotated version](https://tmp.barzilay.org/DarkReader-annotated.webp) (the crappily blinking texts).

**Comment by Gusted** [comment]
Do you have by any chance the `Enable on restricted pages` enabled? Because such top-level "about:blank" are in chromium partially enabled for extension. And the option was purely for things like the chrome webstore if the correct `chrome://flags` was enabled. But it seems like the code is incorrectly constructing a URL for `about:blank` so that should be easy fix.

**Comment by elibarzilay** [comment]
.... maybe?  I'm not sure whether "access to file urls" covers it or not, see screenshot below.  Also: it does *not* seem to work on `about:blank` (when opening explicitly), and on web store pages.  (And I think that Chrome behaves the same as edge does, but I can test things if it'll help.)


![image](https://user-images.githubusercontent.com/185905/123702347-00011480-d831-11eb-8bf1-b21bfb39e21e.png)

**Comment by Gusted** [comment]
#6154 fixes the issue.

**Comment by elibarzilay** [comment]
@Gusted: thanks for the quick fix!  -- I tried to build and install it locally, and it looks like your fix makes the UI appear, which allows me to disable `about:` pages, but it doesn't do the bit of treating it as the origin site, right?  (I tried to look at the code but got lost.)

**Comment by Gusted** [comment]
We have to treat such sites on its own. They might have been created by your cat or your dog or some website but they are a new tab on some obscure empty url, because in such cases I frames would've been the same story which is more or less the same. The PR for now fixes the bug, the behavior is another topic.

**Comment by elibarzilay** [comment]
It's not really random -- like I said, `window.origin` has the site that started it, and this would only be something to use if the url is empty, which means that a new tab or an iframe would behave the same as it is now, and it's only an empty one that would behave according to the url of whoever made it.

**Comment by Gusted** [comment]
> It's not really random -- like I said, `window.origin` has the site that started it

Correct, and we can see that when we get a "notifcation" when a new content script has been injected into a tab. 

However if we query the tab from the background-script, such information isn't available and thus we cannot correctly handle the tab if we say "oh this tab belongs to origin x so we say in the pop-up it's site x", well in the background-script we cannot see such information anymore after any period of time.

> if there's an iframe with no url, then it makes sense to treat it according to its origin too

IFrames are special, such information can be recalled from querying tabs, from such that we can make sense from it. Also IFrames are in the site itself and not on a new tab and will be treated with care. 

Regards,
Gusted
