### ISSUE TITLE
[Performance] Dark Reader adds more than 10 seconds to Gmail load time

### ISSUE THREAD

**Issue by MahdiNazemi** [darkreader/darkreader#6161]
# Performance Issue

## Website
[mail.google.com](mail.google.com)

## How to Reproduce
Open [mail.google.com](mail.google.com)

## Performance Profiler
-
Performance with Dark Reader disabled: -

## System Information

- OS: macOS
- Browser: Firefox 89
- Dark Reader Version: 4.9.31

## Additional Information

- Gmail loads much faster when Dark Reader is disabled.
- The same issue is there in other browsers.
- Hardware acceleration is enabled on all browsers.

I understand that other users have reported this issue in the past. However, because the information shared by other users' profilers has provided insight into speeding up Dark Reader, I thought this new profiling information might be helpful too.

**Comment by Gusted** [comment]
Hi @MahdiNazemi!

Thanks for reporting this issue, the profiler looks pretty interesting and will have a more in-depth look this weekend, especially because some things are out-of-control and might indicate performance issues with Firefox itself. At least that looks to me that way given just a 10 minute look.

Regards,
Gusted

**Comment by MahdiNazemi** [comment]
Thanks for taking the time to look at the profiler's outputs.
I've had the same issue in Brave as well. I'll try to run Brave's profiler and share the results here.

**Comment by Gusted** [comment]
Hi @MahdiNazemi!

I had another look today and some functions that are frequently used in dark reader to be somewhat slow(if you add all the instances of it) and are now being optimized by #6175 and #6174 I found some other issues but that's mainly due to the browser being slow(a lot of built-in functions and properties are somewhat expensive) so that will take some more time to verify and get fixed. But #6175 and #6174 will do it for on gmail. 

Regards,
Gusted

**Comment by MahdiNazemi** [comment]
Thank you for taking the time to improve the performance of Dark Reader!

**Comment by rakleed** [comment]
@Gusted does #6174 and #6175 fix the problem with opening Gmail, using it for a while, then switching to another tab for a few minutes, and after returning to the tab with Gmail, you need to wait 5-15 seconds for the interface to start responding user?

**Comment by Gusted** [comment]
@rakleed These 2 PR should improve the startup performance on Gmail, #6259 should be the best improvement for Gmail and uses an experimental "manager" which I hope to use more in the future which can drastically improve startup performance for websites(by slowly "delaying" certain code).

**Comment by rakleed** [comment]
@Gusted I built a version from the source, the problem I described practically doesn't appear now.

And why aren't you doing builds in GitHub Actions? This would be much more convenient for testing PRs.

**Comment by Gusted** [comment]
> And why aren't you doing builds in GitHub Actions? This would be much more convenient for testing PRs.

Because most PR's don't need builds(config changes / refactors) And if their are PR's that are note-able to test out I mostly will already comment a binary.zip to test it out. As well running `npm run build` will slow down the PR as a whole.

However, I could check we can make github actions as a bot that can respond to specific comments like building a PR.

**Comment by Gusted** [comment]
> However, I could check we can make github actions as a bot that can respond to specific comments like building a PR.

Apparantly github's current API doesn't allow to upload direct files, so that's a idea I have to let float.
