### ISSUE TITLE
YouTube Header

### ISSUE THREAD

**Issue by daephx** [darkreader/darkreader#618]
No matter how many times I mess with the "Dev-Tool", YouTube is so inconsistent In how the header is rendered, flipping between inverted and uninverted at the click of a refresh.

![youtube](https://user-images.githubusercontent.com/36192863/42718700-32e5179a-86c0-11e8-8a74-7822fcc9de2a.PNG)

It's relatively the same for the persistent sidebar on the main webpages but I somehow got that to quit being a jerk.

Edit: Soundcloud has a similar issue

**Comment by alexanderby** [comment]
Are you using a Filter mode? Try using Dynamic mode. Unfortunately YouTube style sheet structure is too complex and Dark Reader dynamic mode sometimes has errors like black on black text when writing a comment. Try using built-in dark mode for YouTube and add it into exceptions list.

**Comment by DaemonPhoenix42** [comment]
I'll give it some tinkering, while dynamic mode was a nice addition and could work I am not a big fan of the color scheme for some sites, at least for youtube I prefer the full black aesthetic as opposed to there the internal dark theme or the other modes.
iirc while messing with it Filter+ seemed interesting because it corrected some of the colors for videos/thumbnails, most notably the reds were far less desaturated. can't recall If it brought about other issues though.

Anyway, thank you for your time!
