### ISSUE TITLE
[Feature Request] Requesting dark sites config files

### ISSUE THREAD

**Issue by Hexiro** [darkreader/darkreader#6406]
# Feature Request

_The Problem:_
Currently, the global dark list is hardcoded into the extension. This means its only ever gets updated after a new version of dark reader is released.

_The Solution:_
It would be nice if under the darkreader organization, a new repository called like "config" or something is created. This seperate configuration can be requested by the extension and cached for a day to a week. In doing this, the global dark list would be updated more frequently on the client. Additionally, this will move "Added dark sites" contributions to this new repository, where other maintainers could possibly update the global dark list, making the darkreader repository have more meaningful contributions.

_Screenshots_
None

_Additional Context_
None

**Comment by Hexiro** [comment]
let me know what you think!

**Comment by Gusted** [comment]
Hi @Hexiro!

Currently it's hardcoded and will stay that way, but you can simply override that behavior, [see](https://github.com/darkreader/darkreader#site-fixes).



> It would be nice if under the darkreader organization, a new repository called like "config" or something is created.

That's something I've discussed with some other people and we trying to get that working, after trying to defeat some technical difficullties by moving around existing file with a good amount of git history.



> This seperate configuration can be requested by the extension and cached for a day to a week

No, no, no. That's something that was requested a lot, but that can't happen as still something in that amount of users the traffic will be enormously huge. And something to consider is that 95%+ People won't benefit from having the latest config as these days a lot are edge-cases and major ones are more likely fixed with code.


Regards,
Gusted

**Comment by Hexiro** [comment]
Ah yes! what you've pointed out makes a lot of sense. Thank You!
