### ISSUE TITLE
[Bug] Darkreader Doesn't work on MacOs since Firefox v91

### ISSUE THREAD

**Issue by RAMilewski** [darkreader/darkreader#6465]
# Bug Report

## Bug Description
Darkreader stopped working in Firefox 91.  It was working well in Firefox Developer edition up through 90, when Dev Ed switched to 91.0b1 it stopped working.  Today Firefox updated to FF 91 and FF Dev Ed to 92.0b1, and dark reader no longer functions in either.  Removing Darkreader, restarting the browser and re-adding it to Firefox 91 or 92 does not help.  It's working fine in Chreme Version 92.0.4515.131 on the same machine.  

## Steps To Reproduce
Install the Darkreader add-on in Firefox 90 and upgrade to Firefox 91 
Click on the icon in the toolbar.
The Darkreader pop-up will open, but it will have a white backgroun and will have no effect on the web page. 

## Expected Behavior
It should allow me to change the appearance of the web page.

## Actual Behavior
See the screenshot

## Screenshots
![Screen Shot 2021-08-10 at 5 20 19 PM](https://user-images.githubusercontent.com/702294/128951273-f4a3c94d-05f8-4b49-8325-7419e669d2ad.png)

## System Information
Firfox 91 and Firefox Developer Edition 92.0b1 and 92.0b2.  Results the same on all these versions. As well as all of the DevEd 91 versions from 91.0b1 and higher.
MacOS 10.14.6 on a Late 2012 iMac.  3.4GHz Intel Core i7  32 GB RAM  Graphics: Nvidia GeForce 58MX 2GB
Dark Reader Version 4.9.34

## Additional Context
I'm a "Type 2" user. (Comment #6032)  So I'm stuck using Chrome for now.

**Comment by Gusted** [comment]
Hi @RAMilewski!

Thank you for a report, so since Firefox [v91](https://www.mozilla.org/en-US/firefox/91.0/releasenotes/):

```
Firefox now automatically enables High Contrast Mode when "Increase Contrast" is checked on MacOS
```

You most likely have this enabled and thus Firefox will invert/modify every color even those modified by dark reader which will result in white-ish color. You can disable this behavior from Firefox with:

- Go to `about:config`.
- Search `browser.display.document_color_use`.
- Modify the value to `1` which corresponds to the value [never](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/test/xpcshell/test_ext_browserSettings.js#268).

Regards,
Gusted

**Comment by RAMilewski** [comment]
That mostly solved the issue.  Interestingly, DarkReader still doesn't work on our WordPress site that I took the screenshot of when I filed the bug.   It did before FF 91.  It also doesn't work on Thingiverse.com, and if I remember correctly that also worked before.   No need to reopen the bug.  I'll poke around a bit and see if I can figure something out.  I'll also start a list of sites where it fails and pass that along if it's of interest.
![Screen Shot 2021-08-13 at 5 22 51 PM](https://user-images.githubusercontent.com/702294/129429054-db3f8f08-9a2d-4c77-b0f3-99d56117e636.png)
