### ISSUE TITLE
[Bug] ditu.baidu.com's poi details pop have messed up styles after url rewrite

### ISSUE THREAD

**Issue by felixonmars** [darkreader/darkreader#6480]
# Bug Report

## Bug Description

The poi details popup box (located on top-left part of the webpage, when you click on any poi on the map) have messed up styles, as long as there is a url rewrite (clicking on the map to show the box, or change to another poi, will trigger such rewrite), when darkreader is enabled.

## Steps To Reproduce

(In the screenshots below, I have removed all dynamic-theme-fixes for this site to make sure that they have no relationship with this bug. The bug is also present when the fixes are present, of course)
- Go to https://ditu.baidu.com/poi/%E4%B8%AD%E5%B1%B1%E5%85%AC%E5%9B%AD/@12725273.29,3558757.28,12z?uid=ecc3089e9e94bd7e28201a1e&info_merge=1&isBizPoi=false&ugc_type=3&ugc_ver=1&device_ratio=2&compat=1&querytype=detailConInfo&da_src=shareurl
- Note that the box is currently shown correctly like the following:
![image](https://user-images.githubusercontent.com/1006477/129152051-6fb219bd-f97c-4dab-832f-4363bcb6938d.png)
- Click on another park (green tree-like icon on the map, there are many)
- Note that the box is now messed up, like the following:
![DeepinScreenshot_select-area_20210812145910](https://user-images.githubusercontent.com/1006477/129152178-96e5cb3a-3551-48db-acfd-5b42266961a6.png)
- Refresh the web page and see the correct info box of the new poi.

## Expected Behavior
The original functionality of the map should not be broken.

## Actual Behavior
One has to refresh the webpage to get the correct info box back.

## Screenshots
Already pasted in the steps above.

## System Information

- OS: Arch Linux x86_64 
- Browser: Firefox 91.0
- Dark Reader Version: 4.9.34

## Additional Context

n/a

**Comment by Gusted** [comment]
Hi @felixonmars!

This seems like a odd website to me as it seems to be loading 24/7 
![image](https://user-images.githubusercontent.com/25481501/129184549-43aa58b7-91cf-4e3f-8291-322d1c4ea169.png)

And because of this inifinte loading, firefox won't show any elements on the inspector because it's technically still loading.
![image](https://user-images.githubusercontent.com/25481501/129184660-9423bf86-fa53-4c22-b3a1-ce2a15c07ff0.png)

It seems like it will only happen once dark reader is enabled on the site, but because I can't debug it at all. I can't even setup breakpoints for some reason - at least they aren't hitting them. The firefox profiler shows it's somehow stopping at a function and then dark reader just does nothing. I'm going to scratch my head on this one and hopefully figure out what's going on. I was actually able to hit that weird pop-up menu but I'm going to assume that's because of this whole weird site is still loading.

Regards,
Gusted

**Comment by felixonmars** [comment]
That's unfortunate :( I'm afraid a lot of Chinese websites have really poor performance abroad.

**Comment by Gusted** [comment]
> That's unfortunate :( I'm afraid a lot of Chinese websites have really poor performance abroad.

I've noticed that, I wasn't able to reproduce it with enabling dark reader after the site is loaded. And seems like only to happen on load-up of the tab.

**Comment by felixonmars** [comment]
> I've noticed that, I wasn't able to reproduce it with enabling dark reader after the site is loaded. And seems like only to happen on load-up of the tab.

Applying dark reader after site loaded seems to work for me too, but it's still reproducible here after clicking any other poi on the map.

**Comment by Gusted** [comment]
I was somehow able to get the page loading(with forcing darkreader to disable after a while) and was able to inspect the elements. And found the maybe culprit, their seems to be 1 `<style>` element that is dynamically injected and after that get multiple text nodes injected.

I suspect it's injecting into a dark reader style when it's enabled. However I still can't use breakpoints for some reason.

Luckily my lovely rubber ducky was able to find some piece of code which seems to be used on `baidu.com`.

```javascript
(Unobfuscated)


    var headEL = document.getElementsByTagName("head")[0];

    ...
    
    function WoewAwesomeFunction223(passedArg) {
        var documentObject = document,
            argument1 = passedArg,
            headElement = headEL,
            elementsWithStyle = headElement.getElementsByTagName("style");
        if (0 == elementsWithStyle.length) {
            if (documentObject.createStyleSheet) {
                documentObject.createStyleSheet();
            } else {
                var newElement = documentObject.createElement("style");
                newElement.setAttribute("type", "text/css"), headElement.appendChild(newElement)
            }
            var firstStyleElement = elementsWithStyle[0], mediaOfStyle = firstStyleElement.getAttribute("media");
        }
        null == mediaOfStyle || /screen/.test(mediaOfStyle.toLowerCase()) || firstStyleElement.setAttribute("media", "screen"), firstStyleElement.styleSheet ? firstStyleElement.styleSheet.cssText += argument1 : firstStyleElement.appendChild(documentObject.createTextNode(argument1))
    }
```

As you can see in this code that my rubber ducky somehow found(totally not on baidu), it will check if their is an existing `<style>` element(which probably is because we use that a lot) and inject new text nodes into that element. I will see if we can make a workaround for their `getElementsByTagName` function to ensure they don't receive any of darkreader's style.

Regards,
Gusted's dog.

**Comment by felixonmars** [comment]
Wow that explains a lot. Many thanks!
