### ISSUE TITLE
[Question] question regarding thunderbird add-on "Dark Reader" (minimal delay)

### ISSUE THREAD

**Issue by Rosika2** [darkreader/darkreader#6600]
# Question

Hi all,

I´ve got a question regarding the add-on "Dark Reader" for thunderbird.

Info:

my system: Linux/Lubuntu 20.04.3 LTS
           thunderbird 78.11.0
           Dark Reader 4.9.34.1
           
This is a great add-on and I need it very much because "normal" html e-mails with black letters on white background produce quite a strain on my eyes. So "Dark Reader" is exactly what´ve been looking for.

It works really well.

I´ve just one question for better understanding:

Whenever I click on an e-mail (no matter whether normal text mail or html mail with pictures) the mail is - **just for a fraction of a second** - depicted normally before "Dark Reader" takes effect.

This is, as I said, just a  very **_minimal_** delay and it doesn´t really bother me.

I just wanted to know whether this behaviour is to be expected.

Thanks a lot in advance for your help.

Many greetings.
Rosika

**Comment by Gusted** [comment]
Hi @Rosika2!

This is expected behavior, at least on Linux. We do have a mechanism that tries to darken the page as soon as possible with a very generic dark style to minimize this effect. However it includes 1 check, that check if the current system prefers a dark color scheme. I know a lot of Linux distro's currently cannot set this properly, whereby some do like Pop!_OS which actually has a global setting for this. You do mention you're are on Lubuntu which is IIRC based on LXQt, which I actually don't know if this is also true but more likely it isn't. 

Regards,
Gusted

**Comment by Rosika2** [comment]
Hi @Gusted,

thank you so much for your answer.
Good to know that this behaviour is to be expected.
As I said, it doesn´t me bother at all; I just wanted to know something more about it.

You´re right in stating that Lubuntu 20.04 makes use of LXQt DE. On 18.04 it still was LXDE. Now idea if things were different then.

So I´ve learnt quite a bit now; thanks for sharing your knowledge.

Keep safe and many greetings from Rosika
