### ISSUE TITLE
[Broken Website] wikipedia.org

### ISSUE THREAD

**Issue by nathanielcwm** [darkreader/darkreader#6606]
# Broken Website Report

## Website Address
https://en.wikipedia.org/wiki/Template:Timeline_Temperature_Conversion

## Expected Behavior
Wikipedia Plots inverted

## Actual Behavior
Not inverted and thus becomes blinding

## Screenshots
![image](https://user-images.githubusercontent.com/22572406/130792136-61039c75-9a37-4a9f-8815-a2629f6934bf.png)

## System Information
- OS: Windows
- Browser: FF91.0.2
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
These aren't plots in the sense that they don't have any generic `classname` that indicate they are a plot. And thus it's to be expected behavior. We're not inverting/modifying individual images on wikipedia anymore as you have a big chance, that you somehow target a image which you didn't meant to target.
