### ISSUE TITLE
chrome and Windows 10 become slow

### ISSUE THREAD

**Issue by Courvoisier13** [darkreader/darkreader#668]
Hi,
I noticed after installing the extension that Chrome becomes really slow. Furthermore, I don't know how or why, windows defender starts working and hogging ressources, causing all of windows to run slow. When I uninstalled the extension, things went back to normal.
This is not a PC power issue. I have a 1920X threadripper. This is really about compatibility with Windows defender.
Please let me know what kind of info I can supply to help you.

thanks

**Comment by risualiser** [comment]
Try to use "Static" mode.

If it cause a way less lags, it means your computer not powerful enough for Dynamic mode (or Filter).

"Dynamic" does require some more resources to analyze colors, and the only way to fix it is analysis optimization, which is already in a [roadmap](https://github.com/darkreader/darkreader/projects/1).

**Comment by alexanderby** [comment]
I didn't notice any issues with Windows Defender and Amazon website. Maybe it happens on some specific pages? Do you have many tabs opened?

I can confirm lags on GMail, they have a large CSS and only some small part of it is actually used. Detecting what CSS is used will also require a lot of resources from the extension.

**Comment by alexanderby** [comment]
Many performance improvements were made for Dynamic mode. Still many optimizations are possible. But if you see that performance is low on some website or if some extension is conflicting with Dark Reader and causes high CPU usage, please file a new issue.

**Comment by Vagelis-Prokopiou** [comment]
Same problem on a Debian GNU/Linux 9.6 system. Using static mode greatly improves (decreases) the CPU activity.

**Comment by kangarooo** [comment]
Chrome. Same. And doesnt stop still on my 100+ tabs.

**Comment by gaforov** [comment]
This is a great extension, but unfortunately, I need to turn it off most of the time because as soon as I turn it on, my laptop fan starts making noise. It consumes a lot of CPU power. I am using latest version 4.9.9 updated May 25, 2020 with Chrome and Windows 10.  
When you are at Google Drive or Reading pdf via Chrome, buttons/icons on the top right corner such as "download" disappear, you need to switch from dynamic to static to see them.

**Comment by Gusted** [comment]
Hmm open up a issue with a specific site and see I can reproduce it with my poor laptop. @gaforov

**Comment by alexanderby** [comment]
@gaforov Are you using Filter mode?

**Comment by gaforov** [comment]
Yes, Youtube FIlter+ makes video slow motion when people talking. But Filter(without plus) when you mouse over the video on Youtube, half of screen goes blank. @alexanderby

**Comment by alexanderby** [comment]
So, it seems like you have a slow GPU, or the browser doesn't use it. I suggest you to use Dynamic mode.

**Comment by gaforov** [comment]
I made a short video showing the issue, I will share the link with you once it gets uploaded to youtube.
My machine: i7-8550U 16GB RAM, 2GB dedicated GPU.  Windows 64-bit

**Comment by alexanderby** [comment]
So, I suggest you to check if hardware acceleration is enabled for Chrome in your case. Go to chrome://settings and search for Hardware Acceleration. Also your Nvidia control panel can have settings for particular apps. Open resource manager to see what particular component, CPU or GPU is being hit. If nothing helps, nothing can be fixed in Dark Reader. Filter mode relies on CSS filters and Filter+ relies on SVG filters. They are hungry to dynamically changing content.

**Comment by gaforov** [comment]
I will try that thank you very much!
