### ISSUE TITLE
Embedded Youtube Videos 

### ISSUE THREAD

**Issue by daephx** [darkreader/darkreader#680]
Embedded youtube videos on quora.com are inverted through the filter and filter+ modes.
for now, I'll just use one of the other ones.
Just a thought I'd like to know, my programming and what not is weak but Is there some sorta way to check for an embedded video globally to prevent inversion or would that strictly be on a per domain basis through the dev tool? Seems like the only indicator I can spot is that it falls under one of the two classes.
.html5-video-player
.html5-video-container

**Comment by alexanderby** [comment]
Maybe you could try using Dynamic mode for Quora? If not, could you please give a link for a page with video?

**Comment by DaemonPhoenix42** [comment]
It's been some time since, so I don' have my original page.
Here is another page to serve as an example
https://www.quora.com/What-is-the-most-liked-comment-on-YouTube

**Comment by Ririshi** [comment]
Hi there, it's been some time since this issue has seen activity, so apologies in advance for reviving an old issue. I am still getting some issues with embedded YouTube videos when using the filter+ (my preferred) mode. An example is https://mireinyc.com/, which has a number of embedded videos. Apart from showing inverted thumbnails, the video is pretty much unplayable with filter+ on, as the view is not updated when the video is playing.
