### ISSUE TITLE
[Bug] Dark reader breaks upon attempting to modify any settings

### ISSUE THREAD

**Issue by proudmuslim-dev** [darkreader/darkreader#6848]
# Bug Report

## Bug Description

Dark reader breaks upon attempting to modify any settings.

## Website Address

Any

## Steps To Reproduce

1. Install Dark reader on firefox 92
2. Attempt to change the settings on any website

## Expected Behavior

Options work as intended

## Actual Behavior

Extension just stops working

## Video

https://ttm.sh/eDd.mp4

## System Information

- OS: Arch Linux
- Browser: Firefox 92, also tested on Firefox Developer Edition 93
![image](https://user-images.githubusercontent.com/69869443/134257169-a4aa9a27-6d70-4a0c-853d-378f999ce6ce.png)
![image](https://user-images.githubusercontent.com/69869443/134755741-3d6bb798-d995-4a7a-ac6d-8da78f5b36da.png)

- Dark Reader Version: 
Latest

## Additional Context

This occurred after I updated the firefox package on my system (https://archlinux.org/packages/extra/x86_64/firefox/)

**Comment by Gusted** [comment]
Hi @proudmuslim-dev!

I cannot reproduce this behavior, but could be one of the regression that we had since the last dark reader release. 
Could you use the [downgrade ability](https://wiki.archlinux.org/title/Downgrading_packages) to downgrade firefox and see if it's related to the new Firefox release?

Regards,
Gusted

**Comment by proudmuslim-dev** [comment]
It appears that reinstalling dark reader did the trick(?) it's still somewhat broken but works on most websites just fine. It still turns off if I change the settings on GitHub, but if I turn it back on manually it works... weird

I'll downgrade firefox later today and tag you with the results

**Comment by shortlurker** [comment]
I have this problem too on Firefox Beta 93 (build 8) Win10 with Dark Reader 4.9.35 and 4.9.36. Settings do not save. Automation does not work. Does not toggle on and off on whitelisted sites.

Reinstalled 4.9.36 did not fix anything for me. Only rolling back to 4.9.34 through the FF version history page settings save and automation works as scheduled.

**Comment by chris-kwl** [comment]
Same misbehavior for me using Firefox 92.0 on Windows 10 Pro 21H1
Have first noticed it today and `about:addons` shows that the plugin was updated today to `4.9.36`

**Comment by proudmuslim-dev** [comment]
@Gusted Works fine if I downgrade ff, and downgrading Dark Reader to `4.9.34`makes it work on 92 as the others have said above

**Comment by Gusted** [comment]
Hmm, that's weird that must've been a regression then. And not necessarily one with Firefox. Kind of weird as if something should happen it should happen to a wider variety of people. v4.9.37 should be out soon with the latest fixes for a few more regressions let's wait for that release and see if that fixed it, otherwise someone might need to a regression test.

**Comment by proudmuslim-dev** [comment]
Alright

**Comment by chris-kwl** [comment]
I just noticed that the changes take effect / are saved but only after restarting the browser.
This is with FF 92.0.1 (64-Bit) and 4.9.36, 4.9.37.1 is not yet available on the mozilla page.

**Comment by shortlurker** [comment]
Updated to 4.9.37.1 through the addons page and also see the same settings behavior as chris-kwl described where a restart of FF is required.

**Comment by Gusted** [comment]
Seems like it might be related to #6873

Also: https://github.com/darkreader/darkreader/issues/6873#issuecomment-927018781

**Comment by chris-kwl** [comment]
Could solve the problem for me, but no idea how exactly...

Based on Gusted comment https://github.com/darkreader/darkreader/issues/6873#issuecomment-927018781 I had a look at the older commits.
I checked out 31fb6743ad7cccab5898dc06ed3f136dc834d9af and loaded it via debugging menu temporarily, FF has loaded it, but the version seems to be no longer compatible. There was a warning (see below) and the existing settings no longer worked, but new ones were accepted.
I switched back to the official 4.9.37.1, which is now also working...

<details>
  <summary>FF warning</summary>
  
  ```
Reading manifest: Warning processing optional_permissions: Error processing optional_permissions.0: Value "contextMenus" must either: must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]
  ```
  
</details>

**Comment by Gusted** [comment]
>  but the version seems to be no longer compatible. There was a warning (see below) and the existing settings no longer worked, but new ones were accepted.
> I switched back to the official 4.9.37.1, which is now also working...

Warnings can be ignored :) Otherwise they would be errors. The version is perfectly working we just didn't had the right toggles for the manifest we had included.

Also a git bisect is not randomly checking out older commits, it's a [nice process](https://www.git-tower.com/learn/git/faq/git-bisect/) that Git(our source control) offers to quickly find out which commit has introduced this behavior.

Regards,
Gusted

**Comment by chris-kwl** [comment]
Didn't even get as far as using bisect. Just created and loaded the commit with tag 4.9.35 for testing and it worked directly with it. But not with the official version 4.9.35. I do not know why... were there still commits in between?

If I had used bisect it would have been probably in vain because I would have searched between tag 4.9.34 and 4.9.35.

Because its working now I can no longer reproduce the problem even with FF portable and test the later commits.

**Comment by Gusted** [comment]
> But not with the official version 4.9.35. I do not know why... were there still commits in between?

Not that their should be...

This is a pretty weird issue as it just seems to happen randomly at people, I wasn't able to find any similarities yet.

**Comment by Azraelle** [comment]
When are you gonna fix it?

**Comment by Gitoffthelawn** [comment]
I had my first experience with this issue a little bit ago.  I thought a site perhaps wasn't rendering properly, so I turned off Dark Reader via the toolbar popup.  Dark Reader turned off, and I could see that it was an issue with the website itself (not a Dark Reader issue).  But then I tried to turn Dark Reader back on using its toolbar popup, and although the Dark Reader popup indicated it was back on, it was no longer making any sites dark.

I had to reboot for other reasons, and after the reboot, Dark Reader was making things dark again.  I haven't tried the DR toggle yet because I need to get some other things done right now.

Likely unrelated, but this happened after another application (Notepad++) crashed.  Plenty of memory was available after that crash, but I heard the fans going strong, so I'm guessing a process was stuck and was taxing the CPU.

This was on a Windows box running Firefox 92.0.1.
