### ISSUE TITLE
Prevent non-interface images from getting inverted

### ISSUE THREAD

**Issue by kikones34** [darkreader/darkreader#706]
Unless I'm missing something, there only exists the "INVERT" option to tweak page elements in Dynamic mode. That's not enough to fix some websites. Take for example this (on www.pixiv.net):

![Original](https://i.imgur.com/YLEcz5F.png)

All those images are inside a \<nav\>. I would like to specify that no image inside that should be inverted, but with the "INVERT" option all I can manage to do is to reverse the images which are inverted:

![Inverted](https://i.imgur.com/QY0RESC.png)

Additionally, I just noticed that the re-inverted images don't go back to the original, the colours get distorted. Not sure why that's the case.

**Comment by risualiser** [comment]
>That's not enough to fix some websites.

Actually, Dynamic mode is supposed to be improved in future to get rid of any additional configs as much as possible, so I think that developer let us add only "Invert" configs just to reduce lags caused by this mode (and also because it often shows not really good results when re-inverting some stuff like fonts).

According to [another page with these pictures](https://www.pixiv.net/member.php?id=934903), I think that extension just detected images your page as "backgrounds" and started to analyze colors.

So, this is a bug, but I think you can rename the issue to "Prevent simple images from inverting".

**Comment by kikones34** [comment]
Hum, I see, I'll edit the issue then. Either way, it'd be nice if there was a way to manually change the parameters such that I could browse Pixiv or other pages which might have this problem, until the extension properly handles them. Currently, no mode works well.

**Comment by Gusted** [comment]
```
CSS
.selector {
    filter: none !important;
}
```

:shrug: And btw Threshold changed so not sure if this issue still persist
