### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by stonecrusher** [darkreader/darkreader#719]
# Improved german translation

I looked through the translation and some terms were faulty or sounded very artificial because of too direct and unintelligible translation. Corrected that.

Chrome: [de.config.txt](https://github.com/darkreader/darkreader/files/2366489/de.config.txt)
Firefox: [messages.json.txt](https://github.com/darkreader/darkreader/files/2366494/messages.json.txt)
Helpfile: [de.md.txt](https://github.com/darkreader/darkreader/files/2366496/de.md.txt)

Note that `@toggle` is empty on purpose. There is no good direct translation that would stand in front of the domain name only. I tested different variations in FF 62.0 and came to the conclusion that it is not necessary at all to have it in the button.
1. It really makes the button ugly, often forcing the domain to wrap
2. The explanation of what it does is just beneath
3. It can be easily tested (instant result!) and reverted by just clicking it again, which is what one would try first if something changed unpleasantly

Only tested with FF62, don't know how it looks or if it works (no json format) in Chrome!

# Untranslated strings

These strings do not have an internationalization key yet.

#==== Everywhere ====
"Type a shortcut"

#==== Developer tools popup ====
"Inversion fix editor"
"Reset"
"Apply"
"Read about this tool here. If a popular website looks incorrect e-mail to DarkReaderApp@gmail.com"

# Extra question

@page_in_dark_list
This site is in global Dark List

Where to see and edit global Dark List? I tried it at https://darkreader.org/ and the "websitelist" apparently is unrelated

# /edit1
I adapted and proof-read the [german helpfile](https://github.com/darkreader/darkreader.org/blob/master/src/help/topics/de.md) as well. Note the german screenshots hosted on github.

**Comment by risualiser** [comment]
> Where to see and edit global Dark List?

[Here.](https://github.com/darkreader/darkreader/edit/master/src/config/dark-sites.config)

**Comment by stonecrusher** [comment]
Thanks. So it is indeed a hardcoded darklist, impossible to turn off or edit from within the extension? That's imho a bit odd, but I can live with it.

**Comment by alexanderby** [comment]
@stonecrusher Thanks for your translation. To make it available in app please do the following:
- Edit [this app file](https://github.com/darkreader/darkreader/blob/master/src/_locales/de.config) (click "✎" icon) and open Pull Request.
- Edit [this help file](https://github.com/darkreader/darkreader.org/blob/master/src/help/topics/de.md) and open another Pull Request.
[Here](https://github.com/darkreader/darkreader/issues/559) are some instructions.

About "Toggle" phrase: in future there will be some design change, so that user could understand what's current state of this button. Maybe a good solution for you will be using the "↻" UTF icon.

-Thanks for noticing untranslated phrases, Currently I replaced "type a shortcut" phrase with "✎...⌨" icons, cause it will require much time to translate it into all locales and watch for space occupied by phrase. Dev Tools phrases are not translated intentionally, it's critical to be able to communicate in English with person who want to contribute, so we can understand each other.
