### ISSUE TITLE
[Feature Request] Dark Reader should cache CSS it recently computed for better performance (so it doesn't have to figure out styles for the same URL anymore)

### ISSUE THREAD

**Issue by artisticfox8** [darkreader/darkreader#7395]
# Feature Request

## Is this feature request related to a problem?
On some sites, Dark Reader can compute the CSS using the dynamic filter over and over again, making the browser slower.
If it remembered I visited that website 2 minutes ago and used that CSS only computing elements not handled by the stylesheet (possible new elements)., it would become a lot quicker. 

## Additional Context
I'm using Intel dualcore, so speed optimisations matter to my computer

**Comment by Gusted** [comment]
Caching is not possible between websites visits as on each new visit the website could show other CSS, you could be logged in, just logged out, the site could be a SPA which means it's really problematic.  Due to technical things with websites this wouldn't be possible, closing.

**Comment by artisticfox8** [comment]
> 
> 
> Caching is not possible between websites visits as on each new visit the website could show other CSS, you could be logged in, just logged out, the site could be a SPA which means it's really problematic. Due to technical things with websites this wouldn't be possible, closing.

If it remembered I visited that website 2 minutes ago and used that CSS only computing elements not handled by the stylesheet (possible new elements)., it would become a lot quicker.

**Comment by artisticfox8** [comment]
Please read carefully

**Comment by Gusted** [comment]
> Please read carefully

I've read it carefully, and I will come to the same conclusion that no matter how little the time between the visits are - the website could send out a whole new site(with other CSS) based on a infinite amount of factors.

**Comment by artisticfox8** [comment]
> 
> 
> Caching is not possible between websites visits as on each new visit the website could show other CSS, you could be logged in, just logged out, the site could be a SPA which means it's really problematic. Due to technical things with websites this wouldn't be possible, closing.

there are tons of static sites / sites where only the content changes + what I said, it could only use the cache as speedup, checking each element, and already using the computed color if it is available, otherwise computing it as usual

**Comment by artisticfox8** [comment]
You wouldn't lose anything, if a whole new site is spent - memory is cheap (only kBs, usually _way_ under a mB for a stylesheet.)

**Comment by Gusted** [comment]
> there are tons of static sites / sites where only the content changes

I can tell you from experience and profiling a ton of websites with dark reader enabled that the static sites are really performant with dark reader.



>  it could only use the cache as speedup, checking each element, and already using the computed color if it is available, otherwise computing it as usual

The checking of each style against a finite amount of cached-styles is not the most performant action that would be done, it will add extra time to do that action and it wouldn't be a good trade-off if you will just compute it always.



> You wouldn't lose anything, if a whole new site is spent - memory is cheap (only kBs, usually _way_ under a mB for a stylesheet.)

You would lose performance because of the added time of comparing the styles with a cache(which wouldn't be nice if you were going for a performance improvement) - And while memory is cheap, it's not nice to cache whole styles of websites like google, youtube, github, twitter etc. They are combined all way above a few Mb's and if someone would on a day visit all those sites, the memory consumption of Dark Reader will be way above for a normal extension.

**Comment by artisticfox8** [comment]
> 
> 
> > there are tons of static sites / sites where only the content changes
> 
> I can tell you from experience and profiling a ton of websites with dark reader enabled that the static sites are really performant with dark reader.
> 
> > it could only use the cache as speedup, checking each element, and already using the computed color if it is available, otherwise computing it as usual
> 
> The checking of each style against a finite amount of cached-styles is not the most performant action that would be done, it will add extra time to do that action and it wouldn't be a good trade-off if you will just compute it always.
> 
> > You wouldn't lose anything, if a whole new site is spent - memory is cheap (only kBs, usually _way_ under a mB for a stylesheet.)
> 
> You would lose performance because of the added time of comparing the styles with a cache(which wouldn't be nice if you were going for a performance improvement) - And while memory is cheap, it's not nice to cache whole styles of websites like google, youtube, github, twitter etc. They are combined all way above a few Mb's and if someone would on a day visit all those sites, the memory consumption of Dark Reader will be way above for a normal extension.

I meant you compute only the elements you have no data for - the newly appeared ones.

**Comment by artisticfox8** [comment]
As for speed, I'm sure there are JS equivalents of Python dictionaries.

**Comment by Gusted** [comment]
> If you compared them using efficient data formats, the time penalty wouldn't have to be big

The best data structure I can come up with is a Minimal perfect hash structure, but given that it isn't natively implemented in Javascript, the standard hashmap which is natively implemented is your way to go, but the speed trade-off will still be big if you have a couple thousands of entry.



>  Maybe it will be smaller than computation

The computation is really fast since the last few updates, their are a lot of other factors that can make dark reader slow actually. 

I would much more prefer if you made a performance issue about a specific site - as this is just "theoretical" to fix a problem with no data to back it up that it is actually happening.

**Comment by Rudxain** [comment]
It seems [extensions can check if a page is cached](https://chromewebstore.google.com/detail/cache-checker/jfipdgenfgpoakdfnndhkgjnnopnlohn). So DR could do a simple "all or nothing" approach: fetch cache or recompute everything, depending on what the browser says.

Browsers are more likely to fetch from cache if the user moves backwards or forwards in the history (with the arrow buttons). So that's yet another hint for DR to fetch the cache.

There could also be a setting named "aggressive caching" (disabled by default), that forces DR to fetch cache as much as possible, even if it could create minor visual-artifacts. This also doubles as a power-saving feature
