### ISSUE TITLE
[Bug] Occasional flash on some sites if the dark reader set disabled for site

### ISSUE THREAD

**Issue by ClassicDarkChocolate** [darkreader/darkreader#7650]
# Bug Report

## Bug Description

Some sites experience flash issue occasionally even when setting dark reader to be disabled on them.

## Website Address

You can see this issue especially on sites that use MUI.
https://mui.com/core/

## Steps To Reproduce

- Open site
- Set dark reader to disable on the site.
- Refresh the page, and sometimes you will see some blocks flash.

## Expected Behavior

Extension not doing anything on sites that already disabled.

## Actual Behavior

Extension does something unknown to pages already set disabled for.

## Screenshots

![](https://i.imgur.com/c4uwch0.png)

Or gif starting from 9s. https://imgur.com/a/mYwKul4

## System Information

- OS: Windows 10
- Browser: Edge 96, Firefox 95
- Dark Reader Version: 4.9.34

**Comment by Gusted** [comment]
HI @ClassicDarkChocolate!

This is a intentional design choice of Dark Reader,

Dark Reader has been dealing with white flashes(your issue is the exact opposite, dark flashes) for quite a long time.
A new mechanism was made in order to hugely fix this, it had a trade-off(which I happily made, considering white flashes are really bad for the eyes) whereby the fix would be applied to each site, even if the site wasn't disabled within the UI, this is because the performance of getting the information if the current site is enabled or not, took too long and white flashes will happen.

Regards,
Gusted

**Comment by ClassicDarkChocolate** [comment]
@Gusted thanks for your reply, should I close this issue or leave it open?

**Comment by Gusted** [comment]
I'm not really intended nor technically can to change this behavior without returning white flashes again.
