### ISSUE TITLE
[Bug] Screen flashes on link clicks when Dark Reader is toggled off

### ISSUE THREAD

**Issue by talyz** [darkreader/darkreader#7941]
# Bug Report

## Bug Description
With a dark theme enabled in Firefox, the screen flashes black when clicking on links, even if the site is disabled in the extension or Dark Reader is toggled off in its menu. The only way to get rid of the behavior is to disable/remove the extension entirely.

## Website Address

N/A

## Steps To Reproduce

- Enable Firefox's Dark theme
- Go to http://nginx.org/
- Disable Dark Reader for the site in Dark Reader's menu
- Click around on the site

## Expected Behavior

Everything works as if the extension wasn't installed.

## Actual Behavior

Screen sometimes flashes black when clicking links.

## Screenshots

The video shows an example of this happening on the nginx.org website, which I've toggled off Dark Reader for.

https://user-images.githubusercontent.com/63433/149314260-f3efb10b-8919-48a6-95bb-0ea6b5556dbe.mp4

## System Information

- OS: Linux
- Browser: Firefox 95.0.1
- Dark Reader Version: 4.9.43

## Additional Context

N/A

**Comment by Gusted** [comment]
See: https://github.com/darkreader/darkreader/issues/7650#issuecomment-995810449

**Comment by talyz** [comment]
Would you mind providing some more info on the issue? Is it possible to turn off the mentioned workaround somehow? I'm wondering since I get white flashes if I switch to the light theme and black flashes with the dark theme, so it seems like my theme is at least partly what's preventing white flashes in my case.

**Comment by Gusted** [comment]
> Would you mind providing some more info on the issue? Is it possible to turn off the mentioned workaround somehow?

Well, I had a patch somewhere whereby the workaround would turn off automatically. But I had to float the idea because of the rise of [MV3](https://developer.chrome.com/docs/extensions/mv3/intro/) which would remove a lot of functionality and one of them was a function that made it possible to remove the workaround where needed.



> I'm wondering since I get white flashes if I switch to the light theme and black flashes with the dark theme, so it seems like my theme is at least partly what's preventing white flashes in my case.

Could you explain that a bit? The dark flashes are consistent(even if you turn of DR due to technical limits). White flashes are from the browser.

**Comment by talyz** [comment]
>Could you explain that a bit? The dark flashes are consistent(even if you turn of DR due to technical limits). White flashes are from the browser.

Sure! What I'm trying to say is that the color of the flash is entirely dependent on which theme I have activated:
- With the light theme I get consistent white flashes _only_, no black ones
- With the dark theme I get consistent black flashes _only_, no white ones

So what I'm wondering is if something has changed in Firefox to make the workaround unnecessary as long as the right theme is chosen. I don't know what the workaround does, though, so it's a bit hard for me to reason about that. :)

**Comment by Gusted** [comment]
> So what I'm wondering is if something has changed in Firefox to make the workaround unnecessary as long as the right theme is chosen. I don't know what the workaround does, though, so it's a bit hard for me to reason about that. :)

The problem is that on slower systems or on the _rare_ occasions that even on dark theme the white flash will happen as it's the "hard fallback", so It will be in the code for a while(as well for Chromium). 

So when you choose light theme, I presume Firefox sets the correct color-scheme to light in which the workaround is disabled(which is why you would see white flashes) and on the `dark` color-scheme(when Firefox sets this correctly) it enables the workaround. So that should be why you see different flashes on themes.

**Comment by PetrovichPetrovich** [comment]
I was using official release from google store and it does blink since the last update even if I dont use dark mode on that page. Especially on nyaa.si. I installed same version from github but MV2 and it doesn't blink at all.
