### ISSUE TITLE
[Feature Request] Site-specific Over-rides Should Ignore Global Setting

### ISSUE THREAD

**Issue by megamorphg** [darkreader/darkreader#7979]
## Is this feature request related to a problem?
I like to enable websites individually, which this extension doesn't allow since the global "Off" option doesn't allow enabling specific sites. Only the global "On" option allows this.

Site-specific over-rides should ignore the global setting as this would address this issue. This way, I can keep it "Off" globally and then just enable the sites I want dark mode on individually.

## Screenshots
Notice the site is grayed out when global is set to Off:
![image](https://user-images.githubusercontent.com/1782353/149797067-f95e27a3-526f-4880-bebd-9b111392b0d0.png)

## Additional Context
The ultimate goal is to be able to set dark mode on desired websites individually, even if globally sites are not automatically set to dark. Site-specific settings should be allowed and over-ride any global setting.

**Comment by NguyenASang** [comment]
@megamorphg Here's how you can disable the default dark mode for every website and enable it only on the sites you want.

https://user-images.githubusercontent.com/87893636/149850704-bd64e869-9d8f-4233-baf2-dc56e39fed62.mp4

**Comment by Gusted** [comment]
Hi @megamorphg!

I'm pretty confused by this feature request, as while I was reading this I thought I'd understood what is meant, but on the hand it doesn't make sense to me. When dark reader is "Off", it is disabled and doesn't modify sites. However this request goes into that, whereby individual sites still should be "On". I don't think that's a good idea:

Because, you can have the same functionality, by going to the Site List in the popup and then select "Invert listed only".

Regards,
Gusted

**Comment by megamorphg** [comment]
@Gusted this addresses the need. Wasn't aware of the invert option. Thank you!
