### ISSUE TITLE
[Broken Website] web.whatsapp.com fails on QR 

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#8060]
# Broken Website Report

## Website Address
https://web.whatsapp.com

## Steps To Reproduce

Go to https://web.whatsapp.com/ and try to scan the QR code. 

## Problematic Observation

It fails. 

## System Information

- OS:  Linux
- Browser:  Firefox 96
- Dark Reader Version:  current

**Comment by Gusted** [comment]
Hi @ShalokShalom!

Do you have [the latest fixes](https://github.com/darkreader/darkreader#site-fixes)? On my machine currently the QR reading works(only the icon is a bit messed up, but QR codes allows for such "error").

Regards,
Gusted

**Comment by ShalokShalom** [comment]
Yeah, it works now. Why not making this setting default?

**Comment by Gusted** [comment]
> Yeah, it works now. Why not making this setting default?

Traffic concerns, we have a few million active users. Github won't be that kind of the sudden traffic increase, especially when not everyone needs it(most fixes that people need aren't CSS, but rather code-related).

**Comment by ShalokShalom** [comment]
This is broken again. I STRONGLY recommend to set this and other known QR code sides to the disabled sites, in my experience it the chance very high, that they wont work. 

Just classify QR codes are something to be reported. If we find somebody, who wants to maintain it, we have a list of the known instances. Its so annoying, running again and again into the same issues, on the same pages. 

Reports on WhatsApp not working go back to basically the inception of the project and every update of the browser makes it necessary, to relogin this way.

**Comment by Gusted** [comment]
> This is broken again. I STRONGLY recommend to set this and other known QR code sides to the disabled sites, in my experience it the chance very high, that they wont work.

That's not how the dark sites config works, it's not the correct way to say "Oh this is broken, lets just disable it and never look back into it". 

> Just classify QR codes are something to be reported. If we find somebody, who wants to maintain it, we have a list of the known instances. Its so annoying, running again and again into the same issues, on the same pages.

Well, is there anything that says that it shouldn't be reported? Reporting issues is really volunteer-basis by the users, if someone runs into a issue and don't want to report it, not my problem. I can only handle and act on issues that get my attention(aka being reported here).

> Reports on WhatsApp not working go back to basically the inception of the project and every update of the browser makes it necessary, to relogin this way.

I just checked the website and the fix that I deemed as "future-proof" is just working as intended, https://github.com/darkreader/darkreader/pull/2748#discussion_r436274191. Please check if you actually have these fixes loaded, on my side nothing else has changed since then on the website that would break the QR-code.
