### ISSUE TITLE
[Broken Website] IMDB some headers and most sidebar items

### ISSUE THREAD

**Issue by irvinm** [darkreader/darkreader#8157]
# Broken Website Report

## Website Address

https://www.imdb.com/user/ur41260497/ratings?ref_=nv_usr_rt_4 (Ratings)
https://www.imdb.com/name/nm0000116/?ref_=tt_ov_dr (Example person James Cameron)

## Steps To Reproduce

- Starting in Windows Sandbox, install latest Firefox and Dark Reader (all default values)
- Open links above and see sections.  (Only started fairly recently)

## Problematic Observation

White areas should be dark

## Screenshots

Ratings:
![image](https://user-images.githubusercontent.com/979729/152687210-a55973e5-9b1f-40e9-b49a-81b73604844b.png)

James Cameron:
![image](https://user-images.githubusercontent.com/979729/152687155-41b88331-bf12-4333-a307-b8da4b6a7a80.png)

## System Information

- OS: Windows 10 Pro (21H2)
- Browser: Firefox 96.0.3
- Dark Reader Version: 4.9.44

**Comment by q1800** [comment]
@Gusted,

Is the fix for this issue the same for the issue shown below in the screenshot? (These fields were never white before).

If this fix is the same for all of these type of issues, will this fix be pushed into a new hotfix release shortly or do we need to wait for the next scheduled release (A Month or more)?

Thanks

![firefox-download](https://user-images.githubusercontent.com/95879668/152874953-5057ba13-4cb8-4967-8f63-601bed683ef4.png)

**Comment by Gusted** [comment]
Those are different issues, please open up a new issue for that.

**Comment by q1800** [comment]
Ok, thank you.
