### ISSUE TITLE
[Broken Website] gimp.org

### ISSUE THREAD

**Issue by q1800** [darkreader/darkreader#8538]
# Broken Website Report

## Website Address
https://www.gimp.org/

## Steps To Reproduce
Visit the website with Dark Reader enabled.
Notice the white backgrounds in the screenshot need fixing.
Notice the underlines in the screenshot need fixing.

## Problematic Observation
White Backgrounds
Underlines

## Screenshots
![Screenshot 2022-03-28 at 16-32-09 GIMP](https://user-images.githubusercontent.com/95879668/160493655-d2dbc56c-dc77-43ca-9eb6-c22eabbe7d9c.png)

## System Information

- OS: Windows 10
- Browser: Firefox Nightly 100
- Dark Reader Version: 4.9.47

**Comment by q1800** [comment]
@Gusted,

Wow! I guess I found you a whopper of an issue to fix! LOL!

**Comment by Gusted** [comment]
> @Gusted,
> 
> Wow! I guess I found you a whopper of an issue to fix! LOL!

Well the fundamental issue was luckily quickly spotted(Sorting wasn't there + only on the URL side some additional things was [done](https://github.com/darkreader/darkreader/commit/0eccbdce22523f3441fdb6b5269953a6e407960e#diff-337c45ced588ebb0fb102c2a797de3e86cb73c04ff2ff609a228c4bbad82e48fR458-R464))... but the actual fix has gone trough many iteration in order to actually solve it 😅. But I'm pretty sure a lot of issues are hereby also resolved and prevented, because it only took this long to realize this was Dark Reader's fault(and not a shortcoming of a feature).

**Comment by q1800** [comment]
Oh so you're saying that I actually caused a pretty good size bug to be found and fixed? Also, that you had to put in work on the weekend because of me?!? Well, you're welcome on both counts! 😝 😝 😝 

Seriously though, I am always happy to assist and help where I can! Enjoy your weekend my friend!
