### ISSUE TITLE
[Broken Website] https://narimiran.github.io/

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#8594]
# Broken Website Report

## Website Address

https://narimiran.github.io/nim-basics/

## Steps To Reproduce

1. Go to the webpage

## Problematic Observation

Brown instead of black

## System Information

- OS:  current
- Browser:  current Firefox/FireDragon
- Dark Reader Version:  current

## Additional Context

I dont know, if this intentional, but I prefer it real black.

**Comment by Gusted** [comment]
I don't think there's much to do here aside from CSS fixes. The original colors has a slight deviation in the blue section, and due to the dark reader modification the blue will be less and thus results in the brown color... Setting contrast a bit higher and background color to `#fff` should help with it.
