### ISSUE TITLE
[Bug] transition: background fades in from black even if dark reader is disabled

### ISSUE THREAD

**Issue by SuspiciousActivity** [darkreader/darkreader#8917]
# Bug Report

## Website Address
https://eazyco.de/darkreaderissue.html

## Bug Description
A div element with `transition: background 5s` on an empty white page flashes from black into transparent.

## Steps To Reproduce
- Make sure Dark Reader is turned off.
- Go to [the example website](https://eazyco.de/darkreaderissue.html).
- You will see the div fade in from black to transparent (white).
- You can reload the page and the issue persists.

## Expected Behavior
When loading an element with `transition: background` and Dark Reader off, the element should have its actual background without any transition.

## Actual Behavior
The element fades in from black to its defined (or default) color.

## System Information
- OS: Windows 10
- Browser: Firefox 100
- Dark Reader Version: 4.9.50

**Comment by muffinresearch** [comment]
Note: to be able to reproduce this about:preferences#general the website appearance needs to be set to "Dark".

<img width="825" alt="Screenshot 2022-05-20 at 18 09 38" src="https://user-images.githubusercontent.com/1514/169583559-17e9f19a-4a19-47c0-9c09-830a66fd8d58.png">

**Comment by Gusted** [comment]
This will be a wont/cannot fix. Dark Reader by default will always unconditionally apply a small fallback theme to sites in order to avoid white flashes from happening. And the browser now takes this dark background color of that element(before we can remove it) and does the transition.

There's currently no way that Dark Reader can be prevented to apply this small fallback to sites where it's disabled, as this process takes too much time in order to be fast enough to avoid white flashes.
