### ISSUE TITLE
[Broken Website] eBay search results don't appear

### ISSUE THREAD

**Issue by SuperSajuuk** [darkreader/darkreader#8992]
# Broken Website Report

## Website Address
https://www.ebay.co.uk

## Steps To Reproduce
- Go to the ebay homepage (whichever one for your location)
- Search for something in the search box and press Enter
- Observe the search results page has no results on it.

## Problematic Observation
None of the search results will be loaded, the area where they should be is completely missing. This can only be fixed by disabling Dark Reader and then refreshing the page, which causes them to load as intended. You can then re-enable dark theme for the page, but refreshing will break it again.

This only impacts search results, but considering searching is a key feature of eBay, not being able to see any results makes the site difficult to use.

## System Information
- OS: Windows 10 Pro 21H1 Build 19043.1645
- Browser: Chrome v102 [latest]
- Dark Reader Version: 4.9.51

## Additional Context
This started quite recently (around beginning of May 2022). Up until then, there was no issue, which leads me to believe that eBay changed something to break the extension.

**Comment by xircon** [comment]
Confirmed Endeavour OS Linux Vivaldi browser.

**Comment by datsfyre** [comment]
Just FYI, the issue seems to be due to a combination of an Ad Blocker and Dark Reader.

The specific rule in the filterlist seems to be this:

`ebay.co.uk,ebay.com,ebay.com.au#$#hide-if-contains-visible-text /Sponsored/ 'li.s-item' 'li.s-item span'` [(ref)](https://github.com/abp-filters/abp-filters-anti-cv/blob/master/english.txt#L358)

All items on Ebay Search Results has the "Sponsored" text, but eBay "hides" the Sponsored text for non-Sponsored items using `color: rgba(0,0,0,0)`.

When Dark Reader applies dark mode, all the spans with "Sponsored" are no longer "hidden" as the colors are adjusted, resulting in an Adblocker removing all items.

**Comment by Gusted** [comment]
I'm not able to reproduce this, there's a deleted comment that suggested that this is due to a adblocker extension. Are you using other extensions than Dark Reader?

**Comment by xircon** [comment]
uBlock origin and a few others that should have no effect.
Works on firefox, doesn't on Vivaldi.  Similar add-ons.

**Comment by xircon** [comment]
Vivaldi-snapshot:
![image](https://user-images.githubusercontent.com/1316691/172024528-88c8a43b-39b0-49e8-b611-078d554551df.png)

Firefox:
![image](https://user-images.githubusercontent.com/1316691/172024265-d176b44c-be30-411d-a093-cefd7b15a42a.png)

**Comment by fyrefyre** [comment]
I was looking into this issue and it's definitely related to Dark Reader w/ Ad Blockers.

Based on how Ad Blockers work, I believe this issue would be hard to fix purely from Dark Readers side. I reached out to eBay support and got a response the search team is aware of the issue and will have a fix ready soon. I'll keep everyone updated if I hear more.

**Comment by fyrefyre** [comment]
Got a response that the fix is live. I'm using DarkReader w/ Chrome and see the results again (finally!)

Before:
![image](https://user-images.githubusercontent.com/94711046/172306754-c77a70d7-32c6-4133-81d9-0e05e6f144e8.png)

Now:
![image](https://user-images.githubusercontent.com/94711046/172306417-b20c43c4-3469-4e1d-83f4-e21daec434fd.png)
