### ISSUE TITLE
[Bug] After setup a new Edge browser instance on Windows 10/11, DarkReader has reset settings on all devices

### ISSUE THREAD

**Issue by Kenya-West** [darkreader/darkreader#9132]
# Bug Report

## Website Address

\*.\*

## Bug Description

When you setup a new browser with the same personal Microsoft account, the Darkreader extension will be installed with stock settings from Microsoft (Edge) Store. And these new stock settings will be spread across all your devices replacing yours that you have been building, possibly, 3+ years. These settings include: filters, modes, and most important, lists of websites.

## Steps To Reproduce

- Setup new device/account and login to Microsoft Edge, wait some time to get Darkreader by extension synchronization.
- It got stock settings.
- Later login to another existing device and see, that Darkreader settings are replaced to stock ones, thus they have been reset.

## Expected Behavior

- DarkReader on a new browser should sync existing settings

## Actual Behavior

- It does not

## Screenshots

[OP is so angry he forgot how to printscreen]

## System Information

- OS: Windows
- Browser: Edge 103
- Dark Reader Version: 4.9.5.1

## Additional Context

The new device was Windows 10, the existing one is Windows 11

**Comment by Gusted** [comment]
That's weird, dark reader always reads from the synchronized settings and only save new settings if the user changed a setting. Did you miss any reported steps, did you change any setting afterwards? As from a logical standpoint it cannot happen due to how dark readers work, it could that reading from the synchronized settings got a error, but then dark reader disabled writing to the synchronized settings and then continue using local settings.

**Comment by Kenya-West** [comment]
> Did you miss any reported steps

No I did not

> did you change any setting afterwards?

Once I realised I lost all the settings, I started to fill lists of websites

**Comment by Gusted** [comment]
I don't see any actionable things here. I'm not able to reproduce it. Unless you're able to reproduce it again, feel free to open it.
