### ISSUE TITLE
[Bug] Breaks features on mailerlite.com

### ISSUE THREAD

**Issue by tut125** [darkreader/darkreader#9226]
# Bug Report

## Website Address

https://app.mailerlite.com/

## Bug Description

When creating a campaign, in this case an RSS campaign, the option to edit the drag and drop templates is missing or unresposive with the extension enabled.

## Steps To Reproduce

- Signup on mailerlite.com.
- Once logged in, select the "campaigns" menu and then "create campaign".
- In the "Choose campaign type", Select the RSS option.
- Use any valid RSS feed link and fill the rest of the fields with dummy content.
- Skip the next section and in the content section, choose the drag and drop editor option.
- Now, hover on any field and click the pencil icon. A new sidebar pops up on the right with "content" and "settings" fields, but they are empty. Clicking on them does nothing. Lots of errors in the dev console
- Disable the dark mode on the page and reload. The options to edit pop up.
- If you again enable dark mode and reload, the options disappear.
- I noticed this bug one or two months ago but I did not know what was causing it until now.

## Expected Behavior

The option to edit the form fields should work with the dark mode turned on, rather than being unresponsive. There is a conflict with the extension and the form editings, as evidenced by errors in the console

## Actual Behavior

Editing form fields does not work. The options disappear and only appear when dark mode is disabled and the page is refreshed.

## Screenshots

[See here](https://prnt.sc/Bh0odZNCIEfX)

## System Information

- OS: Windows 10
- Browser: Brave Version 1.40.113  Chromium: 103.0.5060.114 (Official Build)  (64-bit)
- Dark Reader Version: 4.9.52

**Comment by Gusted** [comment]
Hi @tut125!

Thank you for your detailed issue. Looking at the screenshot and this seems to be a problem that Dark Reader cannot fix. The website is attempting to use Dark Reader's elements(which is not possible due to browser security), it's hard for Dark Reader to avoid this as this is fundamental to how Dark Reader works. The best way to get this fixed is by contact the site's support, developers that see this issue can easily fix this by a adding a few checks to their code.

Closing as can't fix.
