### ISSUE TITLE
Dark Reader won't turn off for a specific website

### ISSUE THREAD

**Issue by ylluminarious** [darkreader/darkreader#935]
I'm trying to turn Dark Reader off for a specific website. Namely, [`userstyles.org`.](http://userstyles.org/) But it won't turn off, no matter how many times I click the `toggle` button. It seems to stay on no matter what. The only way to turn it off is to disable Dark Reader altogether.

[Here is a screencast demonstrating my issue.](https://d3vv6lp55qjaqc.cloudfront.net/items/070E3c420i0F1Y1B0u08/dark_reader_bug.mp4)

My situation is a bit strange because I typically use both Stylus and Dark Reader at the same time for this website. The reason being that [the userstyle for this site](https://userstyles.org/styles/141833/userstyles-dark-2018) sometimes doesn't work, so I supplement it with Dark Reader. As you can see in the screencast, the userstyle will turn on and off just fine but Dark Reader will not go off on this specific website. I can only disable it globally. Furthermore, `userstyles.org` is clearly being added and removed from the site list, but it still won't turn off. This makes me worry that my Dark Reader settings may be corrupted somehow.

Again, I've only seen this happening for `userstyles.org` and no other website. On every other website, I can toggle Dark Reader on a per-site basis just fine.

**Comment by ylluminarious** [comment]
@alexanderby Yes! That was the issue. I had this entry in my site list:

```
Users
```

After I removed that entry, `userstyles.org` is working normally again. I'll leave this issue open so that you can fix it, but thanks for letting me know what the problem was.

**Comment by nisavid** [comment]
This issue seems to manifest whenever a substring of the current website's domain has been previously added to the site list.  In particular, it seems to commonly affect me whenever I find myself having performed (unknowingly, as it happens over many weeks or months) the following steps:

1. Add a subdomain (e.g. `sub.example.net`) to the site list.

1. Add a higher-level domain of that subdomain (e.g. `example.net`) to the site list.

1. Try to toggle the subdomain to remove it from the site list.

The last step always fails, producing no effect, without any explanation.  A workaround is to find all corresponding higher-level domains (e.g. `example.net`) in the site list and remove them.  Toggling their subdomains (e.g. `sub.example.net`) will then resume working as expected.

**Comment by NobleUplift** [comment]
I just had this happen to me after adding `aws.amazon.com` and then I could not toggle `docs.aws.amazon.com` off.

**Comment by CubicrootXYZ** [comment]
Anything new here? Having the issue too. It just ignores blacklisted sites whenchanging tabs.

**Comment by Gusted** [comment]
You can't toggle off for subdomains when you have main domain disabled.

**Comment by CubicrootXYZ** [comment]
> 
> 
> You can't toggle off for subdomains when you have main domain disabled.

For me it is not a problem with subdomains, it happens to every site.

**Comment by Gusted** [comment]
Reinstall

**Comment by CubicrootXYZ** [comment]
> 
> 
> Reinstall

Didn't help in first place, but after a restart it works now. Sorry for disturbing.

**Comment by Lhorzz** [comment]
Old thread, but bug seems to still exist and I finally fixed mine. Did as nisavid mentioned. 
I looked at the Site List > Not Inverted List and deleted all of the entries for the website I was having a problem with. Found I had about 7 different subs. Then I just added the` sitename.*`
Ex: `amazon.com`, `account.amazon.com`, `list.amazon.com`, `aws.amazon.com` > delete them all and just add `amazon.* `and it filters out the whole website without needing to put in subs due to the *

**Comment by pcroland** [comment]
Yeah, it's still buggy.

**Comment by mmseng** [comment]
Still an issue from what I can tell. Apparently I can't have company.com inverted, and also have sub.company.com NOT inverted. That's a real bummer, given that we have so many subdomains, and some don't work well inverted.

**Comment by heliosyne** [comment]
This still an issue. I couldn't disable it for prof.brt.local (an internal website) because brt.local was listed. Any news on getting this fixed?

**Comment by Supsuop** [comment]
2023 it is still a thing!

**Comment by dm17** [comment]
Confirmed still an issue

**Comment by akay64** [comment]
Still an issue, but just started using "invert listed only" as a work around - I don't have that many native dark mode unsupported sites :)

![20230705073503](https://github.com/darkreader/darkreader/assets/6232227/6618b9d1-0aef-42d0-bab8-34afccefb051)

**Comment by hapylestat** [comment]
still issue and quite annoying

**Comment by alexanderby** [comment]
Looks like fixed.
