### ISSUE TITLE
[Broken Website] https://markdowntohtml.com/

### ISSUE THREAD

**Issue by callaloo** [darkreader/darkreader#9449]
# Broken Website Report

## Website Address

https://markdowntohtml.com/
## Steps To Reproduce

Delete the content in the left boxes and observe the preview box. It turns white. Any text typed in the left box shows as white too in the preview.
## System Information

- OS: Windows
- Browser: Firefox 102
- Dark Reader  4.9.52

**Comment by Gusted** [comment]
It's quite weird what this site does in order to render the markdown. I don't really think it's fixable, because they replace the whole DOM and therefor Dark Reader doesn't get notified about the removal of Dark Reader styles. I don't think there is a small workaround to help this edge-case. Wont't fix.
