### ISSUE TITLE
Thunderbird compatibility

### ISSUE THREAD

**Issue by birdie-github** [darkreader/darkreader#946]
If it's not too much to ask, please add Thunderbird 60+ compatibility.

I'm fully aware of dark themes but they leave the message pane unthemed (it's not realistically possible to theme it anyways).

Thank you!

**Comment by olee** [comment]
Any activity on this?
I would love to port this for thunderbird as well, but don't really know where to start at.

**Comment by fluffynuts** [comment]
This would make mail so much easier to read -- please Make It So!

**Comment by MeFisto94** [comment]
Now with Thunderbird shipping a stock dark theme, which still doesn't even theme plaintext messages, this addon would be a real benefit.

What exactly is it that causes problems? Are there any at all?

**Comment by LumKitty** [comment]
Another vote for handling Thunderbird messages

**Comment by kloetpatra** [comment]
yes, please add it to thunderbird

**Comment by ElhemEnohpi** [comment]
I downloaded the .xpi file and was able to install it in the latest Thunderbird 68.5. It doesn't work to make mail messages dark. However, it does actually install, there is a button on the toolbar that opens the Dark Reader menu and the UI seems to work, and it actually functions if you go to search for addons on the Thunderbird addon site - it makes it dark.

I don't know what would be involved in making it also work on the mail messages. Maybe a simple change, maybe impossible... but it would be great if it could be done!

**Comment by Gusted** [comment]
Thunderbird addons are very diffrent than Firefox Add-on, adding this will means making Dark Reader from scratch.

**Comment by DarkArc** [comment]
Oh are they still XUL based instead of web extension? :(

**Comment by Gusted** [comment]
![image](https://user-images.githubusercontent.com/25481501/84826252-f7bda900-b022-11ea-89cf-4dbc6d28c1bd.png)
Yep...

**Comment by Gusted** [comment]
DeepDark addon ^ Suggest to use that

**Comment by olee** [comment]
But it does not make email content dark which is what we want here.
But I guess then someone just has to write a new extension which integrates the dark-mode algorithm from darkreader into a thunderbird extension.
Maybe I should give it a try 😅

**Comment by Gusted** [comment]
Go ahead it's just very different a web extension than a thunderbird addon

**Comment by ElhemEnohpi** [comment]
Hm, that can't be right... they are definitely WebExtension based, no longer XUL.

Thunderbird 68 is the last version to support XUL-type addons like the above example DeepDark (which is anyway a UI Theme, and doesn't affect content). As of next month's release of Thunderbird 78, only MailExtensions are supported. MailExtensions are very similar to WebExtensions, and use many of the same APIs as Firefox. It's not true that a WebExtension must be re-built from scratch to work in Thunderbird. See: [Thunderbird WebExtension APIs](https://thunderbird-webextensions.readthedocs.io/en/latest/)

As I noted, DarkReader _already_ installs and runs in Thunderbird 68, but it only works on its web content pages, not the mail messages or composer. I don't know how much work it would be to make it do that,  maybe too much or more than it's worth, but I think it's not "from scratch".

It's possible to use static CSS in Thunderbird's `userContent.css` and the "Fonts & Colors" preferences to get dark content, but it doesn't always work very well. It would be nice to have Dark Reader's dynamic mode instead.

**Comment by Gusted** [comment]
I will take a look soon

**Comment by Gusted** [comment]
![](https://i.imgur.com/Rs6Hv83.png) 
Well the mail is rendered in HTML and seeing contentScripts is supported it's just a matter of injecting the content-script into the mailContext and Poof Compatibility(I hope so)

**Comment by olee** [comment]
This would be so awesome - it seems you guys are way more knowledgeable than me regarding those addons so I think I better wait for some new results from you 😄

**Comment by Gusted** [comment]
Well not sure WebExtension is quite hard still reading the documentation

**Comment by Jakeler** [comment]
> Oh are they still XUL based instead of web extension? :(

Only partly. XUL is now deprecated in favor of WebExtensions. It is still supported as legacy mode, but they started to remove/disable more features. Many add-ons (even builtin ones) still use it though, because the Webextension API has not all old capabilities. Special Thunderbird APIs are very much work in progress... I recently had to rewrite an old add-on as webextension and it is really a difficult situation. Docs are here: https://thunderbird-webextensions.readthedocs.io/en/68/index.html

So back to topic: In theory it is very simple, just modify the message element style. Same as @Gusted I noticed that `<browser> `element, which contains the email content. Could not find any description what a browser tag in HTML means, but It looks like an `iframe`. It has indeed the same interface and this works in the console:
```js
document.getElementById('messagepane').contentDocument.body.style.background = '#444'
```
Makes at least plaintext mails dark!

Now the real question is of course how to do it from the extension. In a browser this would be done with a injected script. 
I tried multiple options:
- Defining a content_script in `manifest.json` as with  "matches": ["<all_urls>"]. 
Does not do anything, no error, no noticeable injection or execution.
- `browser.tabs.executeScript()` Nothing happens, not even an error.
- `browser.tabs.insertCSS()` Nothing again...

The last two options are even mentioned in the Thunderbird docs, but I could not get anything to work. I verified it on Firefox with the same code, all options work as expected there... I assume these APIs are not implemented currently.

**Comment by Gusted** [comment]
> * `browser.tabs.executeScript()` Nothing happens, not even an error.
> 
> * `browser.tabs.insertCSS()` Nothing again...

Because of this, we can't dark it. Btw we need to executeScript due to the dynamic part being handled in the site itself.
Like you said it seems Thunderbird hasn't implemented this.

**Comment by Jakeler** [comment]
Yep... there are already a few related reports:
https://bugzilla.mozilla.org/show_bug.cgi?id=1504475
https://bugzilla.mozilla.org/show_bug.cgi?id=1617021
https://bugzilla.mozilla.org/show_bug.cgi?id=1622502

Might it be possible with [WebExtension Experiments](https://thunderbird-webextensions.readthedocs.io/en/68/how-to/experiments.html)?

**Comment by Gusted** [comment]
Seems like it we just can wait for 5 years until this is fixed. And nope i already give it a try but seems like access is being given to extension to modify the mail content.

**Comment by PeterMacej** [comment]
After reading this discussion, I tried to install Dark Reader into Thunderbird 78.5.0. I never thought that this is possible. I must say it works perfectly for the web content. I'm using Thunderbird also as a RSS reader. In my case, I wanted to see the RSS feeds in dark and Dark Reader works exactly as in Firefox.

I'm happy it works. Maybe Dark Reader should be included also on Thunderbid add-ons site, saying it works for web pages and not emails.

BTW, for emails, I use [Darko](https://addons.thunderbird.net/en-US/thunderbird/addon/darko_t/) extension for this purpose.

**Comment by Jakeler** [comment]
@PeterMacej Darko is interesting, it requires min. TB 78.4.0 and successfully inserts CSS.

Looking again at the bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1504475
It is closed now, they finally added content script support for emails: https://hg.mozilla.org/releases/comm-esr78/rev/56b3590f01ff
So it should be possible to implement it in Dark Reader as well! Way faster than 5 years @Gusted :)

**Comment by Gusted** [comment]
Well, seeing that's possible now. It shouldn't be a hassle to have support for it. As long they don't lack certain functions nor webExtension API's.

**Comment by Jakeler** [comment]
I got it working with the new API! See my PR for details.

If someone wants to try it out without building from source, I have also a release `xpi` uploaded here: 
https://github.com/Jakeler/darkreader/releases/tag/tb

**Comment by olee** [comment]
Does it not work for mail content yet?
I installed it and emails are still white.

**Comment by Jakeler** [comment]
@olee It does work for viewing mail content, at least in my testing on version 78.4.3. Do you have a recent enough version?
Also Gusted added a couple of improvements, please rebuild my branch or use this: https://github.com/Jakeler/darkreader/releases/download/tb/build-thunderbird-improved.xpi

**Comment by Gusted** [comment]
Side-note: I got this problem while testing and debugging for some reasons I didnt find yet. Only way I got it solved was either removing the whole profile folder or going into safe mode.

**Comment by PeterMacej** [comment]
I tried the latest build and it worked fine. The email messages are dark and the web pages in the RSS reader as well.
The compose message is not dark which is exactly as I want it. Please, if you ever consider to make it work also in the compose window, make it optional.

**Comment by Gusted** [comment]
Hi @PeterMacej!

Please read https://github.com/darkreader/darkreader/pull/4372#issuecomment-738296223
I saw [this webExtension composeScripts](https://thunderbird-webextensions.readthedocs.io/en/latest/composeScripts.html) which probably allows us to also darken the compose window.

CC @Jakeler

Regards,
Gusted

**Comment by PeterMacej** [comment]
> Please read [#4372 (comment)](https://github.com/darkreader/darkreader/pull/4372#issuecomment-738296223)

I can confirm the same behavior as described in that and other comments. I have "Use reader's colors" checked. And I use the Default theme, which explains the white compose content.

BTW, I don't use the Dark theme, instead I have [DeepDark](https://addons.thunderbird.net/sk/thunderbird/addon/deepdark-for-thunderbird/) extension. But this is unrelated here.

**Comment by Jakeler** [comment]
@Gusted I have tried the `composeScripts`, it works identically to `messageDisplayScripts` and the fallback script makes the compose windows dark. The main (index) script would need some modification, because it fails to detect a URL here.

But should we add this? Otherwise it can be also done with the builtin themes and I can understand the argument from @PeterMacej that the original style should kept here. Makes it easier to get the style/colors correct if it looks the same for the recipient on the other end.

**Comment by Gusted** [comment]
> that the original style should be kept for writing. Makes it easier to get the style/colors correct if it looks the same for the recipient on the other end.

I agree with this.

**Comment by PeterMacej** [comment]
> But should we add this? Otherwise it can be also done with the builtin themes and I can understand the argument from @PeterMacej that the original style should be kept for writing. Makes it easier to get the style/colors correct if it looks the same for the recipient on the other end.

Exactly. That's the reason I want my compose window with the original colors. I want to see what my recipients get.

**Comment by ElhemEnohpi** [comment]
Hey, it's great that this works! Unfortunately I'm seeing a large increase in CPU usage, from less than 0.1% without DarkReader, to about 8%, just on a plain text e-mail - so almost a hundred times more CPU than usual. I've got 4.9.26 installed from Jakeler's "build-thunderbird-improved.xpi" installed. I went back to the "Darko" extension for now, which doesn't cause any noticeable CPU increase, but isn't nearly as nice... Is there something else I should try?

**Comment by PeterMacej** [comment]
@ElhemEnohpi Do you mean a temporary or permanent CPU usage increase? On my Windows 10, when I turn on DarkReader, CPU jumps from 0.3% to 7%. But after a second or two, it falls back to 0-0.3%. So I think it's OK.

**Comment by Gusted** [comment]
The jumping to a slightly higher CPU usage is Dark Reader analysing the email and make a nice color-scheme based on it. However after a second or 2 it should be back to normal, because #4005 works properly on Thunderbird and therefore gives Dark Reader a 0% idle usage after it's has styled the email. I will check if I can see any other performance improvements specific to Thunderbird as they are mostly a static email.

Personally:
2 seconds to 7% CPU usage won't even bother me at all, it will become a real problem when it's either permanent or it becomes e.g. 20% or any other amount that doesn't sounds right.

**Comment by ElhemEnohpi** [comment]
It's permanent. Thunderbird takes a constant 8% CPU while running idle, with no other addons except DR. It doesn't make a difference what kind of message is being displayed, plain text or HTML. Using Thunderbrid 78.5.1 on macOS 14.

**Comment by Dannniello** [comment]
No CPU issue on my side (Thunderbird 78.5 on Fedora 33) - when I change e-mail message there is 2~3% CPU usage on `thunderbird` process maybe for 2s and after that - constant 0.

**Comment by Jakeler** [comment]
> However after a second or 2 it should be back to normal, because #4005 works properly on Thunderbird and therefore gives Dark Reader a 0% idle usage after it's has styled the email.

That seems to be not the case. I can reproduce slight increase in idle cpu usage (TB 78.5.0 on ArchLinux). It happens only with some HTML emails, most of what I get is not affected. One example where it happens are mails for GitHub Universe (from the last few weeks). Other stuff like GitHub notifications that contain simple HTML don't cause it.
With disabled dark reader (global toggle) it goes to absolute 0% after a few seconds, when it is enabled it stays consistently at 0.7% on my desktop instead. On my 7 year old laptop it is 2.8%, that is weakest machine I could find. 
Not really noticeable, considering other browsers, Xorg, audio stuff, etc. is consuming much more, but it is there and measurable.

Then I gradually removed parts of the mail until it got to 0% again and it seems to be triggered by the the head+style section. The mail does not need any content or actual css, just insert
```html
<head>
  <style type="text/css">
  </style>
</head>
```
and it has the idle cpu usage. Inline style/css does not cause it.
Any idea why that is @Gusted?

**Comment by Jakeler** [comment]
@ElhemEnohpi 
Fixed version/build: https://github.com/Jakeler/darkreader/releases/download/tb/build-thunderbird_2020-12-12.xpi

**Comment by j-mikhail** [comment]
I'm having the same issue that @olee reported earlier. Tried both @Jakeler 's builds from earlier and just now, but emails seem to be unaffected. Darkreader's settings seem to be in order, and I'm running TB 78.5.1. Any trick to getting this working?

**Comment by kloetpatra** [comment]
Having the same issue with TB 75.5.1. Emails (html or text) are not dark. Only the welcome window (no email selected) is dark. It also doesn't matter if  compact dark theme is on or off. The error console shows no hint. How can I debug this problem?

**Comment by kloetpatra** [comment]
Just found out that it works in classic view or wide view. It does not work in 3 pane vertical view (where email body is on the right side).
Probably it is related to the [same issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1674932) that exists with the [Darko addon](https://addons.thunderbird.net/en-US/thunderbird/addon/darko_t/).

**Comment by Gusted** [comment]
> Just found out that it works in classic view or wide view. It does not work in 3 pane vertical view (where email body is on the right side).
> Probably it is related to the [same issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1674932) that exists with the [Darko addon](https://addons.thunderbird.net/en-US/thunderbird/addon/darko_t/).
> 
> Edit: will be fixed in TB 78.6, Switching to classic view and back to vertical will make it work until TB is restarted.

Thanks for linking the issue, most of the Issue I had without any explanation was described in here. seems like the latest version of TB is just a bit buggy 😄

**Comment by ElhemEnohpi** [comment]
@Jakeler - the new build seems to fix the problem, including using it with the Quote Colors extension, thanks! Also my laptop, which is very old and weak and has a hard time just getting up the stairs, thanks you :)

**Comment by ElhemEnohpi** [comment]
Compose / editor window: It would be nice if there was an option for DR to work in the compose window. When I have the dark theme enabled in Thunderbird, the compose window is dark, but currently it works very poorly.

When replying, quoted text is often unreadable, because some MTA's (Outlook for example) will specify a black font colour, and this is shown as black on almost-black in the compose window. 

TB had at first tried to implement dark mode in message display, but backed out because of these kinds of problems where they couldn't get it to work right: [77.0b3 beta dark background color in mail reader](https://bugzilla.mozilla.org/show_bug.cgi?id=1639249). But they didn't back out of dark mode in the compose window, which has the same problems  (see: [dark mode color changes in editor not correct](https://bugzilla.mozilla.org/show_bug.cgi?id=1643092), etc.). Probably they should. Either way, since Dark Reader gets it right for message display, I think it would also work for composition.

It should be optional so people who want to set and see specific colours can do so. But for people like me who never set colours, I'd rather have a working dark mode display when composing a message. Maybe the Dark Reader button could also show in the Composition Toolbar, so that you can have separate settings?

**Comment by Jakeler** [comment]
TB 78.6.0 got released now, indeed fixing the bug in vertical layout.
@kloetpatra @j-mikhail @olee

**Comment by Jakeler** [comment]
@ElhemEnohpi: This would be certainly possible with [composeAction](https://thunderbird-webextensions.readthedocs.io/en/78/composeAction.html) for the button and `composeScripts` as already mentioned. 
While I agree that this could be a useful, I think it is fine to focus on the message display for the basic compatibility here. The compose window function needs more changes, so I think it is a topic for a separate issue/PR and could be added later.

**Comment by Gusted** [comment]
I had some testing with the `composeScripts` API and found out that the compose window is quite weird, it doesnt have a URL, however it's considered as an IFrame, whereby the URL is `about:blank?compose`, this already causes issues but can be fixed. You can't open any devtools inside the compose window and therefore makes debugging impossible.

**Comment by Gusted** [comment]
Hi everyone!

We just release 4.9.27 which officially includes Thunderbird support(Major thanks to @Jakeler) and Dark Reader is coming to the thunderbird's add-on store. 🎉 

There are in this version some rare cases where the start-up 'crashes' and therefore won't initialize Dark Reader. I tried to fix this with #4843 and personally this issue doesn't encounter me any more. I would like some people to test it out(https://github.com/darkreader/darkreader/pull/4843#issuecomment-764883325) and have confirmation that it works like intended.

Regards,
Gusted

**Comment by alexanderby** [comment]
Thanks to @Jakeler Dark Reader is released for Thunderbird. Please check it out https://addons.thunderbird.net/en-US/thunderbird/addon/darkreader/

**Comment by DUOLabs333** [comment]
I don't know what happened, but it just stopped working recently (Thunderbird 78) -- it says "page protected by browser", so it can't theme it.

**Comment by Gusted** [comment]
Please update DR to the newest version.

**Comment by DUOLabs333** [comment]
I did.

**Comment by alexanderby** [comment]
Maybe @Jakeler can help with this.

**Comment by Jakeler** [comment]
I can't really reproduce this, it shows that `page protected` only if no email is selected. It goes away when I click on an email and everything is dark as expected with TB `91.1.1`. The controls in the popup also work fine (besides a big white border, which is only an cosmetic issue).
Are you by any chance on ArchLinux or Manjaro and have the [DR package](https://archlinux.org/packages/community/any/thunderbird-dark-reader/) installed through pacman @DUOLabs333? Because it is still on version `4.9.34`, which is definitely not working with TB 91. The fix in `4.9.34.1` and `4.9.35` works at least for me.
What exact versions and OS do you have?

**Comment by DUOLabs333** [comment]
I use Arch with TB 78, but I install through the Thunderbird store.

**Comment by Jakeler** [comment]
Ok, I played around with TB `78.6.0` up to `78.14.0` now and found that there are issues with other layouts. Then it fails to apply the theme at the startup, even if it is set to the classic layout again. Switching the layout through **Customize > Layout** to something else makes it work again, but just until the next restart. Can you confirm this?
Also TB `91.1` seems to solve it, there it applies the theme for me on all layouts. Maybe you can try upgrading?

**Comment by DUOLabs333** [comment]
I don't see a "Customize". I would upgrade, but I use other extensions that don't work on 91.

**Comment by Jakeler** [comment]
![grafik](https://user-images.githubusercontent.com/13378765/134231814-f7c5d08f-d518-41e6-9192-4d542d5fe198.png)
You don't have this menu entry?

**Comment by DUOLabs333** [comment]
Oh, I see it. I thought you were referring to DR itself. I can't change any setting in Layout though -- it's stuck on "Classic View".

**Comment by Jakeler** [comment]
Hmm, maybe your TB config is somehow corrupted or another addon blocks this. It could help if you reset your complete config in `~/.thunderbird`, you can just rename it like `~/.thunderbird.backup` instead of directly deleting it, so you can simply move it back if this does not help. Then restart TB and setup at least one account, addon, etc again and see if it works. I understand that this is a bit of work, but I can't think of anything else we could try now.

**Comment by DUOLabs333** [comment]
Since a botched partial upgrade forced me to upgrade everything, I can confirm that upgrading to the newest version worked.
