### ISSUE TITLE
[Bug] Automation no longer works in Firefox after the last two releases (4.9.53 and 4.9.54)

### ISSUE THREAD

**Issue by MahdiNazemi** [darkreader/darkreader#9533]
# Bug Report

## Bug Description
Dark Reader does not change the color scheme automatically if the automation mode is set to "Toggle dark/light."

**UPDATE 1:**
"Toggle on/off" is broken too.

**UPDATE 2:**
The feature is broken only when the "Use system color scheme" option is selected.

After the update to 4.9.53, some automation settings were reset. Even after changing those settings to the above configuration, Dark Reader fails to change the color scheme automatically. #9510 does not fix the issue either.

## Expected Behavior
Light mode during the day, Dark mode during the night.

## Actual Behavior
Light mode all day long.

## System Information
- OS: macOS
- Browser: Firefox 103.0.2
- Dark Reader Version: 4.9.54

**Comment by MahdiNazemi** [comment]
Setting the "Change browser theme" option similarly affects the extension's behavior (i.e., it ignores the automation settings).

**Comment by Bobbsterman** [comment]
Confirming the same bug on Windows.

**System Info:**

- OS: Windows 10
- Browser: Firefox 103.0.2
- Dark Reader Version: 4.9.53

**Comment by adql** [comment]
It may be a continuation of an earlier issue (#7593), where a [workaround](https://github.com/darkreader/darkreader/issues/7593#issuecomment-992195153) helped, but now seemingly not any longer. I'm not sure if it's due to DarkReader or Firefox upgrade. I'm on Manjaro with i3.

**Comment by alexanderby** [comment]
Hi, please try v4.9.55.

**Comment by adql** [comment]
> Hi, please try v4.9.55.

It works, i.e. switches automatically with `Use system color scheme` active.

However, there's a different issue, but I don't know if it's new or I haven't noticed it so far (since I've been using system theme in Firefox settings): when whatever non-system theme is selected in Firefox _and_ DarkReader's `Change the browser's theme` is set to `Custom`, the browser theme does change to DarkReader's custom dark theme on activation, but then changes back to the browser's _system theme_. This doesn't make sense when using automation since this theme (on the browser's side) is itself a light/dark theme (i.e. whatever the system's theme looks like), while DarkReader's _custom_ theme is a dark theme which is supposed to complement the browser's user-selected light theme. This is possibly a separate issue which maybe has already been reported.

**Comment by MahdiNazemi** [comment]
> Hi, please try v4.9.55.

v4.9.55 resolves the issue (Firefox restart is needed).

I will close the issue for now. @adql, please feel free to reopen it if you think the custom theme issue should be taken care of in this thread.

**Comment by AdnanHodzic** [comment]
I still have this same problem with DarkReader 4.9.57 on Firefox (v105) on Ubuntu 22.04.

As part of automation setting both the "active hours" or "active after sunset at location" won't turn it on automatically.

**Comment by nikkwong** [comment]
I'm having this issue on chrome, FWIW

**Comment by AdnanHodzic** [comment]
@nikkwong since this bug is closed and no one is responding to our comments I created a new issue #9903, please feel free to add your comments there.

**Comment by cemakyildiz99-cmd** [comment]
I experienced that i set hour range between 01:00 - 09:00AM for enabling dark mode for this clock range, but i noticed my browser still works default mode, dark mode not enabled.
