### ISSUE TITLE
[Broken Website] web.whatsapp.com

### ISSUE THREAD

**Issue by ShalokShalom** [darkreader/darkreader#9659]
# Broken Website Report

## Website Address

https://web.whatsapp.com/

## Problematic Observation

WhatsApp Web requires a QR code from you. In the last 3 years or so, since I use Darkreader, is this an issue. I appreciate your effort, to make all websites Darkreader compatible. 

Again and again has been tried, to make the site work with its QR codes and Darkreader. 

web.whatsapp.com has, in the past and at the present, again and again and again shown, that it makes the QR code on the site, which is needed to login to the site, completely unreadable. 

**THIS IS NOT POSSIBLE** _WITH WHATS APP_. I and others have reported this several times, and I ran into this already a good dozen times. On every device that I setup for me or my friends, is this an issue and I am sick of it. I honestly suggest, to take Whatsapp and if possible, every page with QR code OUT of the list of compatible sites. Or on the list, who does not change the webcontent. Its tiring.

Thanks

## System Information

- OS:  Linux
- Browser:  Firefox
- Dark Reader Version:  current

**Comment by ShalokShalom** [comment]
I also see a solution, that detects QR codes and does _not_ render dark around and especially **INTO** it (as it does now) and such a fancy feature could provide the best user experience. 😄

**Comment by Gusted** [comment]
I'm not sure if Whatsapp should be used as an argument here. I've it mentioned before, it works as intended and since #2748 I never had any problems with their QR code again (nor anybody reported one since) and it isn't even inverted (or touched) in the first place.

The problem is the white borders around it (the icon is left out of the equation as that's allowed per QR's code specification as part of fault tolerance) which is required for whatsapp's implementation to recognize the QR code.

At best this is an separate issue where the current fix/implementation is messing up with the colors for the QR code.
But Dark Reader cannot touch the QR Code itself and the white borders around it are already hardcoded white. I would be really surprised if the icon is an issue here as that indicates a problem with Whatsapp's qr scanning code.

**Comment by Gusted** [comment]
> I'm not sure if Whatsapp should be used as an argument here.

There are certainly sites I've seen where Dark Reader f*cks them up. However they are all very isolated cases and no generic checker in dark reader would be able to detect them (and it's just ridiculous to spend a lot of CPU time on a edge-case of an edge-case IMO).

**Comment by ShalokShalom** [comment]
Idk if its the browser, or something else. I had issues with it again and again, its really tiresome

**Comment by Gusted** [comment]
Unless there's something actionable, there's not much I can do. I cannot magically fix an issue I cannot reproduce or not have an explanation for.

**Comment by ShalokShalom** [comment]
Just exclude web.whatsapp.com from the list if websites who are converted by default

**Comment by Gusted** [comment]
I'm not a fan of doing that, because it's basically slapping an bandage around a possible bug. As well it's nowhere near dark-by-default, so it will create more problems than it solves.

**Comment by Gusted** [comment]
#9747 might solve the problem, after that it's simply the same QR code as without Dark Reader.
