### ISSUE TITLE
[Performance Issue] Breaks live 

### ISSUE THREAD

**Issue by xeruf** [darkreader/darkreader#9731]
# Performance Issue Report

## Website Address
https://refreshless.com/nouislider/examples/#section-colorpicker

## Steps To Reproduce
If I drag a handle slowly the whole way, sometimes there is a lag of a few seconds until the color updates. I guess the recommended solution here is just to turn off Darkreader as it warps the color anyways, just wanted to point it out :)

## System Information

- OS: Arch Linux
- Browser: Firefox 104.0.1
- Dark Reader Version: idk where to find it, I guess latest? This should be accessible somewhere from the pop-up...

## Additional Context
- Does this happen when Dark Reader is disabled? no
- Does this happen in other browsers? idk
- Do you have hardware acceleration enabled? idk

Somewhat related to https://github.com/darkreader/darkreader/issues/9322

**Comment by Gusted** [comment]
Hi @xeruf!

This is expected behavior, this is actually a prevention of a performance issue. The constant modification of the color requires Dark Reader to analyze the color and create an modification for it and then apply it to the element.

We had in the past where this would slow down the tab and browser, so since then there's a "rate limit", which you're currently seeing.

Thanks for reporting this, but this is expected behavior.

**Comment by xeruf** [comment]
What about fully disabling the inversion upon detecting such a change?
