### ISSUE TITLE
[Broken Website] Trivial html page cant be darkened

### ISSUE THREAD

**Issue by doniks** [darkreader/darkreader#9861]
# Broken Website Report

## Website Address
https://ci.ubports.com/job/docs.ubports.com/job/PR-508/7/artifact/_build/html/..index.html

## Steps To Reproduce
- Go to website
- try to get DR to darken the page
- -> page stays white
- other pages on ci.ubports.com can be darkened ok, e.g. https://ci.ubports.com/blue/organizations/jenkins/docs.ubports.com/detail/PR-508/7/artifacts

## Problematic Observation

the page is a trivial handwritten html file

```
<html>
<head>

<meta http-equiv="Refresh" content="0;url=index.html">

<script type="text/javascript">
      <!--
          function Redirect() {
          window.location = "index.html";
          }
          document.write("Redirect via javascript in 1 seconds.");
          setTimeout('Redirect()', 1000);
          // -->
    </script>
</head>
<body>
<a href="[index.html](view-source:https://ci.ubports.com/job/docs.ubports.com/job/PR-508/7/artifact/_build/html/index.html)">Go to start page</a>
</body>
</html>
```

## System Information

- OS: Linux
- Browser: Firefox 104
- Dark Reader Version 4.9.57

**Comment by Gusted** [comment]
This seems like a browser bug, no extensions(other extensions also seems to fail to do anything with this page) are injected into this page, so as far as Dark Reader is concerned this isn't a page which can be modified.

**Comment by doniks** [comment]
mhm. ok. too bad. It's such an eyesore having this giant white flash screen. anyway. thanks for checking!

**Comment by bershanskiy** [comment]
This is a browser limitation (present in Firefox and Safari; Chromium works fine). Dark Reader does not have sufficient privileges to fix this and a fix would be pretty ugly because it would require messing with security header CSP. Given how infrequent this bug is, I'm closing this in favor of a bug filed at W3C WebExtensions group:
https://github.com/w3c/webextensions/issues/285

@doniks Feel free to ping me if you have any questions, but unfortunately we won't be able to fix this bug on Dark Reader's side.
