### ISSUE TITLE
[Bug] background image is scrolled incorrectly if style height is specified

### ISSUE THREAD

**Issue by lvmm** [darkreader/darkreader#9945]
# Bug Report

## Bug Description
Consider the attached file [01.zip](https://github.com/darkreader/darkreader/files/9664859/01.zip) - when DarkReader is disabled and the page is scrolled down background image is displayed everywhere, when DarkReader is enabled parts of the screen which appear at the bottom have no background image

## Steps To Reproduce
* unzip and load the attached file 01.html
* scroll down - parts which appear from the bottom have no background image
* disable DarkReader
* scroll again - parts which appear from the bottom are now indistinguishable from the upper part of the screen

## Expected Behavior
background image should be displayed everywhere

## Actual Behavior
parts which appear from the bottom have no background image

## System Information
- OS: Windows 10, Linux
- Browser: firefox 104, chromium 105
- Dark Reader Version: 4.9.58

## Additional Context
reproducible only if height is specified in style, without height background is shown correctly.

**Comment by Gusted** [comment]
This is expected behavior, `<html>` will always have a dark background-color applied by Dark Reader, because that will become the root color of the document(this is to avoid white flashes and specify the color for [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content)) and thus not showing the `repeat-y`, as body's height is not specified to stretch the whole document.

> reproducible only if height is specified in style, without height background is shown correctly.

If I add `height: auto` to `<body>`, it will actually produce "the intended" background-image.
