### ISSUE TITLE
[Broken Website] The local rust book sidebar is not affected

### ISSUE THREAD

**Issue by Samisafool** [darkreader/darkreader#9949]
# Broken Website Report

## Website Address
It's a local address. Install rustup and docs to see

## Steps To Reproduce

- Install rustup
- Install docs
- See `rustup docs --book`

## Problematic Observation

The sidebar is not affected by sepia

## Screenshots

Local:
![Local](https://user-images.githubusercontent.com/59611020/192829090-f013cc32-272a-4a42-80dc-f22e64555aef.png)

Rust book website (https://doc.rust-lang.org/stable/book/):
![Rust book website](https://user-images.githubusercontent.com/59611020/192829328-a40cdb7b-49c6-41c1-aa70-84571ea52fcd.png)

## System Information

- OS: Arch Linux
- Browser: Firefox 105.0.1
- Dark Reader Version: 4.9.58

## Additional Context
The rust docs in the website are correct, but the local docs are broken.

**Comment by Gusted** [comment]
Hi @Samisafool!

This is (unfortunately/luckily) expected behavior, this is a restriction put up by browsers. Extensions cannot fetch files that exist on the file system, even if the current tab is loading them. So Dark Reader has no way of knowing which CSS exist on this local file, however there's a workaround.

The file that rustup opens is: `/home/gusted/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/doc/rust/html/book/index.html`, if we open `/home/gusted/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/doc/rust/html/book/` in the terminal and run: `python -m http.server`, it will open a http server for that folder. You can now navigate to `http://localhost:8000/` and see Dark Reader works again. Make sure you go to localhost and not a loopback ip address, as Firefox will otherwise treat is as a "HTTPS" site, which will run into problems again.

**Comment by Samisafool** [comment]
Right, got it.
